### ISSUE TITLE
我尝试绑定Metahuman的骨骼，但是Custom Bone Setting好像不生效

### ISSUE THREAD

**Issue by ct-source** [endink/Mediapipe4u-plugin#1]
首先感谢大佬！
如题，这块不知是插件的问题，还是说我这边配置的问题呢。
就是如果使用Custom骨骼绑定设置的话，人物就不动了，即使和您预设的UE5绑定成一样的骨骼也不行。
如果大佬能预定义一个Metahuman的骨骼就无敌了！

**Comment by endink** [comment]
> 首先感谢大佬！
> 如题，这块不知是插件的问题，还是说我这边配置的问题呢。
> 就是如果使用Custom骨骼绑定设置的话，人物就不动了，即使和您预设的UE5绑定成一样的骨骼也不行。
> 如果大佬能预定义一个Metahuman的骨骼就无敌了！

metahuamn 骨骼你就用 UE4 预设就可以了呀

**Comment by endink** [comment]
是否可以给一下截图，细节面板的

**Comment by endink** [comment]
Preset用UE5可以驱动 metahuman, 另外UE   Editor有时候有BUG，设置不生效可以修改蓝图变量默认值后重启编辑器，下个版本处理一下

**Comment by ct-source** [comment]
大佬加油！看，我用您的插件做的[Demo](https://www.bilibili.com/video/BV1Nt4y1N7P4/)！

**Comment by endink** [comment]
@ct-source 不用客气，使用就是支持，我关闭这个 issue 了

**Comment by endink** [comment]
BUG is fixed, mark!

**Comment by thenighthunter0** [comment]
> 大佬加油！看，我用您的插件做的[Demo](https://www.bilibili.com/video/BV1Nt4y1N7P4/)！ 谢谢大佬用爱发电！我们想落地低成本虚拟人直播，但凡有盈利我们一定报答您😢！

你好，我按教程尝试了metahuman,重点在人物动作，不需要面部追踪。但是头没有跟着身体一起动。你是怎么把头部也绑定的，有特别的改动，还是就是按教程来的？如果是按教程来的，那可能是我哪里搞错了。
