### ISSUE TITLE
Glitch with Arm IK on Metahuman

### ISSUE THREAD

**Issue by Muscaric** [endink/Mediapipe4u-plugin#10]
First of all huge Thank you for your work! This whole project is amazing! 

While testing the newest version of the patch (20230101) on the Metahuman skeleton inside of MediaPipe4U-Demo project I encountered a big glitch on right arm - it is very distorted and palm always tries to follow the left one.  It only appears when "Use Arm IK" is activated. Same occurs with legs and Leg IK. 

![Glitch_from_V20230101](https://user-images.githubusercontent.com/102788608/210350673-e2e1d06d-a41a-4181-9183-21f385bf6a68.png)

With "Use Arm IK" unchecked it works fine, but the elbow and shoulder distortions are then more pronounced of course. 

Best Regards and Happy New Year!

**Comment by endink** [comment]
I'm guessing this is because your joint axes not aligned to child joint or some other reason. Firstly, please screenshot your model to let me see your local axes of your joint :

For example： "LowerArm" joint has an axis that points towards the “Wrist”

<img width="324" alt="image" src="https://user-images.githubusercontent.com/240164/210352253-355bec50-cdb9-433d-a7b1-895bf9adac22.png">

**Comment by endink** [comment]
BTW, If you can, you can upload the model to Google Drive or One Drive, so that I can test it by myself to find the issue.

**Comment by Muscaric** [comment]
Thank you for the fast response! 

I checked out the axis as you advised and they seem to be aligned with child joints, but are indeed facing in opposite direction:
![Joint_Axis_R_MH](https://user-images.githubusercontent.com/102788608/210372755-aef0042d-736f-476e-a762-a219534c7e31.png)
(The left bodyside looks just like on your image)
I also compared them to SKM_Quinn mesh that you use as default in the demo and which has no such glitch - and they are located same way:
![Comparison_Joint_Axes_MH_Quinn](https://user-images.githubusercontent.com/102788608/210373601-794742bf-922b-4632-a7fb-0c2b87a02dc6.png)
However, I compared Physics assets of both Metahuman and Quinn and found out that Constraints on Physics Bodies on right side look in opposite directions: 
![Comparison_BodyConstraints_MH_Quinn](https://user-images.githubusercontent.com/102788608/210374938-936410b9-05df-4b7b-b0b5-c6f1f5669d22.png)

Could this be because of wrong Constraints orientation? Would it help if I manually rotate constraints inside of Unreal Editor so it becomes symmetrical? 
I am using the standard not modified Metahuman Skeleton and I'm bit afraid to mess it up outside of UE.

**Comment by endink** [comment]
It seems that everything is right, and the positive and negative of the axis does not cause undesirable results. Both positive and negative are OK, as long as they are aligned to child nodes, I tested metahuman a long time ago, I'm not sure what caused your problem, I'll test metahuman again later, hoping to find the problem.

**Comment by Muscaric** [comment]
Thank you very much! I'm looking forward to hear about any updates then. Have a nice day!

**Comment by endink** [comment]
Wait for me to test it first, at this time, as a staging solution, if MediaPipe4U can drive Quinn, You can use IKRetarget to redirect animation from Quinn to metahuman . The time is too late in China now, I'll do metahuman testing tomorrow.

**Comment by Muscaric** [comment]
Thanks for your recommendations, I have tried out retargeting from Quinn and it worked! But I would prefer to directly use MH skeleton + Arm IK, since it has way more natural distortions, especially in shoulder region. 

I also doublechecked whether my model corresponds to the Unreal documentation and everything seems fine – it has all functions and construction blueprints. (Generally I was using an unchanged MetaHuman Blueprint with ABP created by following your tutorial on YouTube)

I will use 20221220 version of your Plugin so far, hopefully you could find the fix for the problem when you’ll have time :)

**Comment by endink** [comment]
sorry , I will fix it asap, because it too slow to dowload metahuman model yesterday in China , so I delay it.

**Comment by endink** [comment]
You mean 20221220 have no this issue？？！

**Comment by endink** [comment]
I believe the latest version of the plugin has fixed this issue, if you confirm that it has been fixed, please help me close this issue, if there are other issues, please continue to report at here, thanks.

This is a serious issue, thank you for report it so quickly ！

**Comment by Muscaric** [comment]
I tested it out and everything works great again. Huge Thank You for the fix!
