### ISSUE TITLE
UE5.2 动捕崩溃

### ISSUE THREAD

**Issue by Unknown792** [endink/Mediapipe4u-plugin#101]
### MediaPipe4U 版本

20230811

### UnrealEngine 版本

5.2.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

使用metahuman 进行动捕。在全身动捕的情况下会出现崩溃问题。
<img width="1036" alt="11027E12-966F-4e53-98D2-2563FD3B40CF" src="https://github.com/endink/Mediapipe4u-plugin/assets/141289258/b8def753-f6a9-4729-a0a3-bccd9b6078bc">

**Comment by endink** [comment]
请提供一个完整的日志文件

**Comment by endink** [comment]
另外，是否你在动补时使用进行了什么操作， M4U 的代码似乎没有 FObjectInitializer::Get 的直接访问

**Comment by Unknown792** [comment]
[UE.log](https://github.com/endink/Mediapipe4u-plugin/files/12368259/UE.log)
我新建了一个项目，添加了metahuman的人偶，然后拷贝了demo中的UI和runtime蓝图，直接运行动捕后就会出现这个崩溃的问题。崩溃的时间可能是开始动捕后立马崩溃，也可能运行1分钟左右才会崩溃

**Comment by endink** [comment]
日志没有太多错误信息，这种错误不太可能发生，似乎是一个不是 UObject 的去访问 FObjectInitializer， 这在正常情况下是不可能的，可能是拷贝时候基类丢失了，首先DEMO 工程是5.1 版本，我不确定你这样拷贝过程中是否会发生问题。

**Comment by endink** [comment]
我向可以清理一下项目，然后重新编译，或许会解决问题

**Comment by Unknown792** [comment]
我清理了项目，切换5.2重新生成打包后运行出现了
<img width="537" alt="69D71FAD-F942-424a-933A-92B16DF29E3A" src="https://github.com/endink/Mediapipe4u-plugin/assets/141289258/23f1c493-3f11-4a00-92ee-d69f7725d4df">
这个错误。
然后我又清空项目使用vs尝试编译，但是提示找不到lib文件库
<img width="1142" alt="27F094D5-3A43-47a0-B72F-3CF9FA0CA3D1" src="https://github.com/endink/Mediapipe4u-plugin/assets/141289258/49096559-e671-418f-b966-21bee0c90b02">
这个文件再插件中原本是有的，但是重新编译的时候就被清除了，接着就提示找不到

**Comment by Unknown792** [comment]
我最新的测试发现，如果动画蓝图中使用了这4个节点中除去head的节点，其他的3个节点只要调用了就会崩溃，并且再关闭动画蓝图后再次打开也会直接崩溃
<img width="1875" alt="79D10DCA-7C21-42fd-9526-8507D56D9221" src="https://github.com/endink/Mediapipe4u-plugin/assets/141289258/68852d58-a8c4-4d75-a09d-4388c681eb8d">

**Comment by Unknown792** [comment]
[MediaPipe4U-Demo.log](https://github.com/endink/Mediapipe4u-plugin/files/12377602/MediaPipe4U-Demo.log)
错误还是FObjectInitializer::Get() can only be used inside of UObject-derived class constructor.这个，并且用小白人和metahuman都一样是这个错误

**Comment by endink** [comment]
新建一个项目，不要复制什么，创建一个动画蓝图，放入三个节点，然后用 M4U工具动补，这个过程不超过 10分钟，如果不会崩溃那是复制时候发生了什么

**Comment by Unknown792** [comment]
如果使用ue自带的正方体骨骼创建的动画蓝图是没问题的，但是如果使用了人偶模型例如小白人或者metahuman之后就会崩溃了

**Comment by endink** [comment]
没懂，你的意思是用第三人称项目模板新建一个项目都会崩溃吗

**Comment by endink** [comment]
如果新建项目都会崩溃麻烦上传一份崩溃日志

**Comment by Unknown792** [comment]
我用的是空项目，然后UE自带的骨骼资产
<img width="361" alt="79392E10-AA96-497d-B0F1-520664BFE3B9" src="https://github.com/endink/Mediapipe4u-plugin/assets/141289258/7634ed7b-5a4d-4329-be90-ff3b0d993a90">
添加完mediapipe的节点之后模拟运行是正常的。然后又添加了一个Metahuman的
<img width="373" alt="E046CAF0-52D1-4cd6-934C-E6FDAF27E716" src="https://github.com/endink/Mediapipe4u-plugin/assets/141289258/3b124dea-9ca0-46c4-b5b0-8089f4cd35a0">
添加完mediapipe的节点之后模拟运行是正常的，但是关闭动画蓝图之后再次打开动画蓝图就崩溃了，错误就是FObjectInitializer::Get() can only be used inside of UObject-derived class constructor.
[M4UTest.log](https://github.com/endink/Mediapipe4u-plugin/files/12378274/M4UTest.log)

**Comment by endink** [comment]
同一个场景中不能有两个 mp 动画蓝图

**Comment by endink** [comment]
感谢反馈，晚点我会复现你的问题，可能是在5.2上的BUG，5.2没有太多的去测试

**Comment by 13122352840** [comment]
请问该问题解决了吗？我用5.1打开demo工程的人物动画蓝图（不是头）就会崩溃，报错也是
FObjectInitializer::Get() can only be used inside of UObject-derived class constructor.

**Comment by endink** [comment]
没有出现你说的问题，已经尽力尝试复现问题，不论是 5.1 还是 5.2 ， 在打开动补，持续动补 10 分钟以上或者反复点击开始停止都没有错误出现，你的日志里我也没有发现和这个相关的错误，建议排查引擎中安装的自定义插件、以及 windows sdk 版本和 VS 版本是否满足插件要求

**Comment by endink** [comment]
建议下载最新版插件，最新版版 DEMO 测试

**Comment by 13122352840** [comment]
不，是打开动画蓝图时候会崩溃，我已经看到最新的问题里 有人遇到跟我同样的问题了

**Comment by endink** [comment]
BUG 已复现，尽快修复~
