### ISSUE TITLE
Component option MediaPipeLiveLink missing

### ISSUE THREAD

**Issue by bradcerenzia** [endink/Mediapipe4u-plugin#105]
### MediaPipe4U Version

20230829

### UE Version

5.0.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

Adding component to actor, MediaPipeLiveLink isn't an option. 

Instructions from: https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/mocap/quick_start/prepare_components.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp#%E5%88%9B%E5%BB%BA-actor

![Screenshot 2023-08-31 180119](https://github.com/endink/Mediapipe4u-plugin/assets/35538/f2337db0-007c-4403-b6b1-52dcbe3409fb)
![Screenshot 2023-08-31 180020](https://github.com/endink/Mediapipe4u-plugin/assets/35538/8fe46413-0cb1-4261-adab-123fad484ca6)
![Screenshot 2023-08-31 175948](https://github.com/endink/Mediapipe4u-plugin/assets/35538/d1a24423-d1b0-4eb2-8c1d-2bb80a8c0cb8)
![Screenshot 2023-08-31 175517](https://github.com/endink/Mediapipe4u-plugin/assets/35538/5837d1ba-fdf9-4e47-b653-e422bcadb44c)
![Screenshot 2023-08-31 175543](https://github.com/endink/Mediapipe4u-plugin/assets/35538/5d04fed3-4a1f-4bbd-b817-80eddd657b2b)

**Comment by endink** [comment]
Its not a Component, its a Actor. Search in content browser and drag it into your map.

**Comment by endink** [comment]
https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/mocap/features/face_link_actor.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by bradcerenzia** [comment]
The instructions for the setup of the actor says to add the list of
components, but the one Media Pipe Live Link is missing.

**Comment by bradcerenzia** [comment]
Ah, I'll try these instructions tonight. Thank you!
