### ISSUE TITLE
Character驱动

### ISSUE THREAD

**Issue by SMChenl** [endink/Mediapipe4u-plugin#107]
### MediaPipe4U 版本

5.1

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

开始动捕后摄像头启用了，但出现画面跳转
采用表情捕捉没有用到导入的Character

https://github.com/endink/Mediapipe4u-plugin/assets/103478329/296d3cbe-5a0a-47b1-9245-33affe4bf959

![微信图片_20230901163048](https://github.com/endink/Mediapipe4u-plugin/assets/103478329/5a2e230c-67fe-4fec-8efc-53a3a2d8cc71)

**Comment by endink** [comment]
最新 demo 已经修复了这个菜单跳转的问题

**Comment by SMChenl** [comment]
我下载了更新时间应该是828的demo跟829的插件重新操作，还是有菜单跳转的问题
![24ec2fe7db3dfe3e5ddfd7cf616b9ef](https://github.com/endink/Mediapipe4u-plugin/assets/103478329/4cc4de76-81e6-4524-b3f0-e8ee9b9a5a20)
![9896e97d68d1270c289e781af75a0af](https://github.com/endink/Mediapipe4u-plugin/assets/103478329/588895b8-b417-4c7c-9138-5001feccabb2)

**Comment by endink** [comment]
不明白，这只是一个简单的 UI， 如果你遇到问题你可以自己修改蓝图，我这里运行是可以正常转到对应的 map 的，这么简单的蓝图都不能修改的吗？

菜单界面只是一个方便打开各个 DEMO 的引导页，不应该放入什么组件，各个 DEMO 你可以直接打开 maps 目录下的 map 来查看
