### ISSUE TITLE
Speech API is not working in packaged build!

### ISSUE THREAD

**Issue by RaiaN** [endink/Mediapipe4u-plugin#109]
### MediaPipe4U Version

Latest

### UE Version

5.1.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

I am using the provided Demo project. I set ASR demo as start game level to test Speech API in the packaged game however it is NOT working. I verified Thirdparty/data/models directory, all models are there (both TTS and ASR). Help?

**Comment by RaiaN** [comment]
[MediaPipe4U-Demo.log](https://github.com/endink/Mediapipe4u-plugin/files/12498027/MediaPipe4U-Demo.log)

**Comment by endink** [comment]
Speech is  Commercial feature, so it only can worked in UE Edtior (free license). 

Refer this for details:

https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/licensing/pay_license.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by endink** [comment]
Sure, but... you are not in China, and payment may be more troublesome...

**Comment by RaiaN** [comment]
It is not a problem, I can buy things via WeChat/AliPay. I just want to know whether Ultimate license will give us what I want (Speech, LipSync and LLM in the packaged game)

**Comment by endink** [comment]
Ultimate include all feature. If you can use WeChat/AliPa or paypal, I think its not a problem, and for each paying user, I will give a test license (2-week Ultimate license) to test packaging and feature before receiving payment.

**Comment by endink** [comment]
The Ultimate version is not available means some features are not ready, like virtual camera, RTMP streaming. The version you download is all the features that are currently available, but some features will not work after you package it because you are using a free license, which is mainly for individual users (for motion capture).

**Comment by RaiaN** [comment]
Thank you! 
> I will give a test license (2-week Ultimate license)
I woud like to try a test license. What is the process? I can email you if needed.

**Comment by endink** [comment]
Give me a email, I will tell you my WeChat account. Sorry, because I dont want to public my wechat account at here.

**Comment by RaiaN** [comment]
I will email you sharping@outlook.com, is that okay?

**Comment by endink** [comment]
This is not a issue about development, Let's close this issue right now, if you're interested in commercial license, We can communicate via email.
