### ISSUE TITLE
编译插件报错

### ISSUE THREAD

**Issue by acolasialiuliu** [endink/Mediapipe4u-plugin#111]
### MediaPipe4U 版本

当前最新

### UnrealEngine 版本

5.2.x

###普通 类型

源码编译

### 问题类型

插件安装

### 错误详细描述

G:\Program Files\Epic Games\UE_5.2\Engine\Plugins\AscentCombatFramework\Source\TargetingSystem\Public\ATSTargetPointComponent.h(11): Error: Unable to find parent class type for 'UATSTargetPointComponent' named 'UCCMLookAtPointComponent'

这是标红那句，麻烦看看。 之前的生成步骤已经成功了。 我也下载过demo，打开都提示插件需要重新编译。

**Comment by acolasialiuliu** [comment]
麻烦删除，我解决了，有个插件冲突

**Comment by acolasialiuliu** [comment]
算了，报错更多了

**Comment by acolasialiuliu** [comment]
[98/100] Link [x64] UnrealEditor-MediaPipe.dll
  正在创建库 G:\work\Unreal Projects\MediaPipe4U\Plugins\HostProject\Plugins\MediaPipe4U\Intermediate\Build\Win64\x64\UnrealEditor\Development\MediaPipe\UnrealEditor-MediaPipe.suppressed.lib 和对象 G:\work\Unreal Projects\MediaPipe4U\Plugins\HostProject\Plugins\MediaPipe4U\Intermediate\Build\Win64\x64\UnrealEditor\Development\MediaPipe\UnrealEditor-MediaPipe.suppressed.exp
StandardMediaPipeAnimInstance.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: bool __cdecl FMediaPipeSourceInfo::IsValid(void)const " (?IsValid@FMediaPipeSourceInfo@@QEBA_NXZ)
MediaPipeGlobalEvents.cpp.obj : error LNK2001: 无法解析的外部符号 "public: bool __cdecl FMediaPipeSourceInfo::IsValid(void)const " (?IsValid@FMediaPipeSourceInfo@@QEBA_NXZ)
MediaPipeHolisticComponent.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: bool __cdecl FMediaPipeSourceInfo::IsValid(void)const " (?IsValid@FMediaPipeSourceInfo@@QEBA_NXZ)
MediaPipeRetargetCharacter.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: bool __cdecl FMediaPipeSourceInfo::IsValid(void)const " (?IsValid@FMediaPipeSourceInfo@@QEBA_NXZ)
MediaPipeUtils.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: bool __cdecl FMediaPipeSourceInfo::IsValid(void)const " (?IsValid@FMediaPipeSourceInfo@@QEBA_NXZ)
RuntimeRetargetAnimInstance.gen.cpp.obj : error LNK2001: 无法解析的外部符号 "public: bool __cdecl FMediaPipeSourceInfo::IsValid(void)const " (?IsValid@FMediaPipeSourceInfo@@QEBA_NXZ)
后边都是大量的无法解析外部符号，刚才我看开始计数了，以为成功了

**Comment by acolasialiuliu** [comment]
[99/100] Link [x64] UnrealEditor-MediaPipeEditor.dll
  正在创建库 G:\work\Unreal Projects\MediaPipe4U\Plugins\HostProject\Plugins\MediaPipe4U\Intermediate\Build\Win64\x64\UnrealEditor\Development\MediaPipeEditor\UnrealEditor-MediaPipeEditor.suppressed.lib 和对象 G:\work\Unreal Projects\MediaPipe4U\Plugins\HostProject\Plugins\MediaPipe4U\Intermediate\Build\Win64\x64\UnrealEditor\Development\MediaPipeEditor\UnrealEditor-MediaPipeEditor.suppressed.exp

就这俩步，创建这个库出错

**Comment by endink** [comment]
感觉是你用 VS 执行过Clean 或者 Rebuild,把插件文件给删除了

**Comment by endink** [comment]
另外，你确认你下载的是5.2对应的插件吗，版本下载错了编译不过去的

**Comment by acolasialiuliu** [comment]
确定下的是5.2，我在看看

**Comment by endink** [comment]
尝试下面的清理步骤:      

1. 重新下载插件
2. 删除工程中的以下目录:   
 - DerivedDataCache
 - Intermediate
 - Saved
 - Binraries

3. 右键点击 uproject 弹出菜单点击 generate visualstudio files.

4. 双击.sln 打开VS,开始 Build
5. 关闭 VS 双击 .uproject 打开 UE

**Comment by acolasialiuliu** [comment]
感谢大佬，搞定了，感谢
