### ISSUE TITLE
Crashes of MediaPipe4U-Demo for V. 20230104

### ISSUE THREAD

**Issue by Muscaric** [endink/Mediapipe4u-plugin#12]
Hello again Mr. Xiao! I didn’t find how to open issues on your MediaPipe4U-Demo Project, so I’ll post it here :)

I was testing out new update of Demo Project with the Ver. 20230104 of MediaPipe4U Plugin. With default Mannequin it works fine, but when I tried to test it on MetaHuman I encountered following problem: 

If I want to replace Quinn with my Metahuman, Unreal crashes. When I want to delete Quinn from the scene I first get a warning that this will break references to _MediaPipeDebugDrawer_ and _BP_MediaPipeRuntime_ and after deleting Quinn and trying to _Play_ the project UE crashes with following error:  
**Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000320**
![Screenshot (344)](https://user-images.githubusercontent.com/102788608/210872742-7922f990-c031-4404-92d1-c0a8980063c7.png)
![Screenshot (341)](https://user-images.githubusercontent.com/102788608/210872784-f0be10eb-ec95-4b7d-bf02-016572d6ab3d.png)

If I just try to add a Metahuman into existing scene without removing Quinn, UE crashes with a message: 
**Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:E:\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 691] Array index out of bounds: 350 from an array of size 342**
![Screenshot (342)](https://user-images.githubusercontent.com/102788608/210872866-58d19276-9624-46d9-8c4b-8ae048204dce.png)

I created Animation Blueprint for MetaHuman following your tutorial on YouTube (_UnrealEngine Mocap plugin --Customize skeleton_) and it is just used on unchanged MetaHuman Blueprint as Animation Blueprint for the Body. With older versions of Demo it worked fine. 

Am I missing something? 

Best Regards,
Maria

**Comment by endink** [comment]
Your question is actually about the usage of UE, it has nothing to do with this plugin, I will close this issue, you need more familiar with UE.
