### ISSUE TITLE
Failed during Build

### ISSUE THREAD

**Issue by heitorboccato** [endink/Mediapipe4u-plugin#120]
### MediaPipe4U Version

20230829

### UE Version

5.1.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

After opening the Rider and inicialize Build project, I get the following errors:

>ImageConsumerProvider.h(8): Error C1083 : Not possible to open and include: 'ImageConsumerProvider.generated.h': No such file or directory

>Microsoft.MakeFile.Targets(44,5): Error MSB3073 : The command "E:\UE_5.1\Engine\Build\BatchFiles\Build.bat MediaPipe4U_DemoEditor Win64 Development -Proj
[JetBrainsLog.ReSharperBuild_2023_10_02_13_08_50_0390.log](https://github.com/endink/Mediapipe4u-plugin/files/12782865/JetBrainsLog.ReSharperBuild_2023_10_02_13_08_50_0390.log)
ect="C:\Users\Pichau\Desktop\DemoUE\MediaPipe4U-Demo\MediaPipe4U_Demo.uproject" -WaitMutex -FromMsBuild" was closed with code 6.

**Comment by endink** [comment]
Clean your project:

1. Delete these folders in your project：
- DerivedDataCache
- Intermediate
- Saved

2. right click .uproject file，select generate visual studio project files
3. Open .sln file with IDE（Visual studio or rider）
4. Build project in IDE


Dont use **clean** or **rebuild** in IDE, it will cause the precompiled files in the plugin to be deleted and you will need to download the plugin again.
