### ISSUE TITLE
Build Fail Error

### ISSUE THREAD

**Issue by dorisiscool** [endink/Mediapipe4u-plugin#121]
### MediaPipe4U 版本

2022.1.1.20230829

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

项目打包

### 错误详细描述

[1/2] Link MediaPipe4U_Demo.exe
   Creating library D:\MediaPipe4U\MediaPipe4U-Demo-main (1)\MediaPipe4U-Demo-main\Binaries\Win64\MediaPipe4U_Demo.lib and object D:\MediaPipe4U\MediaPipe4U-Demo-main (1)\MediaPipe4U-Demo-main\Binaries\Win64\MediaPipe4U_Demo.exp
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol g_type_check_instance_cast referenced in function "public: virtual bool __cdecl FGstAppSinkImpl::Connect(class IGstPipeline *,char const *,char const *,class IGstAppSinkCallback *)" (?Connect@FGstAppSinkImpl@@UEAA_NPEAVIGstPipeline@@PEBD1PEAVIGstAppSinkCallback@@@Z)
GstAppSrcImpl.cpp.obj : error LNK2001: unresolved external symbol g_type_check_instance_cast
GstPipelineImpl.cpp.obj : error LNK2001: unresolved external symbol g_type_check_instance_cast
gstvideoscale2.cpp.obj : error LNK2001: unresolved external symbol g_type_check_instance_cast
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol g_signal_emit_by_name referenced in function "public: enum GstFlowReturn __cdecl FGstAppSinkImpl::OnNewSample(struct _GstElement *)" (?OnNewSample@FGstAppSinkImpl@@QEAA?AW4GstFlowReturn@@PEAU_GstElement@@@Z)
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol g_signal_connect_data referenced in function "public: virtual bool __cdecl FGstAppSinkImpl::Connect(class IGstPipeline *,char const *,char const *,class IGstAppSinkCallback *)" (?Connect@FGstAppSinkImpl@@UEAA_NPEAVIGstPipeline@@PEBD1PEAVIGstAppSinkCallback@@@Z)
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol g_object_set referenced in function "public: virtual bool __cdecl FGstAppSinkImpl::Connect(class IGstPipeline *,char const *,char const *,class IGstAppSinkCallback *)" (?Connect@FGstAppSinkImpl@@UEAA_NPEAVIGstPipeline@@PEBD1PEAVIGstAppSinkCallback@@@Z)
GstAppSrcImpl.cpp.obj : error LNK2001: unresolved external symbol g_object_set
gstvideoscale2.cpp.obj : error LNK2001: unresolved external symbol g_object_set
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_object_unref referenced in function "public: virtual void __cdecl FGstAppSinkImpl::Disconnect(void)" (?Disconnect@FGstAppSinkImpl@@UEAAXXZ)
GstAppSrcImpl.cpp.obj : error LNK2001: unresolved external symbol __imp_gst_object_unref
GstPipelineImpl.cpp.obj : error LNK2001: unresolved external symbol __imp_gst_object_unref
gstvideoscale2.cpp.obj : error LNK2001: unresolved external symbol __imp_gst_object_unref
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_mini_object_unref referenced in function "public: virtual bool __cdecl FGstAppSinkImpl::Connect(class IGstPipeline *,char const *,char const *,class IGstAppSinkCallback *)" (?Connect@FGstAppSinkImpl@@UEAA_NPEAVIGstPipeline@@PEBD1PEAVIGstAppSinkCallback@@@Z)
GstSampleImpl.cpp.obj : error LNK2001: unresolved external symbol __imp_gst_mini_object_unref
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_structure_get_int referenced in function "public: enum GstFlowReturn __cdecl FGstAppSinkImpl::OnNewSample(struct _GstElement *)" (?OnNewSample@FGstAppSinkImpl@@QEAA?AW4GstFlowReturn@@PEAU_GstElement@@@Z)
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_structure_get_string referenced in function "public: enum GstFlowReturn __cdecl FGstAppSinkImpl::OnNewSample(struct _GstElement *)" (?OnNewSample@FGstAppSinkImpl@@QEAA?AW4GstFlowReturn@@PEAU_GstElement@@@Z)
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_caps_get_structure referenced in function "public: enum GstFlowReturn __cdecl FGstAppSinkImpl::OnNewSample(struct _GstElement *)" (?OnNewSample@FGstAppSinkImpl@@QEAA?AW4GstFlowReturn@@PEAU_GstElement@@@Z)
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_caps_from_string referenced in function "public: virtual bool __cdecl FGstAppSinkImpl::Connect(class IGstPipeline *,char const *,char const *,class IGstAppSinkCallback *)" (?Connect@FGstAppSinkImpl@@UEAA_NPEAVIGstPipeline@@PEBD1PEAVIGstAppSinkCallback@@@Z)
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_sample_get_caps referenced in function "public: enum GstFlowReturn __cdecl FGstAppSinkImpl::OnNewSample(struct _GstElement *)" (?OnNewSample@FGstAppSinkImpl@@QEAA?AW4GstFlowReturn@@PEAU_GstElement@@@Z)
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_bin_get_type referenced in function "public: virtual bool __cdecl FGstAppSinkImpl::Connect(class IGstPipeline *,char const *,char const *,class IGstAppSinkCallback *)" (?Connect@FGstAppSinkImpl@@UEAA_NPEAVIGstPipeline@@PEBD1PEAVIGstAppSinkCallback@@@Z)
GstAppSrcImpl.cpp.obj : error LNK2001: unresolved external symbol __imp_gst_bin_get_type
gstvideoscale2.cpp.obj : error LNK2001: unresolved external symbol __imp_gst_bin_get_type
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_bin_get_by_name referenced in function "public: virtual bool __cdecl FGstAppSinkImpl::Connect(class IGstPipeline *,char const *,char const *,class IGstAppSinkCallback *)" (?Connect@FGstAppSinkImpl@@UEAA_NPEAVIGstPipeline@@PEBD1PEAVIGstAppSinkCallback@@@Z)
GstAppSrcImpl.cpp.obj : error LNK2001: unresolved external symbol __imp_gst_bin_get_by_name
GstAppSinkImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_video_format_from_string referenced in function "public: enum GstFlowReturn __cdecl FGstAppSinkImpl::OnNewSample(struct _GstElement *)" (?OnNewSample@FGstAppSinkImpl@@QEAA?AW4GstFlowReturn@@PEAU_GstElement@@@Z)
GstAppSrcImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_buffer_new_wrapped_full referenced in function "public: virtual void __cdecl FGstAppSrcImpl::PushBuffer(class IGstAppSrcBuffer *)" (?PushBuffer@FGstAppSrcImpl@@UEAAXPEAVIGstAppSrcBuffer@@@Z)
GstAppSrcImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_flow_get_name referenced in function "public: virtual void __cdecl FGstAppSrcImpl::PushBuffer(class IGstAppSrcBuffer *)" (?PushBuffer@FGstAppSrcImpl@@UEAAXPEAVIGstAppSrcBuffer@@@Z)
GstAppSrcImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_app_src_get_type referenced in function "public: virtual void * __cdecl FGstAppSrcImpl::`scalar deleting destructor'(unsigned int)" (??_GFGstAppSrcImpl@@UEAAPEAXI@Z)
GstAppSrcImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_app_src_push_buffer referenced in function "public: virtual void __cdecl FGstAppSrcImpl::PushBuffer(class IGstAppSrcBuffer *)" (?PushBuffer@FGstAppSrcImpl@@UEAAXPEAVIGstAppSrcBuffer@@@Z)
GstAppSrcImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_app_src_end_of_stream referenced in function "public: virtual void * __cdecl FGstAppSrcImpl::`scalar deleting destructor'(unsigned int)" (??_GFGstAppSrcImpl@@UEAAPEAXI@Z)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_plugin_get_name referenced in function "public: static bool __cdecl FGstCoreImpl::Init(char const *,char const *)" (?Init@FGstCoreImpl@@SA_NPEBD0@Z)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_plugin_feature_list_free referenced in function "public: static bool __cdecl FGstCoreImpl::Init(char const *,char const *)" (?Init@FGstCoreImpl@@SA_NPEBD0@Z)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_registry_get referenced in function "public: static bool __cdecl FGstCoreImpl::Init(char const *,char const *)" (?Init@FGstCoreImpl@@SA_NPEBD0@Z)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_registry_scan_path referenced in function "public: static bool __cdecl FGstCoreImpl::Init(char const *,char const *)" (?Init@FGstCoreImpl@@SA_NPEBD0@Z)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_registry_get_plugin_list referenced in function "public: static bool __cdecl FGstCoreImpl::Init(char const *,char const *)" (?Init@FGstCoreImpl@@SA_NPEBD0@Z)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_init referenced in function "public: static bool __cdecl FGstCoreImpl::Init(char const *,char const *)" (?Init@FGstCoreImpl@@SA_NPEBD0@Z)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_is_initialized referenced in function "public: static bool __cdecl FGstCoreImpl::Init(char const *,char const *)" (?Init@FGstCoreImpl@@SA_NPEBD0@Z)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_deinit referenced in function "public: static void __cdecl FGstCoreImpl::Deinit(void)" (?Deinit@FGstCoreImpl@@SAXXZ)
GstCoreImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_version referenced in function "public: static bool __cdecl FGstCoreImpl::Init(char const *,char const *)" (?Init@FGstCoreImpl@@SA_NPEBD0@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol g_error_free referenced in function "public: virtual bool __cdecl FGstPipelineImpl::Init(char const *,char const *)" (?Init@FGstPipelineImpl@@UEAA_NPEBD0@Z)
GstUtils.cpp.obj : error LNK2001: unresolved external symbol g_error_free
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol g_clear_error referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol g_free referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstUtils.cpp.obj : error LNK2001: unresolved external symbol g_free
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol g_main_loop_new referenced in function "public: virtual bool __cdecl FGstPipelineImpl::Start(void)" (?Start@FGstPipelineImpl@@UEAA_NXZ)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol g_main_loop_run referenced in function "void __cdecl ThreadWorkerFunc(class FGstPipelineImpl *)" (?ThreadWorkerFunc@@YAXPEAVFGstPipelineImpl@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol g_main_loop_quit referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol g_main_loop_unref referenced in function "public: virtual void __cdecl FGstPipelineImpl::Stop(void)" (?Stop@FGstPipelineImpl@@UEAAXXZ)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_message_type_get_name referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_message_parse_error referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_message_parse_warning referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_message_parse_state_changed referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_bus_add_watch referenced in function "public: virtual bool __cdecl FGstPipelineImpl::Init(char const *,char const *)" (?Init@FGstPipelineImpl@@UEAA_NPEBD0@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_seek referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_set_state referenced in function "public: virtual __cdecl FGstPipelineImpl::~FGstPipelineImpl(void)" (??1FGstPipelineImpl@@UEAA@XZ)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_change_state referenced in function "public: virtual bool __cdecl FGstPipelineImpl::Pause(void)" (?Pause@FGstPipelineImpl@@UEAA_NXZ)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_pipeline_get_type referenced in function "public: virtual bool __cdecl FGstPipelineImpl::Init(char const *,char const *)" (?Init@FGstPipelineImpl@@UEAA_NPEBD0@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_pipeline_get_bus referenced in function "public: virtual bool __cdecl FGstPipelineImpl::Init(char const *,char const *)" (?Init@FGstPipelineImpl@@UEAA_NPEBD0@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_parse_launch referenced in function "public: virtual bool __cdecl FGstPipelineImpl::Init(char const *,char const *)" (?Init@FGstPipelineImpl@@UEAA_NPEBD0@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_state_get_name referenced in function "public: int __cdecl FGstPipelineImpl::OnBusMessage(struct _GstMessage *)const " (?OnBusMessage@FGstPipelineImpl@@QEBAHPEAU_GstMessage@@@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_query_position referenced in function "public: virtual bool __cdecl FGstPipelineImpl::CurrentMills(__int64 &)" (?CurrentMills@FGstPipelineImpl@@UEAA_NAEA_J@Z)
GstPipelineImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_query_duration referenced in function "public: virtual bool __cdecl FGstPipelineImpl::SeekPercent(float)" (?SeekPercent@FGstPipelineImpl@@UEAA_NM@Z)
GstSampleImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_buffer_map referenced in function "public: virtual bool __cdecl FGstSampleImpl::Map(void)" (?Map@FGstSampleImpl@@UEAA_NXZ)
GstSampleImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_buffer_unmap referenced in function "public: virtual void __cdecl FGstSampleImpl::Unmap(void)" (?Unmap@FGstSampleImpl@@UEAAXXZ)
GstSampleImpl.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_sample_get_buffer referenced in function "public: virtual void __cdecl FGstSampleImpl::Init(struct _GstSample *,int,int,int)" (?Init@FGstSampleImpl@@UEAAXPEAU_GstSample@@HHH@Z)
GstUtils.cpp.obj : error LNK2019: unresolved external symbol g_filename_to_uri referenced in function "public: static bool __cdecl GstUtils::GetUriFromFilePath(class FString const &,class FString &,bool)" (?GetUriFromFilePath@GstUtils@@SA_NAEBVFString@@AEAV2@_N@Z)
GstUtils.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_uri_protocol_is_supported referenced in function "public: static bool __cdecl GstUtils::IsSupportedSourceUri(class FString const &)" (?IsSupportedSourceUri@GstUtils@@SA_NAEBVFString@@@Z)
GstUtils.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_uri_get_protocol referenced in function "public: static bool __cdecl GstUtils::GetProtocolFromUri(class FString const &,class FString &)" (?GetProtocolFromUri@GstUtils@@SA_NAEBVFString@@AEAV2@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_intern_static_string referenced in function "unsigned __int64 __cdecl gst_videoscale2_get_type_once(void)" (?gst_videoscale2_get_type_once@@YA_KXZ)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_once_init_enter referenced in function "unsigned __int64 __cdecl gst_videoscale2_get_type(void)" (?gst_videoscale2_get_type@@YA_KXZ)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_once_init_leave referenced in function "unsigned __int64 __cdecl gst_videoscale2_get_type(void)" (?gst_videoscale2_get_type@@YA_KXZ)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_log referenced in function "void __cdecl gst_videoscale2_set_property(struct _GObject *,unsigned int,struct _GValue const *,struct _GParamSpec *)" (?gst_videoscale2_set_property@@YAXPEAU_GObject@@IPEBU_GValue@@PEAU_GParamSpec@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_type_name referenced in function "void __cdecl gst_videoscale2_set_property(struct _GObject *,unsigned int,struct _GValue const *,struct _GParamSpec *)" (?gst_videoscale2_set_property@@YAXPEAU_GObject@@IPEBU_GValue@@PEAU_GParamSpec@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_type_class_peek_parent referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_type_register_static_simple referenced in function "unsigned __int64 __cdecl gst_videoscale2_get_type_once(void)" (?gst_videoscale2_get_type_once@@YA_KXZ)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_type_class_adjust_private_offset referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_type_check_class_cast referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_object_class_install_property referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_param_spec_int referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol g_value_get_int referenced in function "void __cdecl gst_videoscale2_set_property(struct _GObject *,unsigned int,struct _GValue const *,struct _GParamSpec *)" (?gst_videoscale2_set_property@@YAXPEAU_GObject@@IPEBU_GValue@@PEAU_GParamSpec@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_mini_object_copy referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_caps_set_simple referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_event_parse_caps referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_static_pad_template_get referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_pad_set_event_function_full referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_pad_event_default referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_plugin_register_static referenced in function "void __cdecl gst_videoscale2_register_static(void)" (?gst_videoscale2_register_static@@YAXXZ)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_factory_make referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_register referenced in function "int __cdecl plugin_init(struct _GstPlugin *)" (?plugin_init@@YAHPEAU_GstPlugin@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_class_add_pad_template referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_get_type referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_add_pad referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_get_static_pad referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_ghost_pad_new_from_template referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_link_many referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_bin_add_many referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_video_info_from_caps referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
D:\MediaPipe4U\MediaPipe4U-Demo-main (1)\MediaPipe4U-Demo-main\Binaries\Win64\MediaPipe4U_Demo.exe : fatal error LNK1120: 84 unresolved externals
[2/2] WriteMetadata MediaPipe4U_Demo.target cancelled
CompilationResultException: Error: OtherCompilationError
   at UnrealBuildTool.ActionGraph.ExecuteActions(BuildConfiguration BuildConfiguration, List`1 ActionsToExecute, List`1 TargetDescriptors, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\System\ActionGraph.cs:line 387
   at UnrealBuildTool.BuildMode.Build(TargetMakefile[] Makefiles, List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 628
   at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 242
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 648
WriteFileIfChanged() wrote 0 changed files of 10 requested writes.
Timeline:

[ 0.000]
[ 0.000](+32.679) <unknown>
[32.679]

**Comment by endink** [comment]
Please install Gstreamer.

Refer this:

https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/Install/gstreamer.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by endink** [comment]
it's a known issue, DesktopPlatform module unsupport shipping mode, and will be fix in next version. New version (include android supoort) will be release at today.
