### ISSUE TITLE
插件安装

### ISSUE THREAD

**Issue by nancenance** [endink/Mediapipe4u-plugin#122]
### MediaPipe4U 版本

版本M4U_5.1（20231011）

### UnrealEngine 版本

5.1.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

插件安装

### 错误详细描述

请问我这里按照步骤：
把插件包放到了ue软件的plugins里删除工程根目录下；
在创建的ueproject中的plugins，修改了makelink里M4U所在目录，并链接了M4U；
然后也用bat清理了project里的intermediate、saved、deriveddatacache、.sln；
重新用generater生成了vs的.sln；
并且用vs2022成功生成了解决方案，但是无法打开.uproject；

这个问题如何解决
![1](https://github.com/endink/Mediapipe4u-plugin/assets/103981443/7a7209e6-ad35-45cb-b48a-7f4de09c8c0a)
![2](https://github.com/endink/Mediapipe4u-plugin/assets/103981443/58ab8142-1ed9-4bc9-b27e-536dd8c738fe)

**Comment by endink** [comment]
发生这个问题通常有两种情况：
**1 操作顺序不对，确保顺序如下：**
    - 1. 链接（或者拷贝）插件到 Plugins  目录
    - 2. 清理项目
    - 3. 生成 vs files
    - 4. 打开 VS 或 Rider 编译
  
如果你确定你的操作顺序和上面一致检查：

VS 或 rider 编译时确保你的编译类型是 Development, 编译条件里选择的是 Editor 而不是 DebugGame 或其他。
