### ISSUE TITLE
口型同步失败

### ISSUE THREAD

**Issue by WZQ1997** [endink/Mediapipe4u-plugin#125]
### MediaPipe4U 版本

20230829

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

我按照文档中操作口型同步，我把语音输出设置在了mediapiperuntime蓝图中通过按钮控制。面部资产使用controlrig pose baker制作的metahuman的。然后在角色的动画蓝图中添加了姿势计算节点和mediapipeLipsync节点，测试运行后只有语音，口型并没有动。
<img width="483" alt="39D355A2-99F9-4af1-8526-978C7AE3901A" src="https://github.com/endink/Mediapipe4u-plugin/assets/39025601/a6e7da81-72e6-4092-bb9f-b5773058466b">

**Comment by endink** [comment]
检查拖动PoseAsset中的曲线模型口型是否变化，检查你的动画蓝图是在头部的网格体上在而不是在body上

**Comment by WZQ1997** [comment]
PoseAsset是由变化的，我放到了metahuman自带的头部动画蓝图中。执行后嘴型也没有动作

**Comment by WZQ1997** [comment]
解决了，是口型资产的问题

**Comment by TDIT-haha** [comment]
> 解决了，是口型资产问题

这个问题你是怎么解决的？能说明下么？我也遇到同样的问题
