### ISSUE TITLE
更新版本后，出现UE崩溃现象

### ISSUE THREAD

**Issue by bayinbilige** [endink/Mediapipe4u-plugin#127]
### MediaPipe4U 版本

M4U_UE5_1_20231011

### UnrealEngine 版本

5.1.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

更新版本后，偶尔出现UE奔溃，今天连续三次闪退，崩溃了。想询问下是什么缘故
[xuniren-backup-2023.10.26-05.07.32.log](https://github.com/endink/Mediapipe4u-plugin/files/13173610/xuniren-backup-2023.10.26-05.07.32.log)

**Comment by endink** [comment]
日志里看不到崩溃信息，是否方便将整个 Savce/Crashes 目录中的内容压缩后上传？

**Comment by endink** [comment]
崩溃如果由插件引起的都是 BUG

**Comment by bayinbilige** [comment]
已发送到您邮箱，这边不支持上传RAR压缩格式

**Comment by bayinbilige** [comment]
[Crashes.zip](https://github.com/endink/Mediapipe4u-plugin/files/13174966/Crashes.zip)

**Comment by bayinbilige** [comment]
[Crashes1.zip](https://github.com/endink/Mediapipe4u-plugin/files/13174992/Crashes1.zip)

**Comment by bayinbilige** [comment]
[Crashes2.zip](https://github.com/endink/Mediapipe4u-plugin/files/13174994/Crashes2.zip)

**Comment by bayinbilige** [comment]
[Crashes3.zip](https://github.com/endink/Mediapipe4u-plugin/files/13175007/Crashes3.zip)

**Comment by bayinbilige** [comment]
您好，分了4个压缩包发给您

**Comment by endink** [comment]
好的，我抽空会看

**Comment by dorisiscool** [comment]
你好， 我也有相同的crash error，请问是如何解决的啊？

**Comment by endink** [comment]
@bayinbilige 你好，你给我的崩溃文件似乎不是最新的，最新的日志都是 10 月份的，你是否能够清理 Crashes 目录， 然后发生崩溃后观察文件文件更新事件以确定这是最后的崩溃日志，然后要锁上传这些文件（去掉旧的文件或文件夹）

**Comment by endink** [comment]
找到一个 10 月 26 号的日志，没有崩溃信息，但是你的程序运行期间有大量的错误：

```
蓝图运行时错误："“无访问”正在尝试读取属性 UltraDynamicSky"。 节点： 设置浮点参数 图表： Update Active Variables 函数： Update Active Variables 蓝图： Ultra_Dynamic_Weather
```

似乎是一个什么天气组件，请你观察程序运行，确保运行过程中不会因为大量的错误和警告打满你的堆栈，这也可能是崩溃的原因。

另外 M4U 发出大量警告：

```
Warning: DynamicTexture pool is full, discard frame.
```

如果你不需要图像回显，请将 `MediaPipeHolisticComponent ` 组件的 `VideoDisplay` 属性设置为 **Raw** 以消除这些警告。
