### ISSUE TITLE
'Media Player Image Source' using 'Img Media Source' Consistently Causes Crash 

### ISSUE THREAD

**Issue by matttidridge** [endink/Mediapipe4u-plugin#129]
### MediaPipe4U Version

2022.0.1

### UE Version

5.1.x

### UnrealEngine Type

Install From Epic Games Launcher

### Platform

Windows

### What happened?

Run the sample scene with the `Media Player Image Source` documentation example, but for `Media` use an `Img Media Source` instead of `File Media Source`.

![image_source_mp_start](https://github.com/endink/Mediapipe4u-plugin/assets/11765663/acbf7b50-8233-4bdc-a145-17a3ffd5278d)

Causes a mediapipe_api crash.

![278203478-dd98b4e7-6992-4d4f-aea3-784f6ddf2dec](https://github.com/endink/Mediapipe4u-plugin/assets/11765663/b55ccb40-aca9-4bb4-920a-ab420c2f8759)

**Comment by matttidridge** [comment]
I need my video file to stay in sync with a Sequencer timeline so 'Media Player Image Source' seems like the only option that will stay in sync with the Sequence while it renders.

**Comment by endink** [comment]
MediaPlayer image source is unstable, I'll check for this error.

If possible, use  gstramer instead.
