### ISSUE TITLE
自定义骨骼body部分无法驱动

### ISSUE THREAD

**Issue by NextBG** [endink/Mediapipe4u-plugin#13]
UE版本：5.0.3
插件版本：20230106

在尝试根据视频教程使用自定义骨骼时发现Pose解算失效（身体部分不动）。Head，Hand以及Location可正常解算驱动

后尝试使用CharacterCreator模型再次根据视频使用自定义骨骼（不使用CharacterCreator预设），问题未得到解决

项目中使用的AnimationBluePrint及MediaPipeRemap资源如图
<img width="533" alt="Remap" src="https://user-images.githubusercontent.com/49566324/211152291-56c250fc-280c-4133-a1ac-fc7a9ac56e05.png">
<img width="437" alt="ABP" src="https://user-images.githubusercontent.com/49566324/211152294-057d919d-367d-4fa6-b572-e4622c4d6caa.png">

**Comment by NextBG** [comment]
驱动效果如图所示，头部手部以及位置可以运动，但身体保持A-Pose
<img width="633" alt="Screenshot 2023-01-07 211555" src="https://user-images.githubusercontent.com/49566324/211152554-2af3d07c-970b-4b29-b375-34aaea9c3f3b.png">

**Comment by endink** [comment]
Auto Setup 导入 UE 有两种骨骼，一种是原生 CC_BASE_xxx 这种命名，这种你选择 CharacterCreator 预设，如果不是，那么就是自动重命名成 UE 风格了，这种选择 UE 预设即可，你要打开 skeleton 资产自己看一下，CC4 其实不需要使用自定义映射，那个教程只是为了展示如何使用自定骨骼功能。目前已知编辑器中可能偶尔出现 C++ 多播委托失效问题，原因未知，可能是 UE 编辑器哪里有小的 BUG，重新停止 play 再开始 play 即可，打包后这个问题不存在。

**Comment by NextBG** [comment]
项目中希望使用的是另一种没有预设的自定义骨骼，使用CC的自定义映射是为了希望能找出问题（看到插件里的CC预设了）

后发现CC模型使用自定义映射也存在同样的问题

此前使用metahuman时尝试使用重映射（以测试重映射功能，未使用预设）时也遇到了相同的问题

**Comment by endink** [comment]
稍后我再测试一下看，没有遇到过这种问题，自定义骨骼其实只是非常简单的代码，按理说不会遇到很复杂的情况~

**Comment by NextBG** [comment]
我在在案例项目MediaPipe4U-Demo里尝试不更改任何其他设置，仅更改BonePreset选项为Custom以及BoneRemap资源，仍然发生了同样的问题，身体pose不动作。
<img width="958" alt="Screenshot 2023-01-10 144133" src="https://user-images.githubusercontent.com/49566324/211480008-6d18d133-9585-4ffa-a044-260b4498605d.png">

remap资源中除了手指部分均做了重映射

所有更改的地方都在截图中展示，希望对你这边的测试有所帮助
<img width="960" alt="Screenshot 2023-01-10 144054" src="https://user-images.githubusercontent.com/49566324/211479978-5ac82884-8785-44ea-b5db-2e9afe0cb68a.png">

**Comment by endink** [comment]
感谢反馈，我会尽快修复

**Comment by Gobcurry** [comment]
我也发现了这个错误，所以我现在在使用UE5白人骨骼通过IK RTG来进行动捕方案，效果还行。只需要livelink节点放在你自己的动画蓝图，也可以进行面捕测试。

**Comment by endink** [comment]
新版测试自定义骨骼没有问题，如果问题依旧，请重新打开 issue

**Comment by endink** [comment]
@NextBG 请阅读文档，理解 MinPoseScoreThresh 属性，或许这个属性设置为 0 是你想要的结果。
