### ISSUE TITLE
能用网络摄像头吗

### ISSUE THREAD

**Issue by JinGuGo** [endink/Mediapipe4u-plugin#132]
### MediaPipe4U 版本

20231011

### UnrealEngine 版本

5.1.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

支持网络摄像头吗，用rtsp，视频流方式，直接获取图像，现在用GStreamerImageSourceComponent，填写地址，UE直接崩溃了

**Comment by endink** [comment]
理论上，Gstreamer 支持的所有 source 都能 在 M4U 中使用 ， 参考这个从视频采集卡获取图像里的讨论：

#126
