### ISSUE TITLE
error after using Mediapipe remap asset

### ISSUE THREAD

**Issue by jossevessies** [endink/Mediapipe4u-plugin#134]
### MediaPipe4U Version

20231011

### UE Version

5.1.x

### UnrealEngine Type

Install From Epic Games Launcher

### Platform

Windows

### What happened?

Dear Anders,

After using a custom bone setup with the remap asset, and manually assigning the bone remapping in the asset.

I get the following error:

PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property MediaPipeAnimInstance". Node:  Is Media Pipe Running Graph:  EventGraph Function:  Execute Ubergraph BP Media Pipe Runtime Blueprint:  BP_MediaPipeRuntime
PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property MediaPipeAnimInstance". Node:  Set Mode Graph:  EventGraph Function:  Execute Ubergraph BP Media Pipe Runtime Blueprint:  BP_MediaPipeRuntime
PIE: Error: Blueprint Runtime Error: "Attempted to assign to None". Node:  Set Mode Graph:  EventGraph Function:  Execute Ubergraph BP Media Pipe Runtime Blueprint:  BP_MediaPipeRuntime
PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property MediaPipeAnimInstance". Node:  Is Media Pipe Running Graph:  EventGraph Function:  Execute Ubergraph BP Media Pipe Runtime Blueprint:  BP_MediaPipeRuntime
PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property MediaPipeAnimInstance". Node:  Set Mode Graph:  EventGraph Function:  Execute Ubergraph BP Media Pipe Runtime Blueprint:  BP_MediaPipeRuntime
PIE: Error: Blueprint Runtime Error: "Attempted to assign to None". Node:  Set Mode Graph:  EventGraph Function:  Execute Ubergraph BP Media Pipe Runtime Blueprint:  BP_MediaPipeRuntime
PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property MediaPipeAnimInstance". Node:  Is Media Pipe Running Graph:  EventGraph Function:  Execute Ubergraph BP Media Pipe Runtime Blueprint:  BP_MediaPipeRuntime
PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property MediaPipeAnimInstance". Node:  Set Mode Graph:  EventGraph Function:  Execute Ubergraph BP Media Pipe Runtime Blueprint:  BP_MediaPipeRuntime

Please note that I was trying to manage to use the remap asset in the Demo file, just to test out the process.

What does happen succesfully is that I see the new model that I have imported from blender in the viewport.

Kindest regards

**Comment by endink** [comment]
Did you use MediaPipe4U demo project? 

What does the “demo file” means ?

**Comment by endink** [comment]
Here is demo project:

https://github.com/endink/MediaPipe4U-Demo

**Comment by jossevessies** [comment]
thanks, but yes indeed. I used this demo project.
This is what I meant with demo file.

everything works great, untill I try to change the model to a custom bone model, that I implemented.
Then I get the above-mentioned error:

PIE: Error: Blueprint Runtime Error: "Accessed None trying to read property MediaPipeAnimInstance". Node: Is Media Pipe Running Graph: EventGraph Function: Execute Ubergraph BP Media Pipe Runtime Blueprint: BP_MediaPipeRuntime


continouously, So I imagine it is something being called every frame.

I thought It might have had to do with that I hadn't made an alternative "animation blueprint" yet.
But even after doing that the error persisted.

really hope you can help me find my way out

**Comment by endink** [comment]
Please build your own blueprint step by step, If you don't know the details of the demo blueprint and change it, it's hard for me to tell you what is wrong, and you have to check the problem yourself, sorry !
