### ISSUE TITLE
动捕崩溃

### ISSUE THREAD

**Issue by WZQ1997** [endink/Mediapipe4u-plugin#136]
### MediaPipe4U 版本

20231010

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

我使用了一个小动物的模型进行动捕，骨骼和metahuman的不一样
<img width="355" alt="屏幕截图 2023-11-27 085739" src="https://github.com/endink/Mediapipe4u-plugin/assets/39025601/d5eacc24-a0da-4002-b210-9b8b7f1e5f95">
运行后并不会动捕

我修改了bone preset 为custom在动捕视频出现骨骼的时候程序就崩溃了
[MediaPipe4U-Demo_2.log](https://github.com/endink/Mediapipe4u-plugin/files/13468997/MediaPipe4U-Demo_2.log)

**Comment by endink** [comment]
你不能在程序运行时修改 Bone preset 属性，这回带来很多意想不到的错误，自定义骨骼你需要自己映射关节点，具体请参考：


https://opensource.labijie.com/Mediapipe4u-plugin/mocap/quick_start/custom_skeleton.html

**Comment by WZQ1997** [comment]
自定义骨骼映射之后可以正确使用，还有一点就是关于面部捕捉需要角色模型做到什么支持才可以用吗。我在商城购买的模型是可以使用NvAR和mediapipe的面捕，但是自定义的模型就不行，自定义的模型有足够的表情支持

**Comment by endink** [comment]
自定义模型你必须有 arkit 的 51 条曲线 (curve)， 就是 51 个苹果表情的 blendshape，或者用面部骨骼做出 51 个 curve， 简单说， iphone arkit 能驱动的角色， M4U 就能驱动
