### ISSUE TITLE
UE5.2无法识别ASR中文模型

### ISSUE THREAD

**Issue by hideoutbush** [endink/Mediapipe4u-plugin#139]
### MediaPipe4U 版本

20230311

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

二次开发

### 错误详细描述

UE5.2版本在将MediaPipeSpeechActor拖入场景中并导入导入ASR模型包后，仍然会出现模型正在加载，无法识别模型文件的情况，再新建空白测试demo后按照b站视频操作仍然出现了模型正在加载的问题。但是UE5.1版本相同操作却能正常运行插件的ASR功能。
![image](https://github.com/endink/Mediapipe4u-plugin/assets/93957385/e01447af-8181-414b-94a9-d0c447dae7d5)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/93957385/9e7bda85-6f4a-48e9-bb2c-5f4c342393bc)

**Comment by endink** [comment]
暂时无力解决，最近很忙，下个版本会对 5.2 专门测试

**Comment by hideoutbush** [comment]
好的，麻烦您了
