### ISSUE TITLE
关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题

### ISSUE THREAD

**Issue by Gobcurry** [endink/Mediapipe4u-plugin#14]
我不知道这个问题属不属于您的解决范围，如果不是，您就忽略我的问题就好了。
我尝试使用一个UE5推流OBS的方案，使用了插件：OWLLivestreamingToolkit，
然后在Rider重新编译后，运行UE5出现了报错，Rider编译没有错误，运行时才会报错，见截图：
![微信截图_20230110183702](https://user-images.githubusercontent.com/117976370/211704811-add53049-abd1-423d-b755-b5eba22dc92e.png)
通过排除法，我发现在Mediapipe和那个插件同时存在时，就会出现上边的错误，我在那边也反馈了错误，希望可以得到解决。

谢谢您

Gobcurry

**Comment by endink** [comment]
首先，这是不是一个没有开源，我很难知道他用了什么东西，也不适合去兼容他，冲突的可能是ffmpeg版本,推流大概率用这个开源方案, 你可以移除mediapipe4u插件中的opencv ffmpeg文件，同时需要排除他用了gstreamer,你可以移除mediapipe4u关于GS 部分定位问题，另外推流是需要 rstp？rtmp?

**Comment by Gobcurry** [comment]
这方面我也不太清楚，所以我先按您的说法试一试吧




Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 中午11:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
首先，这是不是一个没有开源，我很难知道他用了什么东西，也不适合去兼容他，冲突的可能是ffmpeg版本,推流大概率用这个开源方案, 你可以移除mediapipe4u插件中的opencv ffmpeg文件，同时需要排除他用了gstreamer,你可以移除mediapipe4u关于GS 部分定位问题，另外推流是需要 rstp？rtmp?

**Comment by endink** [comment]
虽然我不能去支持这个插件，但是我可以支持OBS，推流是怎么操作呢，虚拟摄像头和窗口捕捉有什么问题吗？

**Comment by Gobcurry** [comment]
我想完成一个在软件中通过UI打开直播预览窗口的功能，他会是一个单独的窗口，然后将这个窗口的画面投影到obs，但因为没有接触过这方面的功能，所以在找方案。而且想让投影的摄像机是一个CineCamera，所以用UE5自带的Scene....2D的那个功能效果不太好，然后尝试了CompoSure插件，但UE5目前不支持这个插件的打包功能，然后我找到了出问题的那个插件，然后出现这个问题


Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
虽然我不能去支持这个插件，但是我可以支持OBS，推流是怎么操作呢，虚拟摄像头和窗口捕捉有什么问题吗？

**Comment by endink** [comment]
Composure 不是官方的东西吗，不支持打包？

**Comment by Gobcurry** [comment]
可以打包，但功能在打包后就失效了，我在csdn找了好久为啥，后来看到有人说Composure在打包后用不了




Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
Composure 不是官方的东西吗，不支持打包？

**Comment by endink** [comment]
感觉是可以打包的，文档里说可以运行时和编辑器使用

**Comment by Gobcurry** [comment]
那我下午再试一下，这问题折磨我一星期了，编辑器运行时效果完美，打包后预览画面中就没有Render Target




Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 中午12:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
感觉是可以打包的，文档里说可以运行时和编辑器使用

**Comment by endink** [comment]
另外，看你的截图，错误似乎是和授权加密的问题有关，似乎不是和我的插件冲突，这块我使用了 OPENSSL 插件，我建议你新建一个空白项目，使用 OWLLivestreamingToolkit （不要使用 MediaPipe4U）, 然后项目中添加 OpenSSL 插件，看是否报错

**Comment by endink** [comment]
OPENSSL 也是官方模块，我没有引入第三方的东西

**Comment by Gobcurry** [comment]
好的，我按您的方法试一下


非常感谢


Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
OPENSSL 也是官方模块，我没有引入第三方的东西

**Comment by Gobcurry** [comment]
我刚才用老版本测试了一下，发现在11月11日下载的mediapipe4U可以和OWLLivestreamingToolkit兼容，项目可以运行，您的插件12月20日发布的版本就会报错了。




Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
OPENSSL 也是官方模块，我没有引入第三方的东西

**Comment by endink** [comment]
抱歉，这个恐怕无法回退，也就无法共存了，因为有一个 Epic 的BUG官方不愿意修复，只能使用它内置的版本方便切换引擎版本，插件其实还是支持了5.1

**Comment by Gobcurry** [comment]
ok，我大概明白了，那比如他那边也使用UE内置的版本是不是就可以了。


Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
抱歉，这个恐怕无法回退，也就无法共存了，因为有一个 Epic 的BUG官方不愿意修复，只能使用它内置的版本方便切换引擎版本，插件其实还是支持了5.1

**Comment by endink** [comment]
是的，因为它不是开源项目，这只是猜测，如果你看到它的插件里有 opencv 相关文件那么大概率是这个问题

**Comment by Gobcurry** [comment]
好的大佬
我刚刚在他的文件夹里搜了一下，好像没有包含OpenCV的文件，我再看看能不能直接问他们插件作者


Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
是的，因为它不是开源项目，这只是猜测，如果你看到它的插件里有 opencv 相关文件那么大概率是这个问题

**Comment by endink** [comment]
如果你购买了它的插件，你可以把这个 github issue 给他，他如果能提供他的技术细节，我可以配合他排查，非开源项目他如果不愿意支持那我也无能为力，实在抱歉

**Comment by Gobcurry** [comment]
好的，我明白了，谢谢您啦




Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于Mediapipe和插件OWLLivestreamingToolkit同时使用出现BUG的问题 (Issue #14)





 
如果你购买了它的插件，你可以把这个 github issue 给他，他如果能提供他的技术细节，我可以配合他排查，非开源项目他如果不愿意支持那我也无能为力，实在抱歉
