### ISSUE TITLE
vs编译失败

### ISSUE THREAD

**Issue by VeCheung** [endink/Mediapipe4u-plugin#141]
### MediaPipe4U 版本

M4U_UE5_2_20231011

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

源码编译

### 问题类型

运行错误

### 错误详细描述

在vs 2022编译错误，无法打开demo工程。尝试删除了Binaries,Intermediate,Saved重新生成vs文件进行编译也不行
![Snipaste_2023-12-08_00-56-07](https://github.com/endink/Mediapipe4u-plugin/assets/153212594/1b8c91ad-27df-4e07-9e92-959b68481d08)

1>D:\Tutorial_Project\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(13): error C2027: 使用了未定义类型“FSlateApplication”
1>C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\ApplicationCore\Public\GenericPlatform\GenericApplication.h(26): note: 参见“FSlateApplication”的声明
1>D:\Tutorial_Project\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(13): error C3861: “Get”: 找不到标识符
1>D:\Tutorial_Project\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(36): error C2027: 使用了未定义类型“FSlateApplication”
1>C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\ApplicationCore\Public\GenericPlatform\GenericApplication.h(26): note: 参见“FSlateApplication”的声明
1>D:\Tutorial_Project\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(36): error C3861: “Get”: 找不到标识符
1>D:\Tutorial_Project\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(59): error C2027: 使用了未定义类型“FSlateApplication”
1>C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\ApplicationCore\Public\GenericPlatform\GenericApplication.h(26): note: 参见“FSlateApplication”的声明
1>D:\Tutorial_Project\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(59): error C3861: “Get”: 找不到标识符
1>[9/12] Compile [x64] FileHelper.gen.cpp
1>[10/12] Link [x64] UnrealEditor-MediaPipe4U_Demo.dll cancelled
1>[11/12] Link [x64] UnrealEditor-MediaPipe4U_Demo.lib cancelled
1>[12/12] WriteMetadata MediaPipe4U_DemoEditor.target cancelled
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: 命令“"C:\Program Files\Epic Games\UE_5.2\Engine\Build\BatchFiles\Build.bat" MediaPipe4U_DemoEditor Win64 Development -Project="D:\Tutorial_Project\MediaPipe4U-Demo-main\MediaPipe4U-Demo.uproject" -WaitMutex -FromMsBuild”已退出，代码为 6。
1>已完成生成项目“MediaPipe4U-Demo.vcxproj”的操作 - 失败。

**Comment by endink** [comment]
Demo 工程不支持 5.2， 看起来是 5.2 头文件做了更改，你非要使用请移除 demo 中的 C++ 文件，剩下的蓝图文件兼容性问题也需要自己处理
