### ISSUE TITLE
我想使用AMediaPipeDebugDrawer中的FVector GetStickManJointPosition(const EMediaPipePoseJoint Joint) const;这个方法

### ISSUE THREAD

**Issue by qinsong729** [endink/Mediapipe4u-plugin#146]
### Feature Category

Blueprint Support

### Feature Description

我想使用这个方法GetStickManJointPosition，或者有其他方法可以获取到StickMan各个Landmark吗？

**Comment by endink** [comment]
能写 C++ 吗？C++ holistic component 上那些 teigger 结尾的委托可以直接获取，蓝图没有暴露事件出来

**Comment by qinsong729** [comment]
可以写C++的，我已经拿到了PoseLandmarksEventTrigger返回的Landmarks，但我想得到3D场景中33个关键点的坐标，我不知道怎么实现

**Comment by endink** [comment]
> 可以写C++的，我已经拿到了PoseLandmarksEventTrigger返回的Landmarks，但我想得到3D场景中33个关键点的坐标，我不知道怎么实现
    
trigger 里的数据就是关键点，mediapipe是归一化（0-1）的坐标，你放大就可以看到小人了, 比如统一 乘 50 试试

**Comment by qinsong729** [comment]
谢谢你

**Comment by qinsong729** [comment]
Your license has expired. Need to update your license file.
最新的license有发布吗？



在 2023-12-27 00:06:52，"Anders Xiao" ***@***.***> 写道：

Closed #146 as completed.
