### ISSUE TITLE
Demo file packing faile

### ISSUE THREAD

**Issue by VeCheung** [endink/Mediapipe4u-plugin#147]
### MediaPipe4U 版本

M4U_UE5_2_20231011

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

项目打包

### 错误详细描述

各方面运行都没问题，到了打包出现Missing precompiled manifest for 'MediaPipeLLMSpeech'的错误。为了排除是版本问题，所以我尝试打包大佬的demo工程，用UE5.1是正常运行的，并且在UE5.1进行打包，也失败了，同样的错误

![MSVC版本](https://github.com/endink/Mediapipe4u-plugin/assets/153212594/3f9e94de-59f3-4166-9848-7bb58c46d769)
![VS版本](https://github.com/endink/Mediapipe4u-plugin/assets/153212594/869a5925-f02b-4ddc-906c-78c809526690)
![系统版本](https://github.com/endink/Mediapipe4u-plugin/assets/153212594/a9d3732d-4768-447f-b274-ffa940c42433)
[Demo项目打包失败.txt](https://github.com/endink/Mediapipe4u-plugin/files/13765230/Demo.txt)

Compile module: MediaPipeLLMSpeech
Missing precompiled manifest for 'MediaPipeLLMSpeech', 'D:\Temp\MediaPipe4U-Demo-main\Plugins\MediaPipe4ULLMSpeech\Intermediate\Build\Win64\UnrealGame\Shipping\MediaPipeLLMSpeech\MediaPipeLLMSpeech.precompiled'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in MediaPipeLLMSpeech.build.cs to override. If part of a plugin, also check if its 'Type' is correct.
BuildException: Missing precompiled manifest for 'MediaPipeLLMSpeech', 'D:\Temp\MediaPipe4U-Demo-main\Plugins\MediaPipe4ULLMSpeech\Intermediate\Build\Win64\UnrealGame\Shipping\MediaPipeLLMSpeech\MediaPipeLLMSpeech.precompiled'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in MediaPipeLLMSpeech.build.cs to override. If part of a plugin, also check if its 'Type' is correct.
   at UnrealBuildTool.UEBuildModuleCPP.Compile(ReadOnlyTargetRules Target, UEToolChain ToolChain, CppCompileEnvironment BinaryCompileEnvironment, List`1 SpecificFilesToCompile, ISourceFileWorkingSet WorkingSet, IActionGraphBuilder Graph, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildModuleCPP.cs:line 388
   at UnrealBuildTool.UEBuildBinary.SetupBinaryLinkEnvironment(ReadOnlyTargetRules Target, UEToolChain ToolChain, LinkEnvironment LinkEnvironment, CppCompileEnvironment CompileEnvironment, List`1 SpecificFilesToCompile, ISourceFileWorkingSet WorkingSet, DirectoryReference ExeDir, IActionGraphBuilder Graph, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildBinary.cs:line 721
   at UnrealBuildTool.UEBuildBinary.Build(ReadOnlyTargetRules Target, UEToolChain ToolChain, CppCompileEnvironment CompileEnvironment, LinkEnvironment LinkEnvironment, List`1 SpecificFilesToCompile, ISourceFileWorkingSet WorkingSet, DirectoryReference ExeDir, IActionGraphBuilder Graph, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildBinary.cs:line 189
   at UnrealBuildTool.UEBuildTarget.Build(BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, TargetDescriptor TargetDescriptor, ILogger Logger, Boolean bInitOnly) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Configuration\UEBuildTarget.cs:line 1995
   at UnrealBuildTool.BuildMode.CreateMakefile(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 757
   at UnrealBuildTool.BuildMode.Build(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 275
   at UnrealBuildTool.BuildMode.Execute(CommandLineArguments Arguments, ILogger Logger) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\Modes\BuildMode.cs:line 242
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\UnrealBuildTool.cs:line 648
WriteFileIfChanged() wrote 0 changed files of 0 requested writes.
Timeline:

[ 0.000]
[ 0.000](+1.219) <unknown>
[ 1.219]

**Comment by endink** [comment]
你安装有多版本的 VC，是否检查了 UE 使用的是最新的 VC，打包输出日志中会显示使用的 VC 版本

**Comment by VeCheung** [comment]
VC版本没问题，我把那三个用不到的AI插件停掉就打包成功了。不过打包出来的程序运行的时候，开启动捕没效果T-T

**Comment by VeCheung** [comment]
用不到的3个AI的插件我关掉了。我自己那个项目打包成功，但是启动不了动捕。Demo工程打包却还是失败的。VC 14.38应该是最新的吧？

UATHelper: Packaging (Windows): GStreamer path:
UATHelper: Packaging (Windows): F:\gstreamer\1.0\msvc_x86_64\
UATHelper: Packaging (Windows): Writing manifest to D:\Temp\MediaPipe4U-Demo-main\Intermediate\Build\Manifest.xml
UATHelper: Packaging (Windows): Using Visual Studio 2022 14.38.33133 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
UATHelper: Packaging (Windows): XGEEXPORT: Exported 'C:\Program Files\Epic Games\UE_5.1\Engine\Intermediate\Build\UBTExport.000.xge.xml'
UATHelper: Packaging (Windows): Total execution time: 1.40 secondsper: Packaging 
UATHelper: Packaging (Windows): Took 1.4917034s to run dotnet.exe, ExitCode=0
UATHelper: Packaging (Windows): Running: C:\Program Files (x86)\Incredibuild\xgConsole.exe "C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.1\UAT_XGE.xml" /Rebuild /NoLogo /ShowAgent /ShowTime /no_watchdog_thread
UATHelper: Packaging (Windows): --------------------Build System Warning---------------------------------------
UATHelper: Packaging (Windows): License not activated:
UATHelper: Packaging (Windows):     License is not activated. Please activate the license in the coordinator.
UATHelper: Packaging (Windows):     This build will run in standalone mode.
UATHelper: Packaging (Windows): -------------------------------------------------------------------------------
UATHelper: Packaging (Windows): Build ID: {DF4C2DEA-40B0-4407-AD52-EF08237650FC}
LogViewport: Scene viewport resized to 1451x843, mode Windowed.
LogViewport: Scene viewport resized to 1451x769, mode Windowed.
LogViewport: Scene viewport resized to 1451x631, mode Windowed.
LogViewport: Scene viewport resized to 1451x521, mode Windowed.
LogViewport: Scene viewport resized to 1451x450, mode Windowed.
LogViewport: Scene viewport resized to 1451x416, mode Windowed.
LogViewport: Scene viewport resized to 1451x390, mode Windowed.
LogViewport: Scene viewport resized to 1451x361, mode Windowed.
LogViewport: Scene viewport resized to 1451x329, mode Windowed.
LogViewport: Scene viewport resized to 1451x305, mode Windowed.
LogViewport: Scene viewport resized to 1451x288, mode Windowed.
LogViewport: Scene viewport resized to 1451x274, mode Windowed.
LogViewport: Scene viewport resized to 1451x261, mode Windowed.
LogViewport: Scene viewport resized to 1451x242, mode Windowed.
LogViewport: Scene viewport resized to 1451x232, mode Windowed.
LogViewport: Scene viewport resized to 1451x224, mode Windowed.
LogViewport: Scene viewport resized to 1451x213, mode Windowed.
LogViewport: Scene viewport resized to 1451x199, mode Windowed.
LogViewport: Scene viewport resized to 1451x184, mode Windowed.
LogViewport: Scene viewport resized to 1451x181, mode Windowed.
UATHelper: Packaging (Windows): --------------------Project: Env_0---------------------------------------------
UATHelper: Packaging (Windows): ** For MediaPipe4U_Demo-Win64-Development
UATHelper: Packaging (Windows): FileHelper.cpp (0:07.90 at +0:00)
UATHelper: Packaging (Windows): D:\Temp\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(13): error C2027: ?????δ?????????FSlateApplication??
UATHelper: Packaging (Windows): C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\ApplicationCore\Public\GenericPlatform\GenericApplication.h(22): note: ?μ???FSlateApplication????????
UATHel(Windows): D:\Temp\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(13): error C3861: ??Get??: ??????????
UATHelper: Packaging (Windows): D:\Temp\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(36): error C2027: ?????δ?????????FSlateApplication??
UATHelper: Packaging (Windows): C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\ApplicationCore\Public\GenericPlatform\GenericApplication.h(22): note: ?μ???FSlateApplication????????
UATHelper: Packaging (Windows): D:\Temp\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(36): error C3861: ??Get??: ??????????
UATHelper: Packaging (Windows): D:\Temp\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(59): error C2027: ?????δ?????????FSlateApplication??
UATHelper: Packaging (Windows): C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\ApplicationCore\Public\GenericPlatform\GenericApplication.h(22): note: ?μ???FSlateApplication????????
UATHelper: Packaging (Windows): D:\Temp\MediaPipe4U-Demo-main\Source\MediaPipe4U_Demo\Private\FileHelper.cpp(59): error C3861: ??Get??: ??????????
UATHelper: Packaging (Windows): error executing C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX64\x64\cl.exe (tool returned code: 2)
UATHelper: Packaging (Windows): ---------------------- Done ----------------------
UATHelper: Packaging (Windows):     Rebuild All: 0 succeeded, 1 failed, 0 skipped
UATHelper: Packaging (Windows): 1 build system warning(s):
UATHelper: Packaging (Windows):    - License not activated
UATHelper: Packaging (Windows): Took 8.192423000000002s to run xgConsole.exe, ExitCode=1
UATHelper: Packaging (Windows): BUILD FAILED: Command failed (Result:1): C:\Program Files (x86)\Incredibuild\xgConsole.exe "C:\Users\Administrator\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.1\UAT_XGE.xml" /Rebuild /NoLogo /ShowAgent /ShowTime /no_watchdog_thread. See logfile for details: 'xgConsole-2023.12.27-19.38.46.txt'
LogSlate: Last resort fallback font was requested. Font: '../../../Engine/Content/Slate/Fonts/DroidSansFallback.ttf', Character: '? (U+02b9)'
LogSlate: Took 0.001978 seconds to synchronously load lazily loaded font '../../../Engine/Content/SlateDebug/Fonts/LastResort.ttf' (5269K)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 11s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=1 (error_Unknown)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: error: Unknown error

**Comment by endink** [comment]
https://opensource.labijie.com/Mediapipe4u-plugin/Install/requirement.html


只要不低于要求的版本就可以，你安装了了最新也要确认 UE 使用了最新，UE EDITOR里可以看到你使用的版本，DEMO 是经过 5.1 打包测试的，而且其他用户也是打包成功，尝试清理目录，重新编译，然后打包

**Comment by endink** [comment]
至于无法动补，你需要找到错误日志，确认你的 license 没有过期

**Comment by endink** [comment]
License 定期发布地址：

https://github.com/endink/Mediapipe4u-plugin/discussions/82

**Comment by VeCheung** [comment]
感谢大佬回复。是这样的，license肯定没过期，最近半个月都在用您给的最新的license（但是今天到期）因为我在UE里各方面测试都是正常的。就是打包后才出现没法动捕，包括打开图显都没有，就像是没把插件打包出来（这个是我自己的UE5.2项目工程）。因为自己的项目打包不成功，所以就打算先尝试Demo工程在UE5.1上面打包成功进行对比排查问题，我也清理过目录重新编译，也翻了其他提交的Issues没找出问题在哪。。。我先看看您说的UE EDITOR里可以看使用的VC版本

**Comment by VeCheung** [comment]
UE EDITOR里没找到，倒是在project setting里面找到这个，不知道大佬说的是不是这个
![Uploading Snipaste_2023-12-28_19-10-22.png…]()

**Comment by VeCheung** [comment]
![Snipaste_2023-12-28_19-10-22](https://github.com/endink/Mediapipe4u-plugin/assets/153212594/2467bd20-c1fa-4bd3-ba7f-5602cb5632b5)

**Comment by endink** [comment]
你的意思是你用最新的版本，Editor 里正常？ 打包后不能动补？

**Comment by endink** [comment]
最新版本确实有个打包 BUG， 需要手动修复，最近太忙了，没时间发版。

参考这个

#130

**Comment by VeCheung** [comment]
是的，在UE里运行都是正常的，打包后不能动捕

**Comment by endink** [comment]
这是我的问题，不好意思

**Comment by endink** [comment]
为什么 提 issue 不给我看错误日志呢， 呵呵， 你给我贴的日志并没有什么有价值的信息。。。。。这个错误日志里会显示找不到模型文件

**Comment by VeCheung** [comment]
您客气了，我想着先排除找问题。但是很懊恼在5.1打包Demo都失败。。。您说的错误日志是UE里直接显示的还是UE指的那个TXT文件？我提交了txt，也复制了UE显示的错误。代码层面我也不确定哪部分才能给您用于诊断我的问题
![Snipaste_2023-12-28_19-19-12](https://github.com/endink/Mediapipe4u-plugin/assets/153212594/ccb64c09-1940-43d8-9a9c-91dc752b31cd)

**Comment by endink** [comment]
着似乎是两个 issue :

1. UE Editor 正常，打包后不正常，参考：   #130 

2 UE 5.2 强行打包 DEMO， 你需要移除 Demo 中的 FileHelper  CPP 文件，因为 5.2 头文件有改动，然后自己找一个插件来弹出选择文件对话框（可有使用 easy dialog 还是什么的一个免费插件 ）

**Comment by VeCheung** [comment]
我更正一下，刚刚没表述清楚。算是两个issue，如果解决了，我后续提多一个issue进行补充说明哈
1.UE Editor 正常，打包后不正常（UE5.2，我自己的项目工程）
2.打包DEMO是用5.1进行打包的，是为了先验证自己电脑的配置环境能够正常打包demo。一次排除是UE版本问题，如果我5.1打包demo成功，我就考虑把项目在5.1里面重新制作一遍进行打包。

**Comment by endink** [comment]
> 我更正一下，刚刚没表述清楚。算是两个issue，如果解决了，我后续提多一个issue进行补充说明哈 1.UE Editor 正常，打包后不正常（UE5.2，我自己的项目工程） 2.打包DEMO是用5.1进行打包的，是为了先验证自己电脑的配置环境能够正常打包demo。一次排除是UE版本问题，如果我5.1打包demo成功，我就考虑把项目在5.1里面重新制作一遍进行打包。

1. 参考 #130 

我们这个 issue 只处理问题 1， 否则我搞不清楚到底要解决哪个问题，你可以另外打开 issue 处理问题 2

**Comment by VeCheung** [comment]
好嘞，我把问题2和相关的信息贴过去。问题1我按照您说的参考试试。非常感谢解答

**Comment by endink** [comment]
按照 #130 的处理办法如果还有问题，你可以继续反馈给我

**Comment by VeCheung** [comment]
打包成功了！！感谢大佬。#130 那个我之前也有看，但是我看他是5.1版本的，所以没参考这个尝试。

**Comment by endink** [comment]
Congratulations ！

**Comment by endink** [comment]
请勿关闭 issue ， 下个版本会修复
