### ISSUE TITLE
 Your license has expired. Need to update your license file. 有最新的license有发布吗？

### ISSUE THREAD

**Issue by qinsong729** [endink/Mediapipe4u-plugin#148]
### MediaPipe4U 版本

M4U_UE5_2_20231011

### UnrealEngine 版本

5.0.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

LogMediaPipe: Error: MediaPipe4U license has expired !

**Comment by qinsong729** [comment]
最新的license是https://github.com/endink/Mediapipe4u-plugin/discussions/82

**Comment by qinsong729** [comment]
最新的license是到2023-12-28日，在这里下载的https://github.com/endink/Mediapipe4u-plugin/discussions/82，已经不能用了

**Comment by endink** [comment]
Updated in discussion
