### ISSUE TITLE
Demo Packaing Failed

### ISSUE THREAD

**Issue by VeCheung** [endink/Mediapipe4u-plugin#149]
### MediaPipe4U 版本

M4U_UE5_1_20231011

### UnrealEngine 版本

5.1.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

项目打包

### 错误详细描述

Demo一直打包失败

![01_打包环境](https://github.com/endink/Mediapipe4u-plugin/assets/153212594/eb3a0a96-f294-47c3-85db-89190c4e5098)
![02_MediaPipe4U-Demo_无任何修改打包失败](https://github.com/endink/Mediapipe4u-plugin/assets/153212594/5b6b73c4-9299-4b75-828f-b5d1a3fce211)
[03_MediaPipe4U-Demo_无任何修改打包失败.log](https://github.com/endink/Mediapipe4u-plugin/files/13786837/03_MediaPipe4U-Demo_.log)
[04_UBT-MediaPipe4U_Demo-Win64-Development.txt](https://github.com/endink/Mediapipe4u-plugin/files/13786838/04_UBT-MediaPipe4U_Demo-Win64-Development.txt)

尝试过清理目录重新编译打包，尝试过重新头加压Demo工程和插件进行运行和打包。劳烦大佬帮忙看看是不是我的打包环境有问题

**Comment by endink** [comment]
不确定是否可以解决，但是可以尝试：

找到 `MediaPipeLLMSpeech.Build.cs`， 修改：   

from
```c#
PrecompileForTargets = PrecompileTargetsType.None;
```

to

```c#
PrecompileForTargets = PrecompileTargetsType.Any;
```
另外，如果你使用免费授权，请移除 AI 相关插件：

- LLM
- Speech
这些插件即使你打包成功，也不会正常工作，因为它不是免费授权可用的插件，具体参考不同授权之间的差异:

https://opensource.labijie.com/Mediapipe4u-plugin/licensing/pay_license.html

**Comment by endink** [comment]
从日志看是插件的预编译文件被你删除了，尝试重新下载插件。
> 如果是免费授权建议别折腾了, 如果强迫症, 可以折腾~

1. 重新下载插件，清理目录，编译，打包
2. 如果一无效，修改 `PrecompileTargetsType.Any`

**Comment by endink** [comment]
另外，你应该注意，` 5.1.1` 并不确保能打包成功，后续版本才会支持 ` 5.1.1`， 目前只能用 `5.1.0`

**Comment by VeCheung** [comment]
好的，明白了，哈哈，那我不折腾了。我那个5.2的项目打包成功了，就可以丢给领导了。我有跟他说AI语音这块的付费功能。感谢解答，那我关闭issue哈

**Comment by endink** [comment]
好的，感谢积极关闭 issue
