### ISSUE TITLE
MediaPipeAnimInstance 切换Mode错误

### ISSUE THREAD

**Issue by qinsong729** [endink/Mediapipe4u-plugin#151]
### MediaPipe4U 版本

M4U_UE5_2_20231011

### UnrealEngine 版本

5.1.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

运行后，我成功从Full Body切换到Half Body，但是我再从Half Body切换到Full Body失败了

**Comment by endink** [comment]
你如何切换的？

**Comment by qinsong729** [comment]
使用MediaPipe4U-Demo工程的Mode选项切换的
![企业微信截图_17047695158576](https://github.com/endink/Mediapipe4u-plugin/assets/287452/2b19295f-c379-4852-8d4a-8c7c19c6583c)
![企业微信截图_17047695465377](https://github.com/endink/Mediapipe4u-plugin/assets/287452/9263a841-f0e1-49c2-81dd-bcdf4a6ece25)
