### ISSUE TITLE
授权咨询

### ISSUE THREAD

**Issue by DD1990** [endink/Mediapipe4u-plugin#16]
插件有效期是多久，如果到期如何获得授权呀

**Comment by endink** [comment]
一般来说会随新版插件发布适当的一起更新授权文件，默认是2个月，你可以在程序里调用API查看，启动也会有提示

**Comment by DD1990** [comment]
能直接购买授权许可吗，永久的

**Comment by endink** [comment]
有永久授权，但是是绑定设备，不可转移的，也有按年付费不限制设备，如果有开发能力，按年付费的许可证放到自己的服务器可以在线刷新，免费许可证不做任何承诺

**Comment by endink** [comment]
商务问题不在这里处理，咨询加Q：27292911
