### ISSUE TITLE
打包后NvAR面捕不生效

### ISSUE THREAD

**Issue by WZQ1997** [endink/Mediapipe4u-plugin#165]
### MediaPipe4U 版本

20231011

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

在ue编辑器中使用测试面捕正常，但是打包后运行程序无法面捕，NvAR和mediapipe都不生效。

**Comment by endink** [comment]
solution：#130

**Comment by WZQ1997** [comment]
我修改了对应的文件，重新打包了游戏，但是结果并没有改变，依然无法使用mediapip和NvAR的面捕

**Comment by WZQ1997** [comment]
现在使用的程序是从另一个硬件一样的主机拷贝过来的，不知道这样是否会有影响

**Comment by endink** [comment]
如果授权文件过期了，在这里下载授权文件

#82

**Comment by WZQ1997** [comment]
![image](https://github.com/endink/Mediapipe4u-plugin/assets/39025601/cdafadb4-fe9e-4ba8-a0b9-b9025d5fc574)

我看了下，我的授权是最新的，我在编译器中是可以正常动捕和面捕的，只有打包后面捕会失效，但是动捕可以用

**Comment by endink** [comment]
那你可以贴一个日志文件出来

**Comment by WZQ1997** [comment]
好的
[MediaPipe4U-Demo.log](https://github.com/endink/Mediapipe4u-plugin/files/15334175/MediaPipe4U-Demo.log)
这是刚打包完成的日志

**Comment by WZQ1997** [comment]
我找到问题了，我的项目中使用了freed 所以打开了livelinkfreed插件，在虚拟制片中需要制作一个预设文件像是这样的
![image](https://github.com/endink/Mediapipe4u-plugin/assets/39025601/dfea453f-1c8f-44c8-8659-fdcdcefac58a)
然后需要在项目设置中添加
![image](https://github.com/endink/Mediapipe4u-plugin/assets/39025601/c445f877-e52b-4adc-bb72-4b00e6b281ae)
添加之后再打包面捕就失效了，去掉这个预设文件就可以正常使用面捕，但是我不清楚这两个功能之间有什么联系

**Comment by endink** [comment]
我用的英文版，如果我没有对照错中英文的话，“预设源”就是 Live Link Presets， Presets 只是将一个 LiveLink Sourfce 保存为 Asset， 然后可以在蓝图中调用 （Apply to Client 函数）将这些数据配置给 LiveLink Client,  M4U 的 FaceLinkActor 也是一种  LiveLink Source ， 或许是多个 Source 覆盖了 subject name ？ 检查 LinkLink 正在使用的 subject name 是不是 "MediaPipe4U" 或者 "NvAR"

**Comment by WZQ1997** [comment]
是的，我创建的freed预设确实把mediapipe4U给覆盖了，所以如果我要使用freed的预设就会导致mediapipe4U的面捕源不能使用

**Comment by endink** [comment]
我应该如何复现这个问题？

**Comment by WZQ1997** [comment]
我解决了这个问题，我改用蓝图加载预设，并且没用apply to client 而是用得add to client 这样就可以互不影响了

**Comment by endink** [comment]
哦，即将发布的新版本中会加入一个函数，强制激活 M4U 源，以提供覆盖预设的能力。

**Comment by endink** [comment]
FaceLinkActor 添加了新的蓝图函数：
```cpp
UFUNCTION(BlueprintCallable, Category="MediaPipe")
void AddLiveLinkSource();

UFUNCTION(BlueprintCallable, Category="MediaPipe")
void RemoveLiveLinkSource();

UFUNCTION(BlueprintCallable, Category="MediaPipe")
bool HasLiveLinkSourceBeenAdded() const;
```
