### ISSUE TITLE
还是自定义骨骼无法驱动的问题

### ISSUE THREAD

**Issue by Gobcurry** [endink/Mediapipe4u-plugin#17]
大佬，春节快乐。
以下是我的问题。
先看截图吧
![微信截图_20230130182517](https://user-images.githubusercontent.com/117976370/215634233-8b5f8765-c3ef-4919-9b22-8822f723345a.png)
![微信截图_20230130182531](https://user-images.githubusercontent.com/117976370/215634236-7c7e5482-8003-43f0-8c25-48a5e020613a.png)
![微信截图_20230130182557](https://user-images.githubusercontent.com/117976370/215634244-a10e322e-9f26-4153-8cd8-85b1dee80d44.png)
![微信截图_20230130182630](https://user-images.githubusercontent.com/117976370/215634297-1355560f-dff6-4af0-b116-3a4d700ed51c.png)
![微信截图_20230130182646](https://user-images.githubusercontent.com/117976370/215634305-127005e4-1e56-4d29-aaf5-aee53f2231c3.png)
![微信截图_20230130182656](https://user-images.githubusercontent.com/117976370/215634313-c4269b8a-ce57-4451-afea-39788e25bd26.png)
![微信截图_20230130182718](https://user-images.githubusercontent.com/117976370/215634322-352fab0c-193d-4998-a377-3a1b94032d93.png)
RemapAsset的骨骼映射我是按照您开发文档中的命名去选的，可能命名不一样，但骨骼选的应该是对的。
最后一张图就是开始摄像机捕捉时的画面，左侧自定义骨骼网格体只有手部和头部可以驱动，（我开了锁脊柱和腿，但不开也是一样效果），右侧Quinn是可以正常驱动的。
我自己的猜测，有可能是我的自定义骨骼有问题，看以下截图
![微信截图_20230131092122](https://user-images.githubusercontent.com/117976370/215635032-4fdcd2b8-e50b-4d96-b033-0210c0a08a5f.png)
![微信截图_20230131092135](https://user-images.githubusercontent.com/117976370/215635051-fe2b4e62-7583-4a2b-9921-ec6cf1eed224.png)
以大臂为例，这个网格体的大臂骨骼是有两根可形变骨骼（具体怎么称呼我也不了解），我不知道这样的骨架构成会不会影响Mediapipe4U的自定义骨骼的动捕。我现在找到的大概有可能是这个问题，也有可能是其他问题，希望您能帮我解答一下。

十分感谢

**Comment by endink** [comment]
目前，一个场景中只能有一个MediapipeAnimInstance (动画蓝图)实例, 因为它需要很多的计算和线程安全，如果你需要很多角色一起运动，其他角色应该重定向，试试从场景中移除Quinn

**Comment by Gobcurry** [comment]
还是一样的效果，昨天我测的时候是只有自定义骨骼，为了给您提交问题所以加上的Quinn，刚才我又删除了Quinn的骨骼网格体，依然是一样的效果




Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月31日(星期二) 上午10:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 还是自定义骨骼无法驱动的问题 (Issue #17)





 
目前，一个场景中只能有一个MediapipeAnimInstance (动画蓝图)实例, 因为它需要很多的计算和线程安全，如果你需要很多角色一起运动，其他角色应该重定向，试试从场景中移除Quinn

**Comment by endink** [comment]
如果方便，把模型共享给我（通过网盘），我可以承诺不会泄露你的模型，还是担心模型泄露的话可以移除贴图，如意不方便给我模型，你可以贴出日志文件

**Comment by endink** [comment]
另外，让我看到你的场景大纲视图

**Comment by Gobcurry** [comment]
链接：https://pan.baidu.com/s/1MqjyS_yxlN8jgKDPYl78aA&nbsp;
提取码：vebw&nbsp;
--来自百度网盘超级会员V6的分享
这个是模型的UE文件，用5.0.3打开就没问题，贴图有1.4个G，所以我删掉了。
下边的是我场景大纲视图：







Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月31日(星期二) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 还是自定义骨骼无法驱动的问题 (Issue #17)





 
另外，让我看到你的场景大纲视图

**Comment by endink** [comment]
私信我，我删除了，B站

**Comment by Gobcurry** [comment]
b站私信您了




Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月31日(星期二) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 还是自定义骨骼无法驱动的问题 (Issue #17)





 
私信我，我删除了，B站

**Comment by endink** [comment]
你的手臂中间有多余的手骨，对于这种结构暂时不支持 IK 和扭曲矫正，直接使用 UE 曼尼重定向到你的角色

**Comment by Gobcurry** [comment]
了解了。确实，我使用ik绑定来映射骨骼的时候也是需要把局部骨骼单独去映射一下，而不能直接对 比如整条手臂创建映射 这样。
谢谢您的回复。


Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月9日(星期四) 晚上10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 还是自定义骨骼无法驱动的问题 (Issue #17)





 
你的手臂中间有多余的手骨，对于这种结构暂时不支持 IK 和扭曲矫正，直接使用 UE 曼尼重定向到你的角色
