### ISSUE TITLE
想替换mediapipe模型

### ISSUE THREAD

**Issue by TDIT-haha** [endink/Mediapipe4u-plugin#171]
### Feature Category

Others

### Feature Description

你好，mediapip4u中对于人体姿态的检测模型是用mediapipe的，那么如果我想把替换mediapipe的姿态模型，我有什么办法替换呢？或是有设置人体姿态数值的接口函数么？可用于我替换模型

**Comment by endink** [comment]
没有源码你做不到的，如果有开源的 C++ 支持的模型，性能和质量能超过 mediapipe 可以告诉我，我可以评估一下

**Comment by endink** [comment]
Onnx?

**Comment by TDIT-haha** [comment]
嗯，对，自己训练的模型想试试效果。

**Comment by endink** [comment]
暂时无法实现自定义模型，我们可以关闭这个 issue
