### ISSUE TITLE
speech_api 运行崩溃

### ISSUE THREAD

**Issue by easonwzs** [endink/Mediapipe4u-plugin#172]
### MediaPipe4U 版本

20240527

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

在我电脑上进行配置MediaPipe4USpeech后 (主要用到 TTS / ASR 功能) 场景中添加 MediaPipeSpeechActor ，在我电脑上编辑器中运行游戏一切正常，
当我的同事从 p4v 上下载项目后，编辑器运行游戏会崩溃：
![img_v3_02c1_c329b13b-79de-45fa-a290-763858c500bg](https://github.com/endink/Mediapipe4u-plugin/assets/4898782/edf93859-ac09-48c6-8e5c-2ccb068fe688)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/4898782/62863fbc-ef03-4893-a35c-731d6a070c32)

**Comment by endink** [comment]
可以提交一个崩溃日志文件， 另外检查是否是 VC 版本过低？

**Comment by endink** [comment]
另外，在 settings -> plugins -> MediaPipe4U Speech 中检查模型状态

**Comment by easonwzs** [comment]
> 可以提交一个崩溃日志文件， 另外检查是否是 VC 版本过低？

崩溃日志：
[XianJianAI.log](https://github.com/user-attachments/files/15922204/XianJianAI.log)

**Comment by easonwzs** [comment]
> 另外，在 settings -> plugins -> MediaPipe4U Speech 中检查模型状态

模型状态都是正常的
![img_v3_02c2_dffe6dc7-409e-42d6-a657-cb5a04fc402g](https://github.com/endink/Mediapipe4u-plugin/assets/4898782/aae99bdb-a6ff-4342-8331-a69d3372c78d)

**Comment by easonwzs** [comment]
> 可以提交一个崩溃日志文件， 另外检查是否是 VC 版本过低？

VS也是最新的 2022 17.10.3
![img_v3_02c2_239e60f6-3076-49b5-a827-a03c34bd954g](https://github.com/endink/Mediapipe4u-plugin/assets/4898782/bec942b8-3709-4666-9615-a5b4b5228324)

**Comment by endink** [comment]
你确定你这个是崩溃日志吗？    
需要你项目里
 Saved/Crashes 里的日志

**Comment by easonwzs** [comment]
> 你确定你这个是崩溃日志吗？ 需要你项目里 Saved/Crashes 里的日志

跟我同事那边又要了一份崩溃日志
[UECC-Windows-4FCC98E24430394686E3D687C5DFB240_0000.zip](https://github.com/user-attachments/files/15926549/UECC-Windows-4FCC98E24430394686E3D687C5DFB240_0000.zip)

**Comment by endink** [comment]
这个崩溃日志最后的错误来自一个 RHI 线程，文件可能不是刚刚发生崩溃时候的日志和 dump 文件，并没有什么和 M4U 相关的信息
