### ISSUE TITLE
webcam拉流问题

### ISSUE THREAD

**Issue by WZQ1997** [endink/Mediapipe4u-plugin#173]
### MediaPipe4U 版本

20230524

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

在编译器或者打包后得程序中，我选择webcam网络摄像头拉流，经常出现拉流后只有黑屏，需要多次停止开启后直到右下角的预览出现ndi得logo时才能拉到流

**Comment by endink** [comment]
网络拉流是什么意思，没有使用 start camera？ rmtp/rtsp 吗？

**Comment by WZQ1997** [comment]
就是网络摄像头 拉的自己推的ndi流
![微信图片_20240712170755](https://github.com/user-attachments/assets/d9620648-5d69-449c-807b-7d4c39e3b3d2)

**Comment by endink** [comment]
推拉流建议使用 Gstreamer, 你可以自定义 Gstreamer 表达式，可以支持市面上几乎所有的网络传输协议

**Comment by endink** [comment]
参考这个视频采集卡的讨论：

#126

**Comment by endink** [comment]
Start camera 必须是一个符合 direct show 标准的 windows 驱动的摄像头，如果你是网络摄像头，例如带 IP 的摄像头，你先要搞清楚他使用的流协议，通常是 rtmp/rtsp, 这种摄像头使用 GS 可以轻松处理

**Comment by endink** [comment]
Ndi 似乎只是一种硬件通讯协议，如果你的摄像头能被识别到，为什么 M4U 不能拉到画面呢？你可以发送一个日志文件上来

**Comment by endink** [comment]
M4U 摄像头使用 opencv 代码，如果驱动出现问题，你还可以使用 mediaplayer image source 然后找 media player 的摄像头插件尝试来驱动摄像头
