### ISSUE TITLE
跪求5.3支持

### ISSUE THREAD

**Issue by yldn** [endink/Mediapipe4u-plugin#174]
### Feature Category

Blueprint Support

### Feature Description

求求了支持一下5.3.2吧 帮帮写论文的孩子

**Comment by endink** [comment]
5.3 不是有下载连接的嘛

**Comment by endink** [comment]
噢噢噢噢，确实跳过了5.3，论文的话你升级一下 UE 也可以的吧

**Comment by endink** [comment]
无力支持，实在抱歉，只能关闭 issue 了
