### ISSUE TITLE
肢体穿模

### ISSUE THREAD

**Issue by TDIT-haha** [endink/Mediapipe4u-plugin#175]
### MediaPipe4U 版本

20240524

### UnrealEngine 版本

5.4.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

其他

### 错误详细描述

你好，我想请教一个问题，在我进行单目驱动数字人的时候，出现手臂穿过身体的情况，对于这个问题的，请问有什么建议可以解决这个问题呢？

**Comment by endink** [comment]
这不是简单可以解决的问题，需要你在 UE 侧处理，比如限制关节角度等

**Comment by xiaoliu-jzc** [comment]
具体如何处理呢，是通过修改骨骼的物理资产加碰撞跟限制关节旋转角度吗
