### ISSUE TITLE
视频动捕卡住问题

### ISSUE THREAD

**Issue by WZQ1997** [endink/Mediapipe4u-plugin#176]
### MediaPipe4U 版本

20230524

### UnrealEngine 版本

5.2.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

使用视频文件动捕 每次使用10~30分钟左右就会卡住，这时停止动捕后更换视频动捕会卡在上一个视频卡住的最后一帧只能关闭程序重新启动才能恢复

**Comment by WZQ1997** [comment]
打包后的程序有时候还会崩溃
[MediaPipe4U-Demo.log](https://github.com/user-attachments/files/16634028/MediaPipe4U-Demo.log)
这个是崩溃的日志

**Comment by endink** [comment]
看起来表情捕捉存在一个复杂的 BUG，只能尝试暂时关闭表情

**Comment by endink** [comment]
开启表情捕捉时候尽量不要开启 LiveLink 窗口，或许这是一个 UI 冲突，具体问题很难复现
