### ISSUE TITLE
AMediaPipeSpeechActor的异步加载会阻塞主线程

### ISSUE THREAD

**Issue by flashyiyi** [endink/Mediapipe4u-plugin#178]
### MediaPipe4U 版本

20230524

### UnrealEngine 版本

5.4.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

ASR在AMediaPipeSpeechActor的异步加载模式实际上还是会卡死主线程，这是正常现象吗？设置为同步则不加载了，手动调用加载也无效。

**Comment by endink** [comment]
卡死肯定不正常，或许是 BUG， 近期暂时无力维护，需要等等

**Comment by endink** [comment]
我不记得是否提供了蓝图函数，记得是有函数可以加载模型的

**Comment by endink** [comment]
现在有空，可以处理一下这个问题，请问你是从 demo 工程运行？
