### ISSUE TITLE
VRM模型使用时，点击启用摄像头后程序崩溃

### ISSUE THREAD

**Issue by FoolishMao** [endink/Mediapipe4u-plugin#18]
感谢作者的工作，我是纯新手，操作上可能会有问题，以下是我使用的步骤：
1.基于https://github.com/endink/MediaPipe4U-Demo
这个项目，使用VRM骨骼建立动画蓝图；
![image](https://user-images.githubusercontent.com/36061157/215650753-66a885ab-c105-4bff-afaa-a8fe02fc8895.png)
2. 修改character里面动画类和骨骼网络体；
![image](https://user-images.githubusercontent.com/36061157/215652662-7cbae024-deb5-4cb1-a4ea-8c88ce4a7d88.png)
3.运行后出现
![image](https://user-images.githubusercontent.com/36061157/215652964-68f2feda-a45a-4bb4-a3c8-7b63975eb420.png)
4. 此时点击启用摄像头会崩溃

**Comment by endink** [comment]
麻烦上传一个日志文件，saved/logs 目录里

**Comment by endink** [comment]
另外，从日志里的警告看你的骨骼没有映射成功

**Comment by FoolishMao** [comment]
[MediaPipe4U_Demo.log](https://github.com/endink/Mediapipe4u-plugin/files/10542995/MediaPipe4U_Demo.log)
刚刚设置了remap，这是崩溃的log文件

**Comment by endink** [comment]
感谢反馈，这看起来是一个严重的 BUG， 我会开始处理它

**Comment by endink** [comment]
另外你的骨骼映射不正确，关于骨骼映射，请参考文档（骨骼要求部分）：

https://opensource.labijie.com/Mediapipe4u-plugin/Install/requirement.html

**Comment by FoolishMao** [comment]
感谢回复，我现在在尝试使用metahuman进行驱动，我在设置character时，按如下设置：
![image](https://user-images.githubusercontent.com/36061157/216909430-e0adeb34-45d1-4439-91d8-dbf38b39f4ea.png)
出现如下错误：LogWindows: Error: Array index out of bounds: 344 from an array of size 342
我的实现有问题吗？
完整log如下：

[MediaPipe4U_Demo.log](https://github.com/endink/Mediapipe4u-plugin/files/10660633/MediaPipe4U_Demo.log)

**Comment by endink** [comment]
为什么你会有这种问题，这看起是骨骼索引错误，你是用自定义骨骼绑定？metahuman 只需要 Preset 选择 UE5 就可以，有非常多的 metahuman 用户，没有反馈过这个问题，有一个非常古老的版本有这个 BUG， 但是那是好几个月以前的事了

**Comment by endink** [comment]
关于崩溃问题已修复，上一个本版没有映射正确的骨骼有可能造成崩溃，关于我发驱动 metahuman 可能是你操作不对。请下载新版插件折腾~

**Comment by FoolishMao** [comment]
感谢你的工作，我试试新版本~
