### ISSUE TITLE
海康摄像头画面延迟很高

### ISSUE THREAD

**Issue by cdutxfy** [endink/Mediapipe4u-plugin#182]
### MediaPipe4U 版本

20240524

### UnrealEngine 版本

5.4.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

其他

### 错误详细描述

大佬你好，我用的海康的监控摄像头测试的，使用的rtsp，运行时视频画面延迟大约有4秒，请问怎样可以减少延迟呢？
![微信截图_20240930173533](https://github.com/user-attachments/assets/7c3d72f3-a868-441d-a753-9cfd7f1b8939)

**Comment by endink** [comment]
降低分辨率是最佳手段,4秒也太多了，恐怕是完全无法使用

**Comment by cdutxfy** [comment]
我在python代码中播放这个rtsp流延迟大概只有1秒，但是在插件中画面延迟就增加到了4秒，是插件需要一些额外的设置吗

**Comment by endink** [comment]
不需要额外设置，但是可以通过降低分辨率来提升帧率，MediaPipeHolisticComponent 上的 ImageSourcd 属性

**Comment by cdutxfy** [comment]
使用gstreamer表达式解决了，现在几乎没有延迟
![微信截图_20241008105245](https://github.com/user-attachments/assets/93c47d98-d629-421e-bb33-291ad5c66820)

**Comment by endink** [comment]
好的，那我关闭这个 issue，其他问题可以开辟新的 issue
