### ISSUE TITLE
插件编译错误

### ISSUE THREAD

**Issue by wm2005wm** [endink/Mediapipe4u-plugin#185]
### MediaPipe4U 版本

20240527

### UnrealEngine 版本

5.3.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

使用UP提供百度网盘下载M4U_UE5_2_20240527进行插件升级编译，出错信息详见附件。请UP百忙中回复，谢谢！！！

**Comment by wm2005wm** [comment]
使用UP提供百度网盘下载M4U_UE5_2_20240527进行插件升级编译，出错信息详见。请UP百忙中回复，谢谢！！！

**Comment by endink** [comment]
我无法为5.3提供支持，插件不支持5.3，实在抱歉
