### ISSUE TITLE
当通过StartVideo按钮指定一个MP4视频后，发生崩

### ISSUE THREAD

**Issue by buaaCCJ** [endink/Mediapipe4u-plugin#186]
### MediaPipe4U 版本

20240527

### UnrealEngine 版本

5.4.x

### 平台

Windows

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

![崩溃](https://github.com/user-attachments/assets/ae78154e-cfc1-4ff4-b4e9-176b78d350c2)
当通过StartVideo按钮指定一个MP4视频后，发生崩溃。已经按照QA文档安装GStreamer 以及环境变量。请问该如何排查？ 是否对GStreamer的版本有要求

**Comment by endink** [comment]
看起来是和 GS有关，我开发链接的 GS 是1.22， 也有可能是版本兼容问题，一般来不应该，动态库调用只要头文件API不变都可以通过，你可以考虑降级一下版本，另外是蓝图调用吗

**Comment by buaaCCJ** [comment]
> 看起来是和 GS有关，我开发链接的 GS 是1.22， 也有可能是版本兼容问题，一般来不应该，动态库调用只要头文件API不变都可以通过，你可以考虑降级一下版本，另外是蓝图调用吗

您好，感谢回复。已经修复，我安装了GStreamer 1.24.9 以及其下面所有的套件，不仅仅是libav，然后可以正常运行了
