### ISSUE TITLE
关于使用自定义骨骼后，动画蓝图父类继承函数报错和无法初始化骨头修改的问题

### ISSUE THREAD

**Issue by Gobcurry** [endink/Mediapipe4u-plugin#2]
问题：我用我的动画蓝图重设父类为MediaPipeAnimInstance，但输出日志还是打印：LogMediaPipe:错误:PoseSolver为null点，FAnimNode_MediaPipePose只能在MediaPipeAnimInstance中使用。并且报警告：Unable to initialize bones to modify,  hands solver was not initialized。
![微信截图_20221118104127](https://user-images.githubusercontent.com/117976370/202604561-dee5d291-5c99-4c03-87f3-bd5aab578db2.png)
![微信截图_20221118104257](https://user-images.githubusercontent.com/117976370/202604835-8d9288d6-6891-43e4-b027-c60b8e7543ab.png)
![微信截图_20221118104306](https://user-images.githubusercontent.com/117976370/202604837-cab660ff-c61f-40ec-806d-b42b437336b7.png)
![微信截图_20221118104315](https://user-images.githubusercontent.com/117976370/202604839-93ce6c64-a8e2-445d-98a8-54d4ad625973.png)
![微信截图_20221118104328](https://user-images.githubusercontent.com/117976370/202604840-44b19a20-554a-4a89-884c-83ae1e2f9879.png)

我的BonePreset用的自定义骨骼，也在Bone Setting匹配好了骨骼链，然后日志就报错。

**Comment by endink** [comment]
Get, 我复现了修复一下

**Comment by endink** [comment]
@Gobcurry 问题已在最新8你发布的版本中修复，关闭issue 了
