### ISSUE TITLE
1. Regarding the MediaPipe error, post the log file at here when an error occurs, which is usually in the saved/logs folder so that I can find out what the problem is.

### ISSUE THREAD

**Issue by sameekue5** [endink/Mediapipe4u-plugin#21]
1. Regarding the MediaPipe error, post the log file at here when an error occurs, which is usually in the saved/logs folder so that I can find out what the problem is.

2. Network, I don't think multiplayer animation has much to do with MediaPipe4U, it should be a server streaming animation data and client-side display problem, I believe UnrealEngine has the example of that. You can find UE document or market to get the sample.

3. Important note about the MediaPipeAminInstance (your animation blueprint). At the same time in the world outline you must make sure it has only one MediaPipeAminInstance , If you want to sync animation to many actors, you can use IK Reatarget to anothers. Because the landmarks data of mediapipe that made by MediaPipeHolisticComponent can be deal one time, multiple consumers (MediaPipeAminInstance ) will be get a low animation frame rate (Multiple  MediaPipeAminInstance  will be competition for data).
> BTW: sorry for my bad English , this is a question of the structure of the program, which is difficult to explain in a short answer.

_Originally posted by @endink in https://github.com/endink/Mediapipe4u-plugin/issues/20#issuecomment-1419021900_

**Comment by sameekue5** [comment]
Hey Anders, this is Sameek , and I am working with Giovanni on this project. As you requested , here is the saved log file for the error which is occuring when I am switching the number of players to more than 1 in the editor, for multiplayer testing.

I dont understand what you meant on the second point, because all the other animations are working for the player at both client and server. Only the Mediapipe Solver nodes that we have setup in the animation Blueprints, are controlling all the players together instead of just the client player.

Also , we are not looking for syncing animations. Our use case is pretty simple, the mediapipe solvers should move only the local player , that is obvious right ? Because if I am waving my hand, I only want my player to wave its hand, and not the server player. And also if I am waving my hand, the other players shall also see my hand movement, currently if the opponent players are waving their hands, I am not able to view it.

**Comment by endink** [comment]
Yeap, the mediapipe solvers should be run in the local only, so  second point I mean is MediaPipe4U does not care about the network, if there is a bug in the local run, don't worry, post the log file, I will fix it asap.

**Comment by sameekue5** [comment]
You are not answering the question directly. I know it should be run in the local, I am asking that why it is controlling both the local and the server characters ?

**Comment by endink** [comment]
There's no code controlling the server character, it's just a plain Animation Blueprint. I'm confused, if your question is #20, I will close this issue.

**Comment by endink** [comment]
duplex #20
