### ISSUE TITLE
脸部不能驱动

### ISSUE THREAD

**Issue by liuguangliang** [endink/Mediapipe4u-plugin#23]
你好，我下载了工程和插件，将他们整合在了一起，但是脸部的表情没有驱动，请问是什么原因。

**Comment by endink** [comment]
你使用什么表情驱动呢？如果 NvAR 请仔细阅读文档是否满足硬件和软件要求，同时检查日志是否发生警告或报错

**Comment by liuguangliang** [comment]
“你使用什么表情驱动呢？” 不是太理解什么意思。  我就是把你的项目下载了，插件下载了，然后场景中的机器人就可以动了，但是小男孩的脸部不能做表情。是不是还要做什么设置。

**Comment by endink** [comment]
请阅读文档，NVAR 部分，需要安装nvidia sdk

**Comment by endink** [comment]
这是开发用的插件，不是打包好的软件，必须要阅读文档，谢谢

**Comment by liuguangliang** [comment]
谢谢，我学习一下

**Comment by liuguangliang** [comment]
5.“独立使用 NvAR 表情捕捉”“暂缺文档” 。请问有这一部分的文档吗，我实在是没办法让小男孩脸部动起来。

**Comment by endink** [comment]
安装完 Nvidia AR SDK 直接运行不会动吗？独立运行比较复杂，没写文档，独立使用的意思就是不和 MediaPipe4U 动补集成使用。
1. 检查 NvAR component 上的 开关 IsDisabled 是否被勾选
2. 显卡是否是 N 卡
3. 显卡是否满足驱动要求的版本   

如果不会动检查日志，发现相关错误或者警告可以贴出来我看一下，

**Comment by endink** [comment]
另外你使用 Demo 里 maps/NvAR 这个 Level 运行吗，这个是配置好直接可以运行的，安装完 SDK 后可能需要重启一下编辑器

**Comment by liuguangliang** [comment]
再次谢谢大佬，我的显卡是3060的，第一次下载了一个2060的sdk。

**Comment by endink** [comment]
solved !
