### ISSUE TITLE
Attach video source to MediaPipe4U

### ISSUE THREAD

**Issue by sautechgroup** [endink/Mediapipe4u-plugin#24]
Hello,
Congratulations for this amazing plugin.
I'm testing your demo.
I want to know if it's possible to attach a video source (from a StreamMedia component or a MediaPlayer component) like a mp4 video or something else (without using virtual camera like OBS studio) instead of the webcam source.
I read the documentation and seems not be present something correlated.
Thank you.
Regards.

**Comment by endink** [comment]
Of course you can, from mp4 file capture has always been supported, it may be that the Google Translate documentation has confused you, please refer to this document, which has the usage of video capture.

 https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/usage/start_mocap.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by endink** [comment]
BTW：Video capture is built on Gstreamer （A very popular open source project）, because UE's decoder isn't good enough, and you'll also need to read the Gstreamer content in the mediapie4u doc.

**Comment by sautechgroup** [comment]
Thank you for the clarification.
Have a nice day
