### ISSUE TITLE
读取 .MP4出错

### ISSUE THREAD

**Issue by liuguangliang** [endink/Mediapipe4u-plugin#25]
运行程序的时候报 LogGStreamer: Error: GStreamer module is not available

执行到 蓝图Start函数时报 LogMediaPipeGStreamer: Error: GStreamer start fault !
filesrc location="C:/Users/xiaofan/Desktop/wiper.mp4" ! decodebin ! videoconvert ! video/x-raw,format=(string)RGBA ! videoconvert ! appsink name=mediapipe_sink

**Comment by endink** [comment]
read doc about gstreamer please !
