### ISSUE TITLE
UE 5.1 compilation

### ISSUE THREAD

**Issue by Eldoran** [endink/Mediapipe4u-plugin#26]
Hey there, thanks for the amazing job here! I wonder if you have plans to release a UE5.1.1 version, so...
Would it be possible to release a compiled version with the current UE5.1.1? Thanks in advance!

**Comment by endink** [comment]
I'm working on this,  when upgrading to UE 5.1.1, all the code works fine, but the Nvidia AR SDK is not working, I'm post an issue to Nvidia, but they haven't responded to me yet, I decided to wait a few more days, if there is no response, I may temporarily release a 5.1.1 version without NvAR

**Comment by Eldoran** [comment]
Thanks for the quick response. I had some issues too with nvidia dlss when 5.1.1 was released and they released a new version in few days, so I hope they fix that too soon. If you release a 5.1.1 version would be great to start testing and see how it works. Thanks!

**Comment by endink** [comment]
If anyone cares about this, they can join me in urging nvidia to respond：

https://forums.developer.nvidia.com/t/always-return-nvcv-err-missinginput-when-run-face-expression/244449

**Comment by endink** [comment]
UE5.1 is fully supported now.
