### ISSUE TITLE
Build Error at visual studio

### ISSUE THREAD

**Issue by 2022is** [endink/Mediapipe4u-plugin#27]
hi , i was unable to build the project at visual studio , i'm so sorry since i'm new to this field , i cant even find a suitable tutorial to export log activity from visual studio , all the tutorial are using the tools which i dont have in my computer
嗨，我无法在 visual studio 上build Ue5和mediapipe4u，我很抱歉，因为我是电脑白痴，我找不到合适的教程来从 visual studio 导出日志活动，我的电脑里没有教程所使用的工具

![Capture](https://user-images.githubusercontent.com/106756932/222960793-6cbcd724-8613-43eb-b28d-d18e566b0ef2.PNG)
[Output-Build.txt](https://github.com/endink/Mediapipe4u-plugin/files/10891824/Output-Build.txt)

**Comment by endink** [comment]
请查看demo 工程readme 清理工程后编译，插件只适合UE熟练的开发

**Comment by 2022is** [comment]
好的，谢谢你噢！
