### ISSUE TITLE
UE5.0版本,将Metahuman修改成自定义动捕重定向资源并绑定动补动画蓝图后,UE5报错

### ISSUE THREAD

**Issue by h616311501** [endink/Mediapipe4u-plugin#28]
以下是报错内容
Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:E:\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\Containers\Array.h] [Line: 691] Array index out of bounds: 350 from an array of size 342

UnrealEditor_MediaPipe!UMediaPipeUtils::BuildBoneIndices() [F:\3D_Works\UE\MediaPipe4U\Build\MediaPipe4U\HostProject\Plugins\MediaPipe4U\Source\MediaPipe\Private\MediaPipeUtils.cpp:1048]
UnrealEditor_MediaPipe!UMediaPipeUtils::GetAllBonesInComponentSpace() [F:\3D_Works\UE\MediaPipe4U\Build\MediaPipe4U\HostProject\Plugins\MediaPipe4U\Source\MediaPipe\Private\MediaPipeUtils.cpp:1100]
UnrealEditor_MediaPipeBVH!AMediaPipeBVHRecorder::OnAddOn() [F:\3D_Works\UE\MediaPipe4U\Build\MediaPipe4UBVH\HostProject\Plugins\MediaPipe4UBVH\Source\MediaPipeBVH\Private\MediaPipeBVHRecorder.cpp:486]
UnrealEditor_MediaPipe!UMediaPipeAnimInstance::ReInitialize() [F:\3D_Works\UE\MediaPipe4U\Build\MediaPipe4U\HostProject\Plugins\MediaPipe4U\Source\MediaPipe\Private\MediaPipeAnimInstance.cpp:209]
UnrealEditor_MediaPipe!UMediaPipeAnimInstance::NativeBeginPlay() [F:\3D_Works\UE\MediaPipe4U\Build\MediaPipe4U\HostProject\Plugins\MediaPipe4U\Source\MediaPipe\Private\MediaPipeAnimInstance.cpp:258]
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by endink** [comment]
请暂时移除 MEDIAPIPE4U bvh插件，看起来导出动画存在BUG

**Comment by endink** [comment]
问题无法复现，肉眼检查到可能存在的BUG，可以下载新版本最新版本检查是否问题被修复
