### ISSUE TITLE
UE 5.11 from SourceCode packge failed

### ISSUE THREAD

**Issue by RookieInsect** [endink/Mediapipe4u-plugin#29]
Error message：
Missing precompiled manifest for 'MediaPipe', 'E:\MediaPipe4U-Demo\Intermediate\Build\Win64\MediaPipe4U_Demo\Shipping\MediaPipe\MediaPipe.precompiled'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in MediaPipe.build.cs to override. If part of a plugin, also check if its 'Type' is correct.
UATHelper: 打包 (Windows):
I did every step of source code packaging, except”执行完成后将把链接符号拷贝道你的项目 Build 目录。“Can I ask what's going on？

**Comment by RookieInsect** [comment]
my unreal engine compiled from source code.
 Project.Target.cs add code :LinkType = TargetLinkType.Default;

**Comment by endink** [comment]
Please read doc, UE form source code is diffrent with from launcher, you need copy cpp link file, I wrote a script do this, its in the document.

**Comment by endink** [comment]
If bat is run succeed, the link files were copied. Afger that, just package your project

**Comment by endink** [comment]
Try change project target.cs, add line:

bPrecomplie = true;   

If not worked, forget this plugin, so sorry! 

Compiling unreal engine from source code, you need to be very familiar with the UE compilation process, it's hard to go into detail here and say ckearly by a few words, many times you need to check the problem yourself, if you are not familiar with c++ compilation, it will waste a lot of time, I recommend you stop use this plugin, it doesn't do much testing against the source engine and may run into other issue, sorry again.

**Comment by RookieInsect** [comment]
I fix it！
your project name is MediaPipe4U-Demo，but project module name is MediaPipe4U_Demo.

**Comment by endink** [comment]
Thanks let me know this! 😜
