### ISSUE TITLE
[Bug]:关闭ue引擎，下载新的license文件并覆盖原文件后，重新打开并允许，动补失效，查看许可证仍然显示3.15到期。请教一下是哪里出了问题。

### ISSUE THREAD

**Issue by JKJ526523** [endink/Mediapipe4u-plugin#32]
### MediaPipe4U 版本

20230309

### UnrealEngine 版本

5.0.x

### UnrealEngine 类型

Launcher

### 问题类型

插件安装

### 错误详细描述

关闭ue引擎，下载新的license文件并覆盖原文件后，重新打开并运行，动补失效（点击start web camera没有相应），查看许可证仍然显示3.15到期。请教一下是哪里出了问题。

**Comment by endink** [comment]
许可证文件过期了，新的许可证文件在 5.1 版本（230311）插件里有，下载 5.1 插件，拿出里面的许可证文件覆盖到你的插件里，晚点我会上传一个
