### ISSUE TITLE
更新脚掌贴地版本后，摄像头动捕正常，视频动捕无响应，rider报错如下，请大佬指教。

### ISSUE THREAD

**Issue by JKJ526523** [endink/Mediapipe4u-plugin#35]
### MediaPipe4U Version

20230316

### UE Version

5.0.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

Warning      LogGStreamer              GstPipeline <MediaPipe_GS_Pipline> BUS WARNING: NO_ERROR_MESSAGE
Error        LogGStreamer              GstPipeline <MediaPipe_GS_Pipline> BUS ERROR: Internal data stream error.

**Comment by endink** [comment]
有可能是 GStreamer 代码问题，找到 MediaPipeHolisticComponent 组件，将 SourceResolutionLimits 属性暂时设置未 None

**Comment by JKJ526523** [comment]
问题解决了，多谢。（感谢这么优秀的项目）

**Comment by JKJ526523** [comment]
![image](https://user-images.githubusercontent.com/112796858/226276130-8fa7f1f3-60dd-4667-b9ab-1fd8d2eb2358.png)
请问我设置完碰撞通道之后，效果是这样的，请问是哪里出了问题

**Comment by endink** [comment]
我没看懂你的问题，请开启新 issue 描述问题，不要在已经关闭的issue 上提问，谢谢
