### ISSUE TITLE
更新脚掌贴地功能后，出现异常[Bug]:

### ISSUE THREAD

**Issue by JKJ526523** [endink/Mediapipe4u-plugin#36]
### MediaPipe4U 版本

20230316

### UnrealEngine 版本

5.0.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

设置如下：
![image](https://user-images.githubusercontent.com/112796858/226505036-6da6ecbd-8788-45c3-8990-100f5081b9c2.png)
![image](https://user-images.githubusercontent.com/112796858/226505202-66ba1678-a93d-4251-908d-f23572f866ee.png)
效果如下（出现高亮部分并且离地更远）：
![image](https://user-images.githubusercontent.com/112796858/226505321-2ff11995-ba23-4d60-ae1d-76c336b5d744.png)

**Comment by endink** [comment]
1. 如果高亮指的是脚部的线框，这是 DebugDraw，你可以通过 AnimaInstance(动画蓝图) 上的属性 DebugDraw 开启或关闭，它主要用于调试。线框种的黄点代表射线碰撞点。
2. 脚没有贴地是射线碰撞点不对，从图中我猜测这是因为你的角色胶囊体和射线发生了碰撞，射线碰撞通道必须忽略所有的的碰撞体，除了地面（Demo 工程地面为 Panel），需要非常熟悉物理碰撞相关知识，你才明白我在说什么

**Comment by endink** [comment]
或者是因为你的地板也没有发生碰撞，确保地板的射线通道是 block

**Comment by JKJ526523** [comment]
![image](https://user-images.githubusercontent.com/112796858/226851316-32028af4-6fef-479e-b107-2080b6211549.png)
GroundIK这个碰撞通道默认是忽略，只单独设置了地板的射线通道为block。
![image](https://user-images.githubusercontent.com/112796858/226851789-49600df7-d401-4439-9e4b-3843f60aecda.png)

**Comment by endink** [comment]
> ![image](https://user-images.githubusercontent.com/112796858/226851316-32028af4-6fef-479e-b107-2080b6211549.png)
> GroundIK这个碰撞通道默认是忽略，只单独设置了地板的射线通道为block。
> ![image](https://user-images.githubusercontent.com/112796858/226851789-49600df7-d401-4439-9e4b-3843f60aecda.png)
> 

你需要检查动画蓝图中的Location solver节点细节面板中的碰撞通道属性是否使用了这个通道

**Comment by JKJ526523** [comment]
![image](https://user-images.githubusercontent.com/112796858/227080607-5a08c68f-a993-4332-aeff-4b6dc745a59a.png)
碰撞通道属性使用了GroundIK这个通道

**Comment by endink** [comment]
检查 Animation Instance 上的 Solve Location 属性是否被勾选，必须开启位移算解才会进行 Ground IK 计算

**Comment by JKJ526523** [comment]
![image](https://user-images.githubusercontent.com/112796858/227452851-be2df127-d069-42f2-9dd3-3e911d84a8e3.png)
Solve Location 属性也已经勾选。
Location solver节点细节面板中的碰撞通道属性启用了GroundIK；GroundIK碰撞通道默认是忽略，只单独设置地板的射线通道为block；并且Solve Location 属性也已经勾选。比较疑惑问题是出在哪里了。

**Comment by endink** [comment]
或者是因为你的地板也没有发生碰撞，确保地板的射线通道是 block

**Comment by endink** [comment]
从你的调试视图看到的是射线没有和地面发生碰撞，检查地面的碰撞体

**Comment by endink** [comment]
红色是射线击穿了，没有和地板碰撞，补了文档，清楚了的写了怎么看调试线条，需要你自己找到为什么会击穿
