### ISSUE TITLE
[Request]: Is it possible to use a live streaming source instead of webcam?

### ISSUE THREAD

**Issue by sautechgroup** [endink/Mediapipe4u-plugin#37]
### MediaPipe4U Version

2022.0.1

### UE Version

5.0.x

### UnrealEngine Type

Compiled From Source Code

### What happened?

Hello everyone,
We have an rtmp stream from a remote pc and we are able to play this stream in a media player by attaching it to a stream media source.
We would to know if it is possible to give in input this stream media source to MediaPipe4U instead of the webcam or some video file.
We read the documentation and seems to be possible by blueprint only with a video file.
Thank you in advance.
Regards.

**Comment by endink** [comment]
It is not support now. But if you can write C++ code, I can tell you how to do it. It is easy.

**Comment by endink** [comment]
sorry again, i will write doc for this asap.

**Comment by endink** [comment]
Sorry, you cant. MediaPlayer can't decode some video formats well,even decoding MP4 will get an error sometimes. GStreamer is the perfect replacement (NVIDIA also uses Gstreamer for video AI, so it's definitely a trustworthy project).   

If you need RTMP stream right now, you'll have to do it yourself, and I'm marking this issue as an "enhancement",  so if I have the time, I might use GStreamer to implement RTMP, in fact, everything Media Player can do easily with Gstreamer.

**Comment by endink** [comment]
BTW, push stream

> Alright, first of all, I have to apologize for the lack of documentation in this section.
> 
> You need implement a "ImageSourceComponent" by your self. Although this sounds very complicated because of the design to flow and multithreading， but most of the work in this implementation has already been done by the plugin.
> 
> 1. Write a a "Component " that inherits from UMediaPipeImageSourceComponent.
> 2. Override function IsSupportHorizontalFlip, IsSupportLimitResolution (return false is OK).
> 3. In your "Component"  tick event, read a image and push to "Stream".
> 
> How to push image:
> 
> 1. Invoke PrepareTexturePool function to tell MediaPipe4U image size and format.
> 2. Invoke Stream().Push method
> 
> A simple example code:
> 
> ```c++
> auto* self  = this;
> Streaming()->PushFrame([self](MediaPipeTexture* PooledTexture)
> {
>   .... // set PooledTexture data
> 
>   self->NotifyTexture2DCreated(PooledTexture);
>   return true;
> });
> ```
> 
> How to read image to MediapipeTexture?
> 
> it has some help function:
> 
> * bool AdoptCvMat(void* SrcMat);
> * bool CopyFromCvMat(void* SrcMat);
> * bool CopyFromData(void* InData, SIZE_T DataSize);
> * bool CopyFromImage(IImageWrapper* InImage, int32 BitDepth = 8);
> 
> > CvMat means an opencv mat class (cv::Mat)
> > InData means an uint8 array, DataSize means array length
> > Adopt means zero copy, but now, only cv::Mat can "zero copy"
> 
> you can use CopyFromData, read unit8 array from MediaTexutre, and copy the array to MediaPipeTexture

BTW, the "PushFrame" function has an overload that supports pushing a media texture directly, but I haven't tested it carefully, and maybe it will help you get uint8 arrays from a MediaTexture (for MediaPlayer output)

**Comment by sautechgroup** [comment]
Hello, I'm trying to use CopyFromData function, but I don't know how to pass the MediaTexture object as an uint8 array.
Is there any conversion I need to make?
Thank you.

**Comment by endink** [comment]
After CopyFromData, you dont need to do anything.

**Comment by sautechgroup** [comment]
> you can use CopyFromData, read unit8 array from MediaTexutre, and copy the array to MediaPipeTexture
How can I read MediaTexture as an uint8 array?

**Comment by endink** [comment]
从你的调试视图看到的是射线没有和地面发生碰撞，检查地面的碰撞体

**Comment by sautechgroup** [comment]
If I understood well, self->NotifyTexture2DCreated(PooledTexture) fires the VideoTextureCreated event.
How can i call this function if I use the PushFrame function that takes in input directly a MediaTexture?
I googled for making an uint8 array from a MediaTexture, but the only way I found to make an array is the ReadPixels function that creates a TArray<Fcolor>
Thank you for the support.

**Comment by endink** [comment]
Oops... Sorry, PushFrame use a mediaptexture cant notify,Its my fault, I forgot that in my code, You are right, NotifyTexture2D is the key for your rendering.


Fcolor is 4 bytes, the order is related to the image format. In fact, it is easy to convert them, it seems that you are not familiar with the knowledge of pixels, I will give you the code directly later.

**Comment by endink** [comment]
@sautechgroup 

```cpp
UMediaTexture* Texture = XXXX....
MediaPipeTexture* MediaPipeTexture = XXXX..

TArray<FColor> colors;
FMediaTextureResource* TexResource = static_cast<FMediaTextureResource*>(Texture->GetResource());
TexResource->ReadPixels(colors);
MediaPipeTexture->Width = Texture->GetWidth();
MediaPipeTexture->Height = Texture->GetHeight();
//mediaptexture is RGBA8
MediaPipeTexture->Format = MediaPipeImageFormat::SRGB;
MediaPipeTexture->CopyFromData(colors.GetData(), colors.Num()*4);
return true;
```

Because FColor is order B->G->R->A, so its rgba8 format, you juse use GetData it will be return a memory array, its not only a FColor array for struct, but also a unit8 array in memory.

But, its a little problem:

The data of the media texture resides on the GPU. To modify/access it on the CPU,  you must lock the bits. I haven't looked into mediatexture carefully, so I can't tell you the specific steps and how to lock mediatexture , the above code is for reference only.
   
It is worth mentioning, **copy memory from gpu to cpu is slow and not recommended**.

If you're new to RHI and image technology, I still don't recommend manually working with pixels.

**Comment by sautechgroup** [comment]
Hello,
thank you for the support, yes I'm new to c++ programming on Unreal Engine (I usually don't use c++).
I'll try and let you know.
Thank you and have a nice day

**Comment by endink** [comment]
If you are interested in extending M4U with C++, I recommend you read here to help understand the design behind M4U：


https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/extensions/image_consumer.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by endink** [comment]
emmm, NotifyTextureCreated will auto convert MediaPipeTexture to Texture2D, if you dont need M4U TextureCreatedEvent, you can ignore this and draw texture to your UI by yourself.

**Comment by sautechgroup** [comment]
Ok I'm trying to use directly the UTexture2D object and use the PushStream override method. My last chance :D
I found a function called StartLoopThread that I saw in webcam logs that is called before starting the webcam.
I tried to call it in my function (once not at every tick) and I have this log:
[2023.03.30-16.16.01:109][507]LogMediaPipe: Display: ImageSourceLoop  Start! ThreadID = 32664
[2023.03.30-16.16.01:110][507]LogMediaPipe: Display: ImageSourceLoop thread enter.
[2023.03.30-16.16.01:110][507]LogMediaPipe: Display: Handle loop break.
[2023.03.30-16.16.01:110][507]LogMediaPipe: Display: ImageSourceLoop thread exit.

I saw that this call let me see the first frame into the VideoImage object into the widget and fires the VideoTextureCreated event in blueprint. But I don't know why it breaks.
Any suggestions?
Thank you for the support and sorry for lack of knowledge in this technology.

**Comment by endink** [comment]
If your image source is an infinite loop call, then a separate thread may be required to execute it, you can see some function that the named "Loop" are for this, if you use tick, then the loop thread is not needed. The implemention for webcam Probably like this：

```cpp
while(runFlag)
{
   ReadFrame... 
   PushFrame... 
}
```

So it use startLoop, onLoop and these functions simplify creating a thread to execute this loop, you can also write your own, there is nothing mysterious about them.

**Comment by endink** [comment]
Do you have a rtmp address for testing? I can write a GStreamer implemention.

**Comment by sautechgroup** [comment]
Hello, sorry for the late answer, jet lag problems..
No I don't have an rtmp stream, but if you use SRS (Simple Realtime Server) and install docker with this giude: https://ossrs.io/lts/en-us/docs/v4/doc/getting-started

You can use rtc2rtmp configuration: https://ossrs.io/lts/en-us/docs/v4/doc/webrtc#rtc-to-rtmp
and see your webcam by "Publish by WebRTC" link provided (that is localhost).
Finally you can see your webcam with rtmp://localhost/live/show.
Thank you.

**Comment by endink** [comment]
Alright, I have used SRS and it is a Chinese project  : )

**Comment by sautechgroup** [comment]
If you used SRS it also uses WebRTC. I choosed RTMP conversion because it's easily streammable into a UMediaPlayer object, but I know that GStreamer also supports WebRTC.
So it does not matter for me if it uses RTMP or WebRTC, indeed it would be better use WebRTC.
Thank you and have a nice day.

**Comment by endink** [comment]
WebRTC is hard to implement，It's not a question about the code, it's about webrtc spec.    

The WebRTC specification does not specify how the signalling server needs to be implemented. It is perfectly valid to exchange the SDP and ICE candidates via email for example.   

Unless I'm binding a signalling server implementation, or reserving an interface to be implemented by the user himself, it doesn't seem like a UE plugin's job anyway.

BTW：I have done "URI image" support, not only rtmp, but also RTSP, M3U8, etc., as long as the network protocols supported by GStreamer can be used as "image source" , which will be released with the next M4U version.

**Comment by sautechgroup** [comment]
Hello, I'm really thankful about this.
Thank you and have a nice day.

**Comment by endink** [comment]
Although the issue was closed, I just mark it, the latest version of the plugin already supports MediaPlayer as an image source:     
   
[Document is here](https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/mocap/features/image_source.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp)
