### ISSUE TITLE
[Bug]:表情捕捉开启后有报错，无法使用

### ISSUE THREAD

**Issue by Maoshanhui** [endink/Mediapipe4u-plugin#38]
### MediaPipe4U 版本

20230316

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

源码编译

### 问题类型

运行错误

### 错误详细描述

打开样例工程的NvAR_WithMediaPipe后，运行。

在开始游戏后的几秒内，pose动捕生效。然后会报错卡住。

报错如下：

Display      LogMediaPipe              [MediaPipe API] ------------> Start Loop Work Thread <------------
Display      LogMediaPipe              ImageSourceLoop  Start! ThreadID = 43820
Display      LogMediaPipe              Webcam opened, capture resolution :1280x720 @ 30.0 fps
Display      LogMediaPipe              ImageSourceLoop thread enter.
Log          Live Link                 (01) Can't evaluate frame for 'MediaPipe NvAR'. No data was available.
Error        LogMediaPipeNvAR          [NvAR API] The given parameter selector is not valid in this effect filter ( code: NVCV_ERR_SELECTOR, op: NvAR_SetU32(PoseMode))
Display      LogMediaPipeNvAR          NVAR Thread Start! ThreadID = 42780
Display      LogMediaPipe              [MediaPipe API] UmpPipeline::AddImageFrameIntoStream (in loop) OK.
Display      LogMediaPipe              [MediaPipe API] Notify image size received ( w: 1280, h: 720 ).
Display      LogMediaPipe              [MediaPipe API] First look workflow is done !
Display      LogMediaPipe              FDynamicTexture::Resize Width=1280 Height=720 Format=PF_B8G8R8A8
Display      LogMediaPipe              Bones for mediapipe  joint  cached.
Display      LogMediaPipe              Joints calibrated completed.

**Comment by endink** [comment]
无法复现问题，mediapipe4u livelink 已经更新到全新的设计，或许可以尝试
