### ISSUE TITLE
will you make it open source?

### ISSUE THREAD

**Issue by seastar105** [endink/Mediapipe4u-plugin#4]
hi i'm trying to puppeteering avatar using mediapipe in unity. but it's quite hard.

will you opensource this awesome project later?
or could you elaborate how did you get local rotation from mediapipe pose landmark?? it's too hard for implementing hands and pose ik solver...

**Comment by endink** [comment]
Hi,

Sorry, There is no plan to open source currently, you need to use matrix calculations, find yaw/pitch/roll for each joint, which is not something that can be clearly said in a few words, it is geometric mathematics,

Anders Xiao

发件人: HAESUNG ***@***.***>
发送时间: 2022年11月27日 21:55
收件人: ***@***.***>
抄送: ***@***.***>
主题: [endink/Mediapipe4u-plugin] will you make it open source? (Issue #4)


hi i'm trying to puppeteering avatar using mediapipe in unity. but it's quite hard.

will you opensource this awesome project later?
or could you elaborate how did you get local rotation from mediapipe pose landmark?? it's too hard for implementing hands and pose ik solver...

―

**Comment by seastar105** [comment]
@endink Wow, thanks for fast replying. I have some more detailed question. if you don't mind. could you answer on these questions? I have no one to ask questions like this.

1. How did you calculate position of pelvis, hip(usually root of bones)? as far as i know, there's no such position in mediapipe's landmark.
2. how did you lock foot on ground in game scene? currently, i just control position of avatar by using hip's position according to image scale. 
3. could you explain how did you calculate wrist's rotation? of course, there's some explanataion of landmarks from pose graph in mediapipe's blog. (15, 16 is wrist, 17, 18 is pinky, 19, 20 is index, 21, 22 is thumb). I tried to calculate wrist's rotation by calculating normal vector of plane, which contains wrist-pinky, pinky-index, index-pinky. but it totally not works..

**Comment by endink** [comment]
This is an extraneous topic, so close it
