### ISSUE TITLE
插件在手部抬起时偶尔会发生手部扭曲的情况,有办法可以限制骨骼旋转吗?

### ISSUE THREAD

**Issue by h616311501** [endink/Mediapipe4u-plugin#40]
![image](https://user-images.githubusercontent.com/39427850/228167351-f0b3411a-df2e-4740-b17f-0c3d8dd96e96.png)
我是在Take Recorder录制动画的时候出现的这个问题.

**Comment by endink** [comment]
事实上，如果你精通 ControlRig 或者 IK，你可以在后期处理任何问题，这个扭曲看起来是 UE 默认的后期动画蓝图进行了扭曲矫正，你可以使用插件的扭曲矫正来转动一点前臂或者直接修改后期动画蓝图里的数值，UE 的扭曲矫正用的矫正骨骼，这是最佳做法，插件会用前臂矫正手腕。关于插件中的扭曲矫正，可以参考文档。
