### ISSUE TITLE
mp4 video error

### ISSUE THREAD

**Issue by RCHerizo** [endink/Mediapipe4u-plugin#43]
I have a problem when I choose a video to be played, nothing happened no video being displayed, I tried to convert the video using h.264 codec but It didn't change anything, I think It's related to "gstreamer". However images work fine, here is the log i copied in the unreal engine editor. Errors that is displayed in red is : 

LogMediaPipeGStreamer: Error: GStreamer start fault !
filesrc location="D:/Videos/camjennie.mp4" typefind=true ! decodebin ! videoscale2  width=1280 height=720 ! videoconvert ! video/x-raw,format=(string)RGBA ! appsink name=mediapipe_sink

[log.txt](https://github.com/endink/Mediapipe4u-plugin/files/11100887/log.txt)

**Comment by endink** [comment]
Sorry ,this is an known bug in this version.
Please find your **MediaPipeHolisticComponent**,  and set **SourceResolutionLimits ** to None

> I will fix that in next release.

**Comment by RCHerizo** [comment]
ok, thank you for your help

**Comment by RCHerizo** [comment]
I tried your solution but it's not working yet : ![Pictures](https://user-images.githubusercontent.com/29947895/228569484-526e4b96-0700-49c2-8b2e-241f5c01d502.PNG)

Here is the video file I use in my test if it can help : 
https://user-images.githubusercontent.com/29947895/228570508-4b97d3f3-594a-4593-a61e-bcf649ef4c30.mp4

**Comment by endink** [comment]
You are welcome 😄 

"SourceResolutionLimits" is for imporve performace. Limiting the resolution can increase the FPS of the solver by about 2~5.

Unfortunately, it has a bug for some videos, and I'll fix it in the next release.
