### ISSUE TITLE
运行时动捕没有响应

### ISSUE THREAD

**Issue by qq1044083166** [endink/Mediapipe4u-plugin#46]
### MediaPipe4U 版本

2023-04-03

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

[Log.txt](https://github.com/endink/Mediapipe4u-plugin/files/11182373/Log.txt)
自建Actor只包含MediaPipeHolistic，并在事件开始时Start Camera，拖入场景，运行后角色无法响应动捕。
使用Demo项目中的BP_MediaPipeRuntime拖入场景，角色可以正常响应

**Comment by endink** [comment]
看日志是摄像头传递的编号不正确，ListWebcams 打印一下设备列表，找到你的摄像头正确的编号

**Comment by qq1044083166** [comment]
刚刚做了一个摄像头的选项控件，通过选择摄像头后按按钮开启Start Camera的方式，终于可以正常响应动捕了，这个时候我打印了一下摄像头编号是0。 
目前，在BeginPlay直接Start Camera 编号为0的方式就会动捕失效，不知道是BUG还是说明

**Comment by endink** [comment]
无法复现，暂时 marker ， 这或许是由于多个组件之间 BeginPlay 函数顺序不确定导致，是我做了一个错误的演示
