### ISSUE TITLE
关于UE5.1打包出现的一些问题

### ISSUE THREAD

**Issue by Gobcurry** [endink/Mediapipe4u-plugin#48]
### MediaPipe4U 版本

20230409

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

项目打包

### 错误详细描述

大佬，又见面了，插件真的太棒了。
但我在打包时出现了一些问题，没有爆红，但最后打包失败了，我已经排除了插件以外的问题，无插件版本可以打包。
首先，我的系统是Win10，64位系统，
我按照您的更新文档中步骤，确认启用插件，LinkType也设置为了Default，创建了 copy_intermediate.bat并填好内容，并运行完毕，项目名称也改好了，但最后一部我不太理解，拷贝链接符号到Build目录这一步。
有两个问题，我的Build目录是指哪里，还有就是链接符号是指copy_intermediate.bat 这个文件吗？
还有个问题，源码版引擎是指在epic下载了源代码的引擎吗，不太了解。

希望您有时间可以给我个反馈。

**Comment by endink** [comment]
你填写的是 launcher 版引擎，为什么你要用源码版的打包方式，launcher和普通项目一样打包就可以，没有这么多麻烦事

**Comment by Gobcurry** [comment]
大佬，我按Launcher版引擎打包还是有问题，然后我把mediapipe4U所有相关插件都迁出后可以打包成功，打包的版本是Development 和 Shipping都试过了，烘焙项目没问题，打包就是失败。然后还有个问题，demo我下载后把插件放到Plugins文件夹后，生成sln文件的时候，也会报错。
![微信截图_20230411115204](https://user-images.githubusercontent.com/117976370/231051717-29669139-949b-42c1-8a3a-f7c6f5ec3753.png)

**Comment by Gobcurry** [comment]
我的工程中除了使用Mediapipe4U之外，还在使用KawaiiPhysics插件，是否是不兼容的问题

**Comment by endink** [comment]
发版都测试过 demo 工程可以打包并成功运行，如果 DEMO 打包失败也需要贴出打包日志文件才能发现问题，自己的项目打包失败，原因非常多，需要自己排查问题，我无法支持到每个项目打包，插件几乎不会和任何插件产生冲突，除非其他插件适用了非UE 内置的 OpenCV，我将关闭问题，精力有限，实在抱歉

**Comment by Gobcurry** [comment]
大佬，我找到问题了，UE5.1不能用VS2019编译，我下了VS2022和Rider2023.1问题就解决了




Gobcurry
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "endink/Mediapipe4u-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 中午12:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [endink/Mediapipe4u-plugin] 关于UE5.1打包出现的一些问题 (Issue #48)





 
发版都测试过 demo 工程可以打包并成功运行，如果 DEMO 打包失败也需要贴出打包日志文件才能发现问题，自己的项目打包失败，原因非常多，需要自己排查问题，我无法支持到每个项目打包，插件几乎不会和任何插件产生冲突，除非其他插件适用了非UE 内置的 OpenCV，我将关闭问题，精力有限，实在抱歉
