### ISSUE TITLE
下载了demo工程文件，但是运行不了

### ISSUE THREAD

**Issue by Sherry0w0** [endink/Mediapipe4u-plugin#49]
### MediaPipe4U 版本

20220409

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

Generate project error
错误提示：Some Platforms were skipped due to invalid SDK setup: IOS, Android, Linux, LinuxArm64.
See the log file for detailed information

Discovering modules, targets and source code for project...
Visual Studio 2022 x64 must be installed in order to build this target.

但是已安装VS2022

日志文件：
[UnrealVersionSelector-2023.04.13-16.03.40.log](https://github.com/endink/Mediapipe4u-plugin/files/11219827/UnrealVersionSelector-2023.04.13-16.03.40.log)

**Comment by endink** [comment]
重新生成 VS文件

**Comment by Sherry0w0** [comment]
就是Generate Visual Studio project files时，出现的错误。已经试过删除文件夹重新generate了，一直是一个错误。_(:з」∠)_

**Comment by endink** [comment]
适用 Visual studio installer  修复 Visual studio, 勾选 C++ 游戏开发工作负载

**Comment by Sherry0w0** [comment]
可以打开了，感谢
