### ISSUE TITLE
Bus Error when Load Video in DEMO

### ISSUE THREAD

**Issue by ZiyuGuo99** [endink/Mediapipe4u-plugin#5]
My Log is shown as follows. Could you help me find out the problems? Thanks!
(FYI, I set up every preparations as your doc) : )
LogMediaPipe: Display: Right Thumb Axis: X=-0.000 Y=-0.000 Z=-1.000
LogMediaPipe: Display: Joints calibrated (RightHandSolver) .
LogMediaPipe: Display: Bone mapped: LeftShoulder ----> [11]upperarm_l ( parent: [10]clavicle_l )
Bone mapped: RightShoulder ----> [57]upperarm_r ( parent: [56]clavicle_r )
Bone mapped: LeftElbow ----> [12]lowerarm_l ( parent: [11]upperarm_l )
Bone mapped: RightElbow ----> [58]lowerarm_r ( parent: [57]upperarm_r )
Bone mapped: LeftWrist ----> [20]hand_l ( parent: [12]lowerarm_l )
Bone mapped: RightWrist ----> [66]hand_r ( parent: [58]lowerarm_r )
Bone mapped: LeftPinky ----> [26]pinky_01_l ( parent: [25]pinky_metacarpal_l )
Bone mapped: RightPinky ----> [72]pinky_01_r ( parent: [71]pinky_metacarpal_r )
Bone mapped: LeftIndex ----> [37]index_01_l ( parent: [36]index_metacarpal_l )
Bone mapped: RightIndex ----> [83]index_01_r ( parent: [82]index_metacarpal_r )
Bone mapped: LeftThumb ----> [34]thumb_02_l ( parent: [33]thumb_01_l )
Bone mapped: RightThumb ----> [80]thumb_02_r ( parent: [79]thumb_01_r )
Bone mapped: LeftHip ----> [129]thigh_l ( parent: [1]pelvis )
Bone mapped: RightHip ----> [106]thigh_r ( parent: [1]pelvis )
Bone mapped: LeftKnee ----> [130]calf_l ( parent: [129]thigh_l )
Bone mapped: RightKnee ----> [107]calf_r ( parent: [106]thigh_r )
Bone mapped: LeftAnkle ----> [131]foot_l ( parent: [130]calf_l )
Bone mapped: RightAnkle ----> [108]foot_r ( parent: [107]calf_r )
Bone mapped: LeftHeel ----> [131]foot_l ( parent: [130]calf_l )
Bone mapped: RightHeel ----> [108]foot_r ( parent: [107]calf_r )
Bone mapped: LeftFootIndex ----> [132]ball_l ( parent: [131]foot_l )
Bone mapped: RightFootIndex ----> [109]ball_r ( parent: [108]foot_r )
Bone mapped: Hip ----> [1]pelvis ( parent: [0]root )
Bone mapped: Head ----> [9]head ( parent: [8]neck_02 )
Bone mapped: Neck ----> [7]neck_01 ( parent: [6]spine_05 )
Bone mapped: Spine ----> [2]spine_01 ( parent: [1]pelvis )
LogMediaPipe: Display: LocationSolver: 38 bone cached
LogGStreamer: Error: GstPipeline: BUS ERROR <MediaPipe_GS_Pipline>
LogMediaPipe: Display: [mediapipe_api.dll] CalculatorGraph::StartRun
enable_segmentation : mediapipe::Packet with timestamp: Timestamp::Unset() and type: bool
input_horizontally_flipped : mediapipe::Packet with timestamp: Timestamp::Unset() and type: bool
input_rotation : mediapipe::Packet with timestamp: Timestamp::Unset() and type: int
input_vertically_flipped : mediapipe::Packet with timestamp: Timestamp::Unset() and type: bool
model_complexity : mediapipe::Packet with timestamp: Timestamp::Unset() and type: int
refine_face_landmarks : mediapipe::Packet with timestamp: Timestamp::Unset() and type: bool
smooth_landmarks : mediapipe::Packet with timestamp: Timestamp::Unset() and type: bool
smooth_segmentation : mediapipe::Packet with timestamp: Timestamp::Unset() and type: bool
use_prev_landmarks : mediapipe::Packet with timestamp: Timestamp::Unset() and type: bool
LogMediaPipe: Display: [mediapipe_api.dll] ------------> Start Loop Work Thread <------------

**Comment by endink** [comment]
Sorry, this is due to an error inside GStreamer, the plugin packaged currently disabled GStreamer error messages, maybe I can only release a new version for you to print the error message, I couldn't do anything before that.

**Comment by SarahGuo1999** [comment]
Thanks for your reply! I would truly appreciate it if you could send me a new version. My email address is 2101210573@pku.edu.cn

**Comment by endink** [comment]
https://cowtransfer.com/s/1c4f0dcd0b9a40
----

This version was packaged during my development, I have not gone through packaging tests and DEMO project tests, but I believe it will worked, and I have opened GStreamer logs in it, if you can get logs from this package it will be a victory, LOL, BTW, This version has optimized fingers to have this better finger effect. Thanks for your issue reporting ag.

**Comment by SarahGuo1999** [comment]
Received with thanks! I'll have a try. : )

**Comment by endink** [comment]
已经修复，无法确认修复情况~
