### ISSUE TITLE
无法打开包括文件: “GstElementComponent.generated.h”: No such file or directory

### ISSUE THREAD

**Issue by xiehuiqi220** [endink/Mediapipe4u-plugin#51]
### MediaPipe4U 版本

2022.0.1

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

其他

### 错误详细描述

![image](https://user-images.githubusercontent.com/1331211/232315305-c30c239e-baf6-4ddb-83db-335dc71db28e.png)
![image](https://user-images.githubusercontent.com/1331211/232315351-eab3c61f-1d36-46a9-8ed0-4ee79a0770aa.png)
ue 5.1，生成项目解决方案之后，应该是没有产生 generated.h 文件，导致编译失败
> MediaPipe4U-Demo\Plugins\GStreamer\Source\GStreamer\Public\GstElementComponent.h(4): fatal error C1083: 无法打开包括文件: “GstElementComponent.generated.h”: No such file or directory

visual studio 2022 community 版本

**Comment by endink** [comment]
这是预编译插件，但是看起来你进行了“完整编译”，预编译不会再源文件中包含 .generated.h,  因为这些文件已经在“中间缓存”目录里生成好，通常路径是插件目录下：

Intermediate\Build\Win64\UnrealGame\Inc\ { PluginName } \UHT

请检查 Intermediate 目录是否完整，同时确保你没有用 VS 或者 Rider 执行过 Clean Solution

**Comment by endink** [comment]
尝试一下步骤解决问题：
1. clearn_project.bat
2. 右键点击 uproject 文件，重新生成 vs 文件 (generate vs files）
3. 使用 vs2022 (注意：必须 VS 2022) 或者 Rider (也需要安装 VS 2022) 生成解决方案（Build Solution）
