### ISSUE TITLE
The live link does not appear and add source the live link is disabled.

### ISSUE THREAD

**Issue by zaikit** [endink/Mediapipe4u-plugin#54]
### MediaPipe4U Version

20230409

### UE Version

5.1.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

The live link does not appear and add source the live link is disabled.
![Live_Link_1](https://user-images.githubusercontent.com/89686732/232641368-3265860d-d30c-47d3-a4da-5f86fc7966d9.png)
![Live_Link_2](https://user-images.githubusercontent.com/89686732/232641408-9df1cdf2-8af1-41e8-ae64-81e317d3c32e.png)

How can we fix it?
Thank you,

**Comment by endink** [comment]
Dont create it manually, it is only available when starting the game. Just click "Play"
