### ISSUE TITLE
How to show the input video from the camera?

### ISSUE THREAD

**Issue by zaikit** [endink/Mediapipe4u-plugin#56]
### Comparison Product

2023-04-08

### Feature Category

New Runtime Feature

### Feature Description

I have used this tutorial [https://opensource.labijie.com/Mediapipe4u-plugin/quick_start/texture_display.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp] to show the camera input. However, this tutorial use old plugin version. There some component not exist in new plugin version (2023-04-08).

Can you tell me how to show the input video from camera using new plugin version ((2023-04-08)?
Thank you,,

**Comment by endink** [comment]
which component is missed ,I think the doc is worked for your version

**Comment by zaikit** [comment]
From demo project blueprint like this,
![Demo](https://user-images.githubusercontent.com/89686732/234116229-faa01bb0-2da6-402f-b397-d4bdb6a3431f.png)
I try update the blueprint of my project
![Update](https://user-images.githubusercontent.com/89686732/234116374-2d7a51c0-d863-4a17-8c94-f3373a255bfe.png)
Because my project didn't use UI component, what is the input of the Widget in Anchor Widget in Canvas component?

**Comment by endink** [comment]
Its an Image widget, it means align image that in canvas. This function will calculate image size and position.

**Comment by endink** [comment]
In summary, there are three things to do to display an image:   
1. Calculate the image size (because the frame size is different)   
2. Set the material of the Image widget(this can be done once at the beginning of the application)   
3. Set the texture to the material

**Comment by zaikit** [comment]
What are the nodes needed to show the image?
From this blueprint, what is needed to be updated?
![Update](https://user-images.githubusercontent.com/89686732/234442771-279edf79-e990-4584-8e27-87f39a219bca.png)

**Comment by endink** [comment]
please see this tutorial video:   

[https://www.youtube.com/watch?v=_6OLqClX-Fw](https://www.youtube.com/watch?v=_6OLqClX-Fw)

**Comment by zaikit** [comment]
Thank you,,
