### ISSUE TITLE
fatal error C1083: 无法打开包括文件: “ImageConsumerProvider.generated.h”: No such file or directory

### ISSUE THREAD

**Issue by woofei** [endink/Mediapipe4u-plugin#57]
### MediaPipe4U 版本

M4U_UE_5_1_20230423

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

源码编译

### 问题类型

运行错误

### 错误详细描述

项目源码编译报错，ImageConsumerProvider.generated.h”: No such file or directory

**Comment by endink** [comment]
请阅读文档，检查环境要求，并使用VS2022

**Comment by endink** [comment]
https://opensource.labijie.com/Mediapipe4u-plugin/Install/requirement.html
