### ISSUE TITLE
UE 5.1 - mediapipe4u license expired even after being replaced.

### ISSUE THREAD

**Issue by AOK-VISIONS** [endink/Mediapipe4u-plugin#58]
### MediaPipe4U Version

MediaPipe4U_ue_5_1_20230316

### UE Version

5.1.x

### UnrealEngine Type

Compiled From Source Code

### What happened?

Hello again,
I am receiving an error now stating the MediaPipe4U license has expired in my output log.
![Screenshot 2023-05-03 162411](https://user-images.githubusercontent.com/130712898/236041658-7da35c72-7201-484b-82d0-a31dd1cca5a9.png)

The start webcam will not work and returns an error saying "MediaPipeContext is NULL" which I am sure is related to this.
![Screenshot 2023-05-03 162711](https://user-images.githubusercontent.com/130712898/236041952-76170d6e-0bee-4052-869b-ea8cbc96d9e9.png)

I have replaced the license file however with the latest license file from the M4U_UE_5_1_20230423 plugin download, but still receive this error even after replacing.

![Screenshot 2023-05-03 162510](https://user-images.githubusercontent.com/130712898/236042490-404d71f7-c2ef-4c97-a96a-dc7dfc051994.png)

I have also tried cleaning the demo project, cleaning the 20230316 plugin and replacing the license before I compile the project in VS, and the problem still persists... any idea of what's wrong here?
Thanks.

**Comment by endink** [comment]
Use 20230423 version plugin, license format has been changed since 20230423.

**Comment by AOK-VISIONS** [comment]
Got it, thanks!
