### ISSUE TITLE
动补运行时报错

### ISSUE THREAD

**Issue by JKJ526523** [endink/Mediapipe4u-plugin#59]
### MediaPipe4U 版本

20230423

### UnrealEngine 版本

5.0.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

许可证已正常更新。运行动补失败，log如下。之前正常运行，忽然开始出现的这个问题，请教如何解决。
![image](https://user-images.githubusercontent.com/112796858/236232662-df7708b4-6183-437a-816b-2d90a6a591cd.png)

**Comment by endink** [comment]
上传日志文件，使用最新版插件

**Comment by endink** [comment]
关闭 map 重新打开或许会解决问题

**Comment by JKJ526523** [comment]
[MediaPipe4U-Demo.log](https://github.com/endink/Mediapipe4u-plugin/files/11398990/MediaPipe4U-Demo.log)
这是日志文件，请您看一下是哪里出了问题。（插件今晚刚替换成0423的许可证）

**Comment by endink** [comment]
日志中出现错误了 Error: MediaPipe4U license has expired !

我想你是用了最新的许可证，但是插件用的是旧的，最新的许可证因为格式有一点点变化，旧版插件可能无法兼容，更新一下插件就可以。

**Comment by JKJ526523** [comment]
感谢。是的，我更新了插件之后解决了这个问题。但是有新的问题，新版插件的GroundIK 功能貌似进行了调整，请问我需要怎么做才能让GroundIk正常工作呢？

**Comment by endink** [comment]
嗯？没有动过那块呀，能否新开个 issue 让我知道是什么问题

**Comment by JKJ526523** [comment]
好的，稍等。
