### ISSUE TITLE
Engine Crashes after choosing Video

### ISSUE THREAD

**Issue by YousefBadr** [endink/Mediapipe4u-plugin#60]
### MediaPipe4U Version

20230423

### UE Version

5.1.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

I'm using the demo project. After choosing any video the engine crashes with the following error:
`
Unhandled Exception: 0xc06d007e

KERNELBASE
UnrealEditor_GStreamer!__delayLoadHelper2() [D:\a\_work\1\s\src\vctools\delayimp\delayhlp.cpp:312]
UnrealEditor_GStreamer!_tailMerge_gstreamer_1_0_0_dll()
UnrealEditor_GStreamer!GstUtils::GetProtocolFromUri() [F:\3D_Works\UE\MediaPipe4U\Build\GStreamer\HostProject\Plugins\GStreamer\Source\GStreamer\Private\GstUtils.cpp:30]
UnrealEditor_MediaPipeGStreamer!UGStreamerImageSourceComponent::BuildUriAndValidate() [F:\3D_Works\UE\MediaPipe4U\Build\MediaPipe4UGStreamer\HostProject\Plugins\MediaPipe4UGStreamer\Source\MediaPipeGStreamer\Private\GStreamerImageSourceComponent.cpp:172]
UnrealEditor_MediaPipeGStreamer!UGStreamerImageSourceComponent::Start() [F:\3D_Works\UE\MediaPipe4U\Build\MediaPipe4UGStreamer\HostProject\Plugins\MediaPipe4UGStreamer\Source\MediaPipeGStreamer\Private\GStreamerImageSourceComponent.cpp:95]
UnrealEditor_MediaPipeGStreamer!UGStreamerImageSourceComponent::execStart() [F:\3D_Works\UE\MediaPipe4U\Build\MediaPipe4UGStreamer\HostProject\Plugins\MediaPipe4UGStreamer\Intermediate\Build\Win64\UnrealEditor\Inc\MediaPipeGStreamer\UHT\GStreamerImageSourceComponent.gen.cpp:85]
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_Engine
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_UMG
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
user32
user32
InkObj
atlthunk
user32
user32
UnrealEditor_ApplicationCore
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
`

**Comment by endink** [comment]
https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/Install/gstreamer.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by YousefBadr** [comment]
Thanks a lot. Will try that.

**Comment by endink** [comment]
If issue fixed, I will close this issue.
