### ISSUE TITLE
Plugin stopped working after new map

### ISSUE THREAD

**Issue by saechisaechi** [endink/Mediapipe4u-plugin#62]
### MediaPipe4U Version

M4U_5_0_20230409

### UE Version

5.0.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

I added a new environment from the marketplace, and made that map the starter map. I put the same mediapipecomponents, and avatar with the same blueprints and animation on this new map, but it didn't work when I started it. 

I thought maybe the license is expired so I replaced the license with the version from M4U_UE_5_0_20230505.7z, but it still doesn't work. 

I went back to the map it used to work before (ThirdpersonBP starter map) but it also doesnt start anymore. 

I'm not sure what to do, I didnt change any of the codes when changing between maps.  Even pressing webcam capture from the Mediapipe Toolkit doesnt start it. 

![image](https://user-images.githubusercontent.com/87157576/237042549-4ad02e62-4a06-46f6-a0da-db5bbe9df41b.png)![image](https://user-images.githubusercontent.com/87157576/237042764-f534dea9-b584-4d93-80c2-e98e413caa60.png)
![image](https://user-images.githubusercontent.com/87157576/237042947-0926f158-aa71-4f76-833d-769c9e79fb23.png)

**Comment by endink** [comment]
sorry， please use the newest version of plugin , the license file format has changed since 20230423. So

**Comment by endink** [comment]
Its my fault , sorry again!

**Comment by endink** [comment]
By the way, newest version has a known Bug in UE5.0, please delete asserts in Content folder. This has no bad effects other than affecting the toolkit display.

**Comment by saechisaechi** [comment]
Do I delete the old plugins in the content folder and then install the new plugin? Sorry I'm not sure what to delete for the bug

**Comment by endink** [comment]
Delete MediaPipe4U/Content folder after you downloaded and unzip the    newest plugin.

**Comment by saechisaechi** [comment]
Thank you! It works again
