### ISSUE TITLE
更新插件版本后GroundIK功能出现问题。

### ISSUE THREAD

**Issue by JKJ526523** [endink/Mediapipe4u-plugin#63]
### MediaPipe4U 版本

20230423

### UnrealEngine 版本

5.0.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

我的插件原本是一直使用您刚更新GroundIK那个版本，这次更新成了最新插件版本。ABP_Mannequins_Mediapipe  中  Mediapipe Location Solver节点显示编译警告，之前暴露出来的一个校准时间的参数有更新，我刷新了一下节点。但是GroundIK仍然不工作，麻烦您看一下是哪里出了问题。
![image](https://github.com/endink/Mediapipe4u-plugin/assets/112796858/12524208-8a69-4425-8f79-03eda7c6f7b1)
[MediaPipe4U-Demo.log](https://github.com/endink/Mediapipe4u-plugin/files/11442657/MediaPipe4U-Demo.log)

**Comment by endink** [comment]
哦，ground ik 没有变化，我回头测试一下 ground ik，校准时间变量确实有变化，这个属性移动到动画蓝图（MediaPipeAnimInstance）的属性上了，因为后续还要用它校准骨骼~

**Comment by JKJ526523** [comment]
感谢您，是这个原因导致功能失效了吗？我该如何修改能够使得GroundIK正常工作呢。

**Comment by endink** [comment]
位置校准和 ground ik 是独立工作的，应该没有影响，你可以检查：
- 动画蓝图上变量 SolveLocation 是否勾选

绘制调试信息：
1. 打开动画蓝图 DebugDraw
2. 打开 SolveLocation 节点 DebugDraw
3. 运行程序

当 ground ik 不工作时，把带调试线条的截图贴出来

**Comment by endink** [comment]
另外，可以尝试移除 Location Solver 节点，再重新添加，然后重新编译一下动画蓝图

**Comment by JKJ526523** [comment]
动画蓝图上的变量SolveLocation已勾选，调试线条是这样的，有黄点正确检测了地面
![image](https://github.com/endink/Mediapipe4u-plugin/assets/112796858/4fc5c653-94e6-4b0f-82e8-8d5816cb60a8)

**Comment by endink** [comment]
嗯？看调试线条应该是没有问题的，但是我没有测试过 5.0 版本，之前能正常吗？这块没有更改任何代码的，看了你的日志文件，也没有发生什么错误, 你说的不正常是人悬空还是脚偶尔不贴合？

**Comment by endink** [comment]
如果你指的是偶尔的脚不贴合，请查阅 groundik 文档：

https://opensource.labijie.com/Mediapipe4u-plugin/features/location_solver.html

不同的视频有不同的运动速度，很难泛化的预测，可以通过三个参数来微调 Ground IK 效果：

- FeetDampingDistance
- JumpVelocityThreshold
- FeetSmoothSpeed

文档中有这些参数的详细解释。

**Comment by JKJ526523** [comment]
不是偶尔的脚不贴和，是这个蹲下的时候人物的脚远远地脱离地面了。之前动补这个视频是能够正常地让脚贴合地面的。

**Comment by JKJ526523** [comment]
调试了一番，但是仍然没有解决这个问题。。。请您看一下脚底下有个红点是说明有错误吗，或者请教您我该如何修改让功能正常运行
![image](https://github.com/endink/Mediapipe4u-plugin/assets/112796858/1a28612b-34f5-4be3-b201-5938848533b0)

**Comment by endink** [comment]
红点是地面对齐线条，不是错误，我在UE5.1测试没有复现你的问题，尝试锁定位移的三个轴向

**Comment by endink** [comment]
另外提供一下动画蓝图属性的完整截图

**Comment by JKJ526523** [comment]
动画蓝图属性
![image](https://github.com/endink/Mediapipe4u-plugin/assets/112796858/56888763-099d-4c20-98d4-4b0995d0ed61)

**Comment by endink** [comment]
能找到复现他的最小步骤吗？我本地复现不出这个问题

**Comment by endink** [comment]
如果是 Demo 工程改的， 可以传一个网盘分享给我

**Comment by endink** [comment]
我只能处理Demo 工程逻辑，自己的工程我处理不了，精力有限，我不可能读所有用户的程序逻辑抱歉

**Comment by JKJ526523** [comment]
我这边只是在demo工程中添加了一些环境植物，逻辑是基本没有改动的。我在b站私聊发您可以吗

**Comment by endink** [comment]
可以的，你B 站私信我，网盘就行

**Comment by endink** [comment]
BTW， 你的 DEMO 是最新的吗，最新版本插件最好使用最新 DEMO

**Comment by JKJ526523** [comment]
我这边上传网盘有点慢。。需要点时间。我的demo工程不是最新的，因为一直用之前的版本做一点增量工作，没有更新过demo工程

**Comment by endink** [comment]
Mark， 下一个版本解决

**Comment by endink** [comment]
Fixed in 20230617
