### ISSUE TITLE
unreal 5.0.3打包demo工程时，出现“VideoMaterial.uasset is too new. Engine Version: 1004  Package Version: 1008”错误

### ISSUE THREAD

**Issue by 63663455** [endink/Mediapipe4u-plugin#68]
### MediaPipe4U 版本

M4U_UE_5_0_20230423

### UnrealEngine 版本

5.0.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

demo工程打包时，出现以下错误：
UATHelper: 打包 (Windows): LogInit: Display: LogAssetRegistry: Error: Package d:/work/unreal_engine/media_pipe/MediaPipe4U-Demo-UE_5_0_05261342/Plugins/MediaPipe4U/Content/Materials/VideoMaterial.uasset is too new. Engine Version: 1004  Package Version: 1008
UATHelper: 打包 (Windows): LogInit: Display: LogAssetRegistry: Error: Package d:/work/unreal_engine/media_pipe/MediaPipe4U-Demo-UE_5_0_05261342/Plugins/MediaPipe4U/Content/Materials/black_one_pixel.uasset is too new. Engine Version: 1004  Package Version: 1008

具体的打包日志：
[unreal5_0_3打包demo工程时的日志.txt](https://github.com/endink/Mediapipe4u-plugin/files/11572155/unreal5_0_3.demo.txt)

怎么样才能用unreal 5.0.3对工程进行打包（development）？

**Comment by endink** [comment]
使用最新版或者删除 MediaPipe4U 插件中的 Content ，编辑器工具的材质有点问题，新版已经不使用材质

**Comment by endink** [comment]
尽可能使用5.1, BUG会少一些，因为开发使用5.1， 5.0可能会有遗漏不少测试
