### ISSUE TITLE
demo工程第1次编译成功运行后，执行clean_project.bat，再生成sln文件进行编译时，出现“ImageConsumerProvider.generated.h”: No such file or directory”错误

### ISSUE THREAD

**Issue by 63663455** [endink/Mediapipe4u-plugin#69]
### MediaPipe4U 版本

M4U_UE_5_0_20230423

### UnrealEngine 版本

5.0.x

### UnrealEngine 类型

Launcher

### 问题类型

插件安装

### 错误详细描述

demo工程第1次编译成功运行后，执行clean_project.bat，再生成sln文件进行编译时，出现“ImageConsumerProvider.generated.h”: No such file or directory”错误。

这时必须重新解压demo工程，解压后的工程文件夹名称不能和之前的一样，比如之前解压后的工程名称为“MediaPipe4U-Demo-UE_5_0”，必须重命名为不一样的目录，再进行编译，才不会报错。

请大佬帮忙解决一下这个问题！

**Comment by endink** [comment]
generated.h 你只要按文档安装正确的 VS版本和 VC包
