### ISSUE TITLE
Mediapipe location solver

### ISSUE THREAD

**Issue by thenighthunter0** [endink/Mediapipe4u-plugin#7]
再次感谢大佬，询问位移相关问题。
当设定如下，z改为1.8，标定倒计时0
![image](https://user-images.githubusercontent.com/29919918/205242313-4bb1b6ff-b415-4574-8866-52e1f85241ea.png)
1.输入一个4s视频，出现现象为：
（1）第一次播放，在原地摔倒，且摔倒在空中，hip保持不动，即无location位移
![image](https://user-images.githubusercontent.com/29919918/205243468-a4ddebb5-cbca-4634-a08a-af003abb93b7.png)
（2）后续的轮播：
         人物上升，feet位置与原来hip平齐，摔倒动作正常(z轴有变化)
![image](https://user-images.githubusercontent.com/29919918/205243584-98907697-76eb-4485-a203-ffa5fa7395bc.png)
![image](https://user-images.githubusercontent.com/29919918/205243723-ada8259b-7fa1-469e-bb11-4a2a48774799.png)

这个是因为蓝图中，mediapipe location solver我排在了最前面导致的问题。

2.标定，的原理是什么？标定地面吗？还是标注人物？还是建立坐标系？

**Comment by thenighthunter0** [comment]
这个是因为蓝图中，mediapipe location solver我排在了最前面导致的问题。
mediapipe location solver的顺序，会引发上述情况。

**Comment by endink** [comment]
标定的意思是初始化摄像头画面中的点的位置，既然你已经在位移上做了这么多，当你顺利解决问题后，如果你能在 B 站发表一个简单视频，让其他人知道你是如何使用位移的，我会感激不尽~

**Comment by endink** [comment]
或许，叫做校准相机更为合理

**Comment by thenighthunter0** [comment]
好的，还有些小问题没解决好，后面搞好会发的
