### ISSUE TITLE
NVAR插件打包问题，5月26日下载的demo和插件，在打包时报错，去掉NVAR插件则可以打包成功。

### ISSUE THREAD

**Issue by zola-z** [endink/Mediapipe4u-plugin#70]
### MediaPipe4U 版本

20230521

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

项目打包

### 错误详细描述

LogInit: Display: LogMediaPipeNvAR: Error: [NvAR API] Cannot find nvCVImage DLL or its dependencies ( code: NVCV_ERR_LIBRARY, op: NvAR_GetVersion )

**Comment by endink** [comment]
这个错误是CUDA没找到，更新一下显卡驱动？

**Comment by endink** [comment]
Nvidia 显卡驱动有点问题？

**Comment by zola-z** [comment]
我的显卡是1660s，重装驱动后打包还是这个问题，用别人4090的新电脑打包也是这样的问题。不知正好是这两台电脑显卡驱动有问题，还是有相应的SDK包下载？

**Comment by endink** [comment]
难道你没有安装 Nvidia AR SDK 吗，文档不是写清楚环境了吗

**Comment by endink** [comment]
https://opensource.labijie.com/Mediapipe4u-plugin/mocap/experiment/nvar.html

**Comment by zola-z** [comment]
惭愧，给您添麻烦了
