### ISSUE TITLE
cannot find Unreal5.1 mediapipe livelink component

### ISSUE THREAD

**Issue by stella00000100000** [endink/Mediapipe4u-plugin#71]
### MediaPipe4U Version

5.1

### UE Version

5.1.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

感谢大神分享mediapipe的插件！我用的是UE5.1，安装的是5.1版本的mediapipe4u。
[跟着文档在设定的时候，在创建角色组件的步骤中，文档中说需要添加四个组件。唯独找不到MediapipeLivelink这个组件。
<img width="374" alt="微信截图_20230531164448" src="https://github.com/endink/Mediapipe4u-plugin/assets/100847930/ec3fb92f-738e-4fd3-897f-b13f058d4807">
想问一下是我的设置哪里不对吗？
所有相关插件都已开启。
<img width="471" alt="微信图片_20230531164332" src="https://github.com/endink/Mediapipe4u-plugin/assets/100847930/f1f5fb12-97f8-4f45-953f-c75542afc2cb">

**Comment by endink** [comment]
MediapipeLiveLink 是一个 Actor ，并不是一个 Component (组件)， 你应该在内容浏览器种查找，然后将它拖放到场景中

**Comment by stella00000100000** [comment]
懂了！感谢指点

**Comment by endink** [comment]
emmm... 你必须熟练 UE 的，Actor, Component, Character ，继承等概念，这不是一个新手友好的插件，或许你应该考虑外挂式的解决方案，例如类似乐道师那种东西。
