### ISSUE TITLE
虚拟摄像头读取了错误的分辨率

### ISSUE THREAD

**Issue by TheWaytao** [endink/Mediapipe4u-plugin#73]
### Feature Category

New Runtime Feature

### Feature Description

我使用ds的虚拟摄像头作为视频源，并设置分辨率为1920*1080，但实际log中读取到的视频分辨率为：853*480，这导致StartCamera这个函数并没有实际读取到虚拟摄像头中的视频
![image](https://github.com/endink/Mediapipe4u-plugin/assets/93570962/48768c31-d6ef-4e3a-af2c-e8d23d07bd24)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/93570962/a3f7549a-d90f-48d2-bf39-dce54eb7e370)

**Comment by endink** [comment]
这不是读取错误，是缩放了分辨率，1080P 会很卡很卡，如果显示黑屏说明摄像头不支持 direct show, 分辨率控制在 MediaPipeHolistic 上有属性

**Comment by TheWaytao** [comment]
好的，我找到了切换分辨率的地方了，同事说您是用OpenCV进行解析的，而解析obs时会导致一些无法读取的问题，是这样的吗

**Comment by endink** [comment]
是的，是用 opencv

**Comment by endink** [comment]
OBS 内置虚拟摄像头无法兼容 Directshow , 可以用这个插件 https://github.com/Avasam/obs-virtual-cam/releases

**Comment by TheWaytao** [comment]
好的，已经解决了
