### ISSUE TITLE
打包遇到错误

### ISSUE THREAD

**Issue by WZQ1997** [endink/Mediapipe4u-plugin#74]
### MediaPipe4U 版本

20230620

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

项目打包

### 错误详细描述

在打包一开始遇到了下面的问题
UATHelper: 打包 (Windows): Find MediaPipe File: mediapipe\modules\pose_landmark\pose_landmark_lite.tflite
UATHelper: 打包 (Windows): Find MediaPipe File: mediapipe\modules\face_geometry\data\geometry_pipeline_metadata_landmarks.binarypb
UATHelper: 打包 (Windows): Find Speech Module File: overlipsync\ovrlipsync_offline_model.pb
UATHelper: 打包 (Windows): Parsing headers for MediaPipe4U_Demo
UATHelper: 打包 (Windows):   Running Internal UnrealHeaderTool D:\Mediapipe4U\Demo\0621\MediaPipe4U-Demo-main\MediaPipe4U-Demo.uproject D:\Mediapipe4U\Demo\0621\MediaPipe4U-Demo-main\Intermediate\Build\Win64\MediaPipe4U_Demo\Shipping\MediaPipe4U_Demo.uhtmanifest -WarningsAsErrors -installed
UATHelper: 打包 (Windows): Total of 6 written
UATHelper: 打包 (Windows): Reflection code generated for MediaPipe4U_Demo in 0.5610497 seconds
UATHelper: 打包 (Windows): Missing precompiled manifest for 'DesktopPlatform', 'D:\UE5\UE_5.1\Engine\Intermediate\Build\Win64\UnrealGame\Shipping\DesktopPlatform\DesktopPlatform.precompiled'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in DesktopPlatform.build.cs to override. If part of a plugin, also check if its 'Type' is correct.
UATHelper: 打包 (Windows): Took 1.5949148s to run dotnet.exe, ExitCode=6
UATHelper: 打包 (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\admin、\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+UE5+UE_5.1\UBT-MediaPipe4U_Demo-Win64-Shipping.txt)
UATHelper: 打包 (Windows): AutomationTool executed for 0h 0m 2s
UATHelper: 打包 (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: 打包 (Windows): BUILD FAILED

**Comment by endink** [comment]
请阅读打包文档，看起来这是源码编译的引擎

**Comment by endink** [comment]
确保VC和VS版本正确，VS2022要升级17.6.3

**Comment by WZQ1997** [comment]
感谢回答，我已经正确的解决了打包的问题。现在有我个新的问题，使用插件如果从外部获取音视频流进行动捕的话音频数据是被丢弃了吗，或者有方法可以再场景中输出音频吗

**Comment by endink** [comment]
你好，如果有新的问题，麻烦提交一个新的 issue, 这样方便后来者查看，尽可能避免技术支持的重复劳动，谢谢合作~
