### ISSUE TITLE
你好，我的数字人用新版插件动捕时关节会变形，老版插件动捕正常。尝试把新版许可文件放在项目的老版插件文件夹里，启动UE5.1后项目设置里的许可日期为什么还是老版的许可日期呢？

### ISSUE THREAD

**Issue by hyc88988898** [endink/Mediapipe4u-plugin#75]
### MediaPipe4U 版本

M4U_UE5_1_20230620

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

项目打包

### 错误详细描述

1. 新插件的许可文件覆盖了老插件的许可文件
![微信图片_20230625133835](https://github.com/endink/Mediapipe4u-plugin/assets/134036282/1f9b29b2-549a-4bf3-8509-e13877c3f0d5)

2. 项目设置里的许可日期显示的还是老版的许可日期
![微信图片_20230625133843](https://github.com/endink/Mediapipe4u-plugin/assets/134036282/1a03a9ed-47d1-407d-aad3-0888cdf976b0)

3. 打包时提示这些信息
![微信图片_20230625133848](https://github.com/endink/Mediapipe4u-plugin/assets/134036282/4b8ef87d-fdf4-47c6-8ed8-aed3533c9edd)

请问老版插件用新的许可文件，我当如何应对？

**Comment by endink** [comment]
请阅读文档，你要覆盖 Source 文件夹中的许可证文件，而不是 Binaries。

https://opensource.labijie.com/Mediapipe4u-plugin/licensing/update_license.html

**Comment by endink** [comment]
新版如果你的模型有错误你可以把贴图移除，提供一个白模，并且导出一份骨骼映射的 json （创建映射的编辑器里有导出按钮）然后私信共享网盘给我，这样我修复你无法使用新版的问题， 谢谢~

**Comment by endink** [comment]
新版已修复了使用扭曲矫正时的计算错误的 BUG

**Comment by hyc88988898** [comment]
是的，新版插件的关节扭曲现象明显改善了
