### ISSUE TITLE
导入新插件后，重启UE出现问题

### ISSUE THREAD

**Issue by hyxdss** [endink/Mediapipe4u-plugin#76]
### MediaPipe4U 版本

20230620

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

插件安装

### 错误详细描述

导入插件后，UE就启动不了，提示：An Unreal process has crashed:UE-***（项目名称）
<img width="549" alt="屏幕截图 2023-06-26 235559" src="https://github.com/endink/Mediapipe4u-plugin/assets/132764897/137de18f-2e95-46da-9b34-de8a5f3190ab">

**Comment by endink** [comment]
看起来是你没有安装 GStreamer , 请参阅文档安装 GStremer

**Comment by hyxdss** [comment]
已解决

**Comment by hyxdss** [comment]
修复了一下GStremer

**Comment by endink** [comment]
Mark 一下， GStreamer 不存在时，程序不应该崩溃~~后续版本解决
