### ISSUE TITLE
关于音频的获取问题

### ISSUE THREAD

**Issue by WZQ1997** [endink/Mediapipe4u-plugin#77]
### MediaPipe4U 版本

20230620

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

其他

### 错误详细描述

使用插件如果从外部获取音视频流或者使用mp4视频文件进行动捕的话音频数据是被丢弃了吗，或者有方法可以再场景中输出音频吗

**Comment by endink** [comment]
出于性能考虑，GStreamer 部分的代码中没有去解码音频，你可以认为音频轨道被丢弃了，解码音频可能会降低动补性能。

**Comment by endink** [comment]
如果是外部数据，为什么不使用软件抽取音轨然后背景播放 mp3，这样不会影响到视觉处理部分的性能

**Comment by WZQ1997** [comment]
是这样的，我需要将这个音频在场景中播放出来，例如动捕的小白人做了一个拍手的动作，场景中也会出现拍手的声音。

**Comment by endink** [comment]
现在暂时无法支持，但是最近这两天会发布一个版本，这个版本会支持 MediaPlayer 图像源，这样你就可以自己采集音频来满足你的场景

**Comment by WZQ1997** [comment]
好的，感谢回答

**Comment by endink** [comment]
新版已发布，可以尝试 MediaPlayer Image Source 同时捕获音频和视频。   
参考文档：   

https://opensource.labijie.com/Mediapipe4u-plugin/mocap/features/image_source.html
