### ISSUE TITLE
插件无法启动

### ISSUE THREAD

**Issue by bayinbilige** [endink/Mediapipe4u-plugin#78]
### MediaPipe4U 版本

M4U_UE5_1_20230521

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

[eeeeee.log](https://github.com/endink/Mediapipe4u-plugin/files/11905344/eeeeee.log)

**Comment by endink** [comment]
MediaPipe4U license has expired !!!!!

拜托~自己看一下日志，已经提示你许可证过期了

**Comment by bayinbilige** [comment]
你好，许可证过期了怎么办。



---原始邮件---
发件人: "Anders ***@***.***&gt;
发送时间: 2023年7月1日(周六) 下午4:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [endink/Mediapipe4u-plugin] 插件无法启动 (Issue #78)




 
MediaPipe4U license has expired !!!!!
 
拜托~自己看一下日志，已经提示你许可证过期了
