### ISSUE TITLE
MediaPipeRemapAsset  无法正常工作

### ISSUE THREAD

**Issue by dragonpoint** [endink/Mediapipe4u-plugin#79]
### MediaPipe4U 版本

20230628

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

MediaPipeRemapAsset  无法正常工作，我确信一切配置都按照你的文档设置好了
MediaPipeAnimInstance-->BonePreset=Custom  & BoneRemap=NewMediaPipeRemapAsset

log errors
LogMediaPipe: Error: Invalid bone 'None' for joint Hip (SolveJoint(Hip)).
LogMediaPipe: Error: Invalid bone 'None' for joint Spine (SolveJoint(Spine)).
LogMediaPipe: Error: Invalid bone 'None' for joint Chest (SolveJoint(Chest)).
LogMediaPipe: Error: Invalid bone 'None' for joint LeftShoulder (SolveJoint(LeftShoulder)).
LogMediaPipe: Error: Invalid bone 'None' for joint LeftElbow (SolveJoint(LeftElbow)).
LogMediaPipe: Error: Required bones not found for ik chain : [NULL] --> [LeftElbow] --> [NULL] (SolveJointIK(LeftElbow))
LogMediaPipe: Error: Invalid bone 'None' for joint RightShoulder (SolveJoint(RightShoulder)).
LogMediaPipe: Error: Invalid bone 'None' for joint RightElbow (SolveJoint(RightElbow)).
LogMediaPipe: Error: Required bones not found for ik chain : [NULL] --> [RightElbow] --> [NULL] (SolveJointIK(RightElbow))
LogMediaPipe: Error: Invalid bone 'None' for joint LeftHip (SolveJoint(LeftHip)).
LogMediaPipe: Error: Invalid bone 'None' for joint LeftKnee (SolveJoint(LeftKnee)).
LogMediaPipe: Error: Required bones not found for ik chain : [NULL] --> [LeftKnee] --> [NULL] (SolveJointIK(LeftKnee))
LogMediaPipe: Error: Invalid bone 'None' for joint LeftAnkle (SolveJoint(LeftAnkle)).
LogMediaPipe: Error: Invalid bone 'None' for joint RightHip (SolveJoint(RightHip)).
LogMediaPipe: Error: Invalid bone 'None' for joint RightKnee (SolveJoint(RightKnee)).
LogMediaPipe: Error: Required bones not found for ik chain : [NULL] --> [RightKnee] --> [NULL] (SolveJointIK(RightKnee))
LogMediaPipe: Error: Invalid bone 'None' for joint RightAnkle (SolveJoint(RightAnkle)).
LogMediaPipe: Error: Invalid bone 'None' for joint Head (SolveJoint(Head)).
LogMediaPipe: Error: Joint 'LeftAnkle' was not mapped to bone.
LogMediaPipe: Error: Joint 'RightAnkle' was not mapped to bone.

**Comment by endink** [comment]
这些日志不是已经告诉你无效的骨骼名称了吗，你使用自定义映射（BonePreset = Custom），但是你的 RemapAsset 资产没有指定骨骼, 请仔细阅读一下文档~~这不是一个不看文档就可以使用的插件，不想阅读文档也请下载 Demo 工程学习

**Comment by dragonpoint** [comment]
大哥，我确认已经按照文档要求设置过了，完全符合你文档的要求，创建了RemapAsset并且设置了变量，我的错误描述中第二行你可能没注意。我本身是二十几年的程序员了，还不至于那么低级。我怀疑要么是文档中有描述有缺失，要么是某种bug。你的deomo中我没有找到RemapAsset关联的例子，或者我找的不够仔细

**Comment by dragonpoint** [comment]
我确认已经按照文档要求设置过了，完全符合你文档的要求，创建了RemapAsset并且设置了
变量，我的错误描述中第二行你可能没注意。deomo中我没有找到RemapAsset关联的例子，或者我找的不够仔细。demo中只有一个RemapAsset资源，并没有其应用的点的例子程序。

![Screen-2023-07-02_07-19-37](https://github.com/endink/Mediapipe4u-plugin/assets/6975520/bf2cc1bc-6fb0-42d5-8088-af2f7658396e)
![Screen-2023-07-02_07-20-15](https://github.com/endink/Mediapipe4u-plugin/assets/6975520/e409979b-6bb2-46f5-a48f-708f8b60d416)
![Screen-2023-07-02_07-17-21](https://github.com/endink/Mediapipe4u-plugin/assets/6975520/d07bd672-92e6-4b1b-b961-4e7ee1019005)
![Screen-2023-07-02_07-15-43](https://github.com/endink/Mediapipe4u-plugin/assets/6975520/f79c214f-ce93-4d7a-9871-cfa34598dfce)
![Screen-2023-07-02_07-16-39](https://github.com/endink/Mediapipe4u-plugin/assets/6975520/aa91437e-6e8f-43eb-b5fd-fc5418531add)

**Comment by endink** [comment]
上传一个完整日志文件

**Comment by endink** [comment]
看起来没问题，project settings--->MediaPipe4U 截个图

**Comment by dragonpoint** [comment]
[Mars.log](https://github.com/endink/Mediapipe4u-plugin/files/11929288/Mars.log)
![Screen-2023-07-02_18-52-21](https://github.com/endink/Mediapipe4u-plugin/assets/6975520/db307782-f94f-4fe6-850f-18e779f141e0)

**Comment by endink** [comment]
从日志里面我很难知道你的问题，但是日志显示的流程是缺少步骤的，M4U 大致的逻辑大概是这样：   

1. 当第一帧动画执行时，如果映射表没有初始化，进行初始化   
2. 当初始化完成后开始从映射表中获取骨骼进行求解   

从日志看你没有执行任何映射表的操作，我猜测你不是一个很正常的蓝图，中间或许有某种动态的行为，普通蓝图映射完成后会在日志中打印骨骼映射表，但是你的日志中是直接就开始求解过程。   
   
---  
如果要进一步排查问题我需要清楚你的动画蓝图逻辑和 MediaPipe4U 前置节点情况

**Comment by endink** [comment]
明天我查看一下代码，看看影响映射表创建的因素，如果是素流可能会影响功能，目前 M4U 不支持网络传输

**Comment by dragonpoint** [comment]
不是网络游戏，我可以做一下测试，排除我这里所有不相干的逻辑，只用你的插件看看行不行

**Comment by dragonpoint** [comment]
我做了一个干净的测试，确实可以驱动，看来是我的动画类可能比较复杂，我自己排查一下别的问题，谢谢帮助

**Comment by endink** [comment]
Pose Solver 节点是最复杂的节点，移除所有 M4U 蓝图节点，仅添加 Hand Solver 节点，观察日志和查看是否可以驱动手指

**Comment by dragonpoint** [comment]
问题基本解决。我的动画类有点复杂，一开始并没有使用Pose Solver ，根据情况动态切换的。
我测试了一下，默认使用Pose Solver ，就可以解决问题。
我自己改一下流程吧。

**Comment by endink** [comment]
嗯？难道你不是用蓝图吗？  如果你适用 C++, 可以禁用算解器: 

参考代码： 
```cpp
UMediaPipeAnimInstance animInstance;
solverProvder = animInstance->GetPoseSolver();
if(solverProvider)
{
    solverProvider->GetSolver().SetDisabled(true);
}
```

**Comment by dragonpoint** [comment]
我是使用蓝图的。蓝图的动画中，有很多状态，好几个不同序列动画的切换，不是一开始就使用了mediapipe的函数，只有需要的时候才会调用相关函数。目前我在动画一启动就先调用一下Solver，后面需要的时候再做切换，一切正常。
所以问题的重点在于，必须在动画类初始化第一次就必须调用一次相关的Solver函数一次？？以前，我的动画初始为其他序列动画，不是动捕部分。

**Comment by endink** [comment]
不懂你说的调用是什么意思，没有约束一开始就要初始化，很多用户的蓝图都很复杂，你可以使用状态机配合子动画蓝图或者直接切换网格体的 AnimationClass ，有关切换动画蓝图你需要阅读文档，有专门说明，切换以后要手动connect一次，因为如果开始不是 M4U的蓝图，begin play的代码会被遗漏
