### ISSUE TITLE
手臂手肘扭曲

### ISSUE THREAD

**Issue by WZQ1997** [endink/Mediapipe4u-plugin#80]
### MediaPipe4U 版本

20230628

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

其他

### 错误详细描述

我使用metahuman进行动捕，手腕会360度旋转，也设置了TwistCorrectionEnabled但是运行起来之后变成手肘360度旋转了
运行起来之后会有LogMediaPipe: Warning: [MediaPipe API] Timestamp rollback !这个打印，不知道是否有影响

<img width="183" alt="CBEF9D~1" src="https://github.com/endink/Mediapipe4u-plugin/assets/39025601/2c782987-94b6-4501-994e-6f2bb9cf0048">
<img width="234" alt="C92E3A~1" src="https://github.com/endink/Mediapipe4u-plugin/assets/39025601/aceb431d-4f7f-4ad4-b1b2-ecb64abb7c06">

**Comment by endink** [comment]
metahuman 不建议开启扭曲矫正，因为它有专用的矫正骨骼，Epic 已经在后期动画蓝图中有矫正逻辑了，关闭矫正就可以，手腕旋转过多是你使用手指算解，但是可能视频中手指动作过快难以识别，全身动补（非半身特写的视频）建议关闭手指，google 没有提供手指评分，很难判断手指是否被识别

**Comment by WZQ1997** [comment]
我更换为半身动捕，去掉了扭曲矫正，旋转手腕速度并不快，但是还是出现了手腕转了360度，小臂没动
<img width="360" alt="3" src="https://github.com/endink/Mediapipe4u-plugin/assets/39025601/b7951fed-5ce9-4a2f-a3f6-6efd5b916a1a">

**Comment by endink** [comment]
你看看后期动画蓝图里有矫正的，需要你自己后期的，这不是插件能解决的，因为矫正骨骼无法通用，如果你不会自己矫正，请使用插件的矫正功能，试着调整矫正权重。

**Comment by endink** [comment]
看你的截图是你禁用了后期动画蓝图，metahuman你就算不做任何配置也不会是这个样子

**Comment by WZQ1997** [comment]
感谢回答，确实是这样的，之前因为UE5.1版本使用metahuman打包会失败需要禁用后期动画蓝图，打开后就可以了

**Comment by endink** [comment]
嗯？打包会失败？ 5.2 可以？

**Comment by WZQ1997** [comment]
我表述错了，是5.1版本在关卡中使用了metahuman后打包成功，但是运行会失败。
![image](https://github.com/endink/Mediapipe4u-plugin/assets/39025601/0391a9b4-add8-4be2-829c-d7900be50c03)
提示这个错误，在UE的官方论坛下也有人在讨论这个问题，应该是只在5.1的情况下才会出现。我所了解到的唯一能正常运行的方法需要勾选禁用后期处理蓝图才可以。

**Comment by endink** [comment]
学习了，美术向的东西我不太熟悉，issue 先开着，后面我会添加自定义矫正骨骼和矫正 BS 支持来“修复”metahuman这个打包问题
