### ISSUE TITLE
MeidaPipe库错误&&错误的摄像头数据拉取

### ISSUE THREAD

**Issue by BlueShadow0125** [endink/Mediapipe4u-plugin#83]
### MediaPipe4U 版本

20230628

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

Demo演示工程运行时报错
LogMediaPipe: Error: Invalid state: MediaPipeContext is NULL.
LogMediaPipe: Error: Unable to connect mediapipe pipline.
我看了一下log，没发现什么有用的信息

Demo演示工程运行时，无法拉取摄像头信息
连接物理摄像头时，ListWebCam函数返回false，拿回来的字符串数组为空
已确定物理摄像头可以被Windows检测到
已尝试安装最新版OpenCV库并添加环境变量，但无效

**Comment by endink** [comment]
插件设置里检查许可证是否过期，查找日志里的错误

**Comment by BlueShadow0125** [comment]
哦是的，我看到了在7月17日过期，我也找到了付费政策，但是付费政策中的Trial版本应当如何获得？我想要先在Demo中查看效果

**Comment by endink** [comment]
我已经在讨论区发布了新的许可证啊，你仔细看看项目页面有链接

**Comment by PanDaDerica** [comment]
您好  UP主希望得到您的指点
Demo演示工程运行时报错
LogMediaPipe: Error: Invalid state: MediaPipeContext is NULL.
LogMediaPipe: Error: Unable to connect mediapipe pipline.
LogGStreamer: Error: GStreamer module is not available.
已经更新mediapipe4u.license文件 
概述：This mediapipe4u license will expire after 1 days
