### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by bayinbilige** [endink/Mediapipe4u-plugin#84]
### MediaPipe4U 版本

M4U_UE5_1_20230628

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

[eeeeee.log](https://github.com/endink/Mediapipe4u-plugin/files/12077383/eeeeee.log)

**Comment by endink** [comment]
请你不要重复提交相同的问题了。   
日志里明明有：
```
Error: MediaPipe4U license has expired !
```

如果你看不懂是什么意思，你应该考虑寻找其他解决方案而不是用 M4U。我已经告诉过你一次了，也写了大量的文档。你不想看文档，也不愿意看主页里的说明，日志打印的信息你也不想看，我实在没有精力反复说明同一个问题 ！！

**Comment by endink** [comment]
劝退一下：   

你应该寻找其他方案，MediaPipe4U 不是一个新手友好的解决方案，也不可能不看文档就能用得清楚~ 代码都是英文错误日志，将来也不会考虑中文日志输出，综上，可能其他得方案会更适合你~

**Comment by bayinbilige** [comment]
许可证有效期多久，好像并没有明显说明发自我的手机-------- 原始邮件 --------发件人： Anders Xiao ***@***.***>日期： 2023年7月18日周二 下午3:41收件人： endink/Mediapipe4u-plugin ***@***.***>抄送： bayinbilige ***@***.***>, Author ***@***.***>主    题： Re: [endink/Mediapipe4u-plugin] 无法启动 (Issue #84)
劝退一下：
你应该寻找其他方案，MediaPipe4U 不是一个新手友好的解决方案，也不可能不看文档就能用得清楚~ 代码都是英文错误日志，将来也不会考虑中文日志输出，综上，可能其他得方案会更适合你~

**Comment by bayinbilige** [comment]
许可证过期后怎么处理，也没有说明。我知道是有效期过了，但我不知道怎么解决？这应该不是我的问题发自我的手机-------- 原始邮件 --------发件人： Anders Xiao ***@***.***>日期： 2023年7月18日周二 下午3:41收件人： endink/Mediapipe4u-plugin ***@***.***>抄送： bayinbilige ***@***.***>, Author ***@***.***>主    题： Re: [endink/Mediapipe4u-plugin] 无法启动 (Issue #84)
劝退一下：
你应该寻找其他方案，MediaPipe4U 不是一个新手友好的解决方案，也不可能不看文档就能用得清楚~ 代码都是英文错误日志，将来也不会考虑中文日志输出，综上，可能其他得方案会更适合你~

**Comment by bayinbilige** [comment]
我即使知道有效期过了，但也无从得知解决方法？你好像并没有说明有效期多久？有效期到了后怎么解决？



---原始邮件---
发件人: "Anders ***@***.***&gt;
发送时间: 2023年7月18日(周二) 下午3:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [endink/Mediapipe4u-plugin] 无法启动 (Issue #84)




 
劝退一下：
 
你应该寻找其他方案，MediaPipe4U 不是一个新手友好的解决方案，也不可能不看文档就能用得清楚~ 代码都是英文错误日志，将来也不会考虑中文日志输出，综上，可能其他得方案会更适合你~

**Comment by bayinbilige** [comment]
抱歉了作者，一个人写一个插件并且运营，确实很耗精力，深表理解。劳烦告诉我许可证过期后怎么处理？

---原始邮件---
发件人: "Anders ***@***.***&gt;
发送时间: 2023年7月18日(周二) 下午3:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [endink/Mediapipe4u-plugin] 无法启动 (Issue #84)




 
劝退一下：
 
你应该寻找其他方案，MediaPipe4U 不是一个新手友好的解决方案，也不可能不看文档就能用得清楚~ 代码都是英文错误日志，将来也不会考虑中文日志输出，综上，可能其他得方案会更适合你~

**Comment by Cynthia0216** [comment]
作者在开发文档中有明确写明白如何操作
https://opensource.labijie.com/Mediapipe4u-plugin/licensing/update_license.html

所以作者再三强调说，需要看开发文档。


如何得知许可证到期，可以看日志，日志会有报错！这时候去查看插件到期日期即可，作者文档也写清楚了

**Comment by bayinbilige** [comment]
嗯嗯，感谢你耐心的解答，我去看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月18日(周二) 下午4:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [endink/Mediapipe4u-plugin] 无法启动 (Issue #84)




 
作者在开发文档中有明确写明白如何操作
 https://opensource.labijie.com/Mediapipe4u-plugin/licensing/update_license.html
 
所以作者再三强调说，需要看开发文档。
 
如何得知许可证到期，可以看日志，日志会有报错！这时候去查看插件到期日期即可，作者文档也写清楚了

**Comment by bayinbilige** [comment]
你好，我查看了文档，还没有找到更新许可证的办法。重新下载插件，还是之前版本的，里面的许可证也是过期的。问一下从哪里更新许可证？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月18日(周二) 下午4:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [endink/Mediapipe4u-plugin] 无法启动 (Issue #84)




 
作者在开发文档中有明确写明白如何操作
 https://opensource.labijie.com/Mediapipe4u-plugin/licensing/update_license.html
 
所以作者再三强调说，需要看开发文档。
 
如何得知许可证到期，可以看日志，日志会有报错！这时候去查看插件到期日期即可，作者文档也写清楚了

**Comment by bayinbilige** [comment]
请问从哪里获得新的许可证？重新下载插件还是之前得版本？许可证也是过期的？



---原始邮件---
发件人: "Anders ***@***.***&gt;
发送时间: 2023年7月18日(周二) 下午3:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [endink/Mediapipe4u-plugin] 无法启动 (Issue #84)




 
劝退一下：
 
你应该寻找其他方案，MediaPipe4U 不是一个新手友好的解决方案，也不可能不看文档就能用得清楚~ 代码都是英文错误日志，将来也不会考虑中文日志输出，综上，可能其他得方案会更适合你~
