### ISSUE TITLE
下载链接里没有更新版本

### ISSUE THREAD

**Issue by bayinbilige** [endink/Mediapipe4u-plugin#85]
### MediaPipe4U 版本

M4U_UE5_1_20230628

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

插件安装

### 错误详细描述

20230628版本的许可证到期，已看到你有7月17日的更新日志，但在下载链接里，还是20230628的版本，里面的许可证还是过期的

**Comment by endink** [comment]
<img width="630" alt="image" src="https://github.com/endink/Mediapipe4u-plugin/assets/240164/223b94cf-258c-4fc0-97d6-b72be3744a51">

大哥，首页上这么大几个字，你不能自己好好看一下吗~

**Comment by endink** [comment]
https://github.com/endink/Mediapipe4u-plugin/discussions/82
