### ISSUE TITLE
烘焙工具错误

### ISSUE THREAD

**Issue by Uzaker** [endink/Mediapipe4u-plugin#88]
### MediaPipe4U 版本

20230719

### UnrealEngine 版本

5.0.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

使用烘焙工具烘焙姿势资产时，点击start bake引擎就会崩溃，我使用的是UE5.2
[DigiHumanAnimation_2.log](https://github.com/endink/Mediapipe4u-plugin/files/12158980/DigiHumanAnimation_2.log)

**Comment by endink** [comment]
额~~，5.2 确实有问题~

**Comment by endink** [comment]
下个版本解决，你只能考虑用 5.1 烘焙一个然后升级资产到 5.2

**Comment by endink** [comment]
fix at 20230807
