### ISSUE TITLE
纯手部模型驱动不了

### ISSUE THREAD

**Issue by steven9439** [endink/Mediapipe4u-plugin#89]
### MediaPipe4U 版本

20230718

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

其他

### 错误详细描述

![image](https://github.com/endink/Mediapipe4u-plugin/assets/79041813/1870607c-b48e-4cf7-8217-95dfd1ddd08f)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/79041813/24464999-52e7-4ea8-b151-293dde9a79d6)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/79041813/763c16ae-0701-4ed7-825a-1d07e6717978)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/79041813/17af80b4-6b87-4f3a-8fc1-dc9482a763f3)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/79041813/a91fa773-d984-4797-97f0-4359fe1f0eac)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/79041813/aab1e1e0-6de4-4ea5-887f-68f16d7462cf)
![image](https://github.com/endink/Mediapipe4u-plugin/assets/79041813/93a50328-ef10-470e-bb0b-9ac7eea7348b)

**Comment by endink** [comment]
。。。。没考虑这种情况，我觉得即使你的网格体只有手，你也应该有一副完整的骨架，举个例子，手腕的计算需要依赖小臂，这样的依赖关系可能导致你的手不会动

**Comment by steven9439** [comment]
> 。。。。没考虑这种情况，我觉得即使你的网格体只有手，你也应该有一副完整的骨架，举个例子，手腕的计算需要依赖小臂，这样的依赖关系可能导致你的手不会动

好的，谢谢

**Comment by steven9439** [comment]
> 。。。。没考虑这种情况，我觉得即使你的网格体只有手，你也应该有一副完整的骨架，举个例子，手腕的计算需要依赖小臂，这样的依赖关系可能导致你的手不会动

还有个问题，模型老是晃来晃去的，怎么解决

**Comment by endink** [comment]
没太懂，禁用位移算解，或者锁定关节，调整平滑度这些都可以缓解不同的“晃来晃去“

**Comment by steven9439** [comment]
> 没太懂，禁用位移算解，或者锁定关节，调整平滑度这些都可以缓解不同的“晃来晃去“

好的 已经解决了 感谢
