### ISSUE TITLE
切换了蓝图中网格体的动画蓝图，再切回Mediapipe4u 的动画蓝图 ，就不能动捕了

### ISSUE THREAD

**Issue by guanjingkai** [endink/Mediapipe4u-plugin#9]
我的demo，默认设置成 Mediapipe4u 的蓝图动画，按下P动作捕捉正常，但是按V切换了动画蓝图，再按P，就不能动捕了，那个OSC协议的再反复切换是正常的
![image](https://user-images.githubusercontent.com/26058819/206251618-6a2d808f-231f-4d2f-a02c-92c56b277a00.png)
![image](https://user-images.githubusercontent.com/26058819/206251741-e0358fc0-a587-45f0-990e-465c7b35d564.png)

**Comment by endink** [comment]
mark, 蓝图需要支持初始化函数~

**Comment by endink** [comment]
切换动画蓝图后调用一下 BeginPlay 或许会解决问题？
