### ISSUE TITLE
语音识别的文字设置到文本框会导致崩溃

### ISSUE THREAD

**Issue by Uzaker** [endink/Mediapipe4u-plugin#90]
### MediaPipe4U 版本

20230718

### UnrealEngine 版本

5.1.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

在识别到事件中，将识别到的语音文本设置给文本框（EditableTextBox）会导致引擎崩溃，5.1和5.2都会崩溃。其实不影响使用，但我觉得应该告诉你。
[M4UBake.log](https://github.com/endink/Mediapipe4u-plugin/files/12178963/M4UBake.log)

**Comment by endink** [comment]
这是因为识别是一个后台线程，不能去访问UI, 你可以开启一个task 放到游戏线程设置文本框，后面会改进，蓝图事件都在游戏线程触发,先mark一下
