### ISSUE TITLE
Packaging failed

### ISSUE THREAD

**Issue by mitdave95** [endink/Mediapipe4u-plugin#91]
### MediaPipe4U Version

20230718

### UE Version

5.1.1

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

Packaging failed with below error for demo project

`__imp_gst_mini_object_copy referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_caps_set_simple referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_event_parse_caps referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_static_pad_template_get referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_pad_set_event_function_full referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_pad_event_default referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_plugin_register_static referenced in function "void __cdecl gst_videoscale2_register_static(void)" (?gst_videoscale2_register_static@@YAXXZ)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_factory_make referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_register referenced in function "int __cdecl plugin_init(struct _GstPlugin *)" (?plugin_init@@YAHPEAU_GstPlugin@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_class_add_pad_template referenced in function "void __cdecl gst_videoscale2_class_intern_init(void *)" (?gst_videoscale2_class_intern_init@@YAXPEAX@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_get_type referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_add_pad referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_get_static_pad referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_ghost_pad_new_from_template referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_element_link_many referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_bin_add_many referenced in function "void __cdecl gst_videoscale2_init(struct GstVideoScale2 *)" (?gst_videoscale2_init@@YAXPEAUGstVideoScale2@@@Z)
UATHelper: Packaging (Windows): gstvideoscale2.cpp.obj : error LNK2019: unresolved external symbol __imp_gst_video_info_from_caps referenced in function "int __cdecl gst_videoscale2_sink_event(struct _GstPad *,struct _GstObject *,struct _GstEvent *)" (?gst_videoscale2_sink_event@@YAHPEAU_GstPad@@PEAU_GstObject@@PEAU_GstEvent@@@Z)
UATHelper: Packaging (Windows): C:\WorkingDir\Unreal\MediaPipe4U-Demo-main\Binaries\Win64\MediaPipe4U_Demo.exe : fatal error LNK1120: 84 unresolved externals
UATHelper: Packaging (Windows): Took 6.0960872s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\Mit\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+UE_5.1\UBT-MediaPipe4U_Demo-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 7s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error`

Complete log file attached in the message

**Comment by mitdave95** [comment]
[UBT-MediaPipe4U_Demo-Win64-Development.txt](https://github.com/endink/Mediapipe4u-plugin/files/12189549/UBT-MediaPipe4U_Demo-Win64-Development.txt)

**Comment by endink** [comment]
You need install GStreamer sdk.   
refer this：   
https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/Install/gstreamer.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by mitdave95** [comment]
Installed the wrapper, and still it is failing. Should I remap all the plugins?

**Comment by endink** [comment]
After Install GSTREAMER, you need build project (compile) in VS or Rider. Don‘t execute "Rebuild" or "Clean" in VS/RIDER

**Comment by endink** [comment]
Are you sure you installed GStreamer correctly? Whether the environment variable contains the path to GS, this error is caused by the GS SDK not being found.

**Comment by mitdave95** [comment]
Yes, confirmed the installation and Environment Variables. 
Now getting a different error
[UBT-MediaPipe4U_Demo-Win64-Development-2.txt](https://github.com/endink/Mediapipe4u-plugin/files/12189648/UBT-MediaPipe4U_Demo-Win64-Development-2.txt)

**Comment by endink** [comment]
I  think your current environment is very messy, you should start all steps over again in another directory, look at the logs you seem to have reference the plugins twice

**Comment by mitdave95** [comment]
Will do

**Comment by mitdave95** [comment]
Soory again for being dumb about this but it failed with a new error of GSTREAMER

`UATHelper: Packaging (Windows): Determining max actions to execute in parallel (24 physical cores, 32 logical cores)
UATHelper: Packaging (Windows):   Executing up to 24 processes, one per physical core
UATHelper: Packaging (Windows): Building 2 actions with 2 processes...
UATHelper: Packaging (Windows): [1/2] WriteMetadata MediaPipe4U_Demo.target cancelled
UATHelper: Packaging (Windows): [2/2] Link MediaPipe4U_Demo.exe
UATHelper: Packaging (Windows): LINK : fatal error LNK1181: cannot open input file 'D:\gstreamer\1.0\msvc_x86_64\lib\glib-2.0.lib'
UATHelper: Packaging (Windows): Took 5.1865825999999995s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\Mit\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Epic+UE_5.1\UBT-MediaPipe4U_Demo-Win64-Development.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 6s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED`

**Comment by mitdave95** [comment]
Checked the lib folder but the file UE is trying to access, is not present. Not even hidden

![Screenshot (2)](https://github.com/endink/Mediapipe4u-plugin/assets/8618126/21eec912-0411-412e-b1ac-97d642b63512)

**Comment by mitdave95** [comment]
Pardon the above comments, I missed to install development package of GStreamer
https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/Install/gstreamer.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

All works. Thanks a ton for the help
