### ISSUE TITLE
Pose does not wrok

### ISSUE THREAD

**Issue by mitdave95** [endink/Mediapipe4u-plugin#92]
### MediaPipe4U Version

20230719

### UE Version

5.2.x

### UnrealEngine Type

Install From Epic Games Launcher

### What happened?

Trying to use the plugin with Environments like [The Bazaar](https://www.unrealengine.com/marketplace/en-US/product/persian-bazaar-ue4-ue5) following the youtube tutorial. No errors are thrown in output logs, but the pose does not work. 
Camera gets turned on, skeleton gets mapped and face mocap works, only body mocap does not work. 

Is there some setting which needs to enabled?

If I try the metahuman blueprint in an empty scene it works fine (both face and body)

**Comment by endink** [comment]
Do you switch animation blueprints or switch levels ?

**Comment by mitdave95** [comment]
Nope just 1 level and 1 metahuman

**Comment by endink** [comment]
If you are convenient, you can upload a log file.

**Comment by mitdave95** [comment]
Sure
[MoCap.log](https://github.com/endink/Mediapipe4u-plugin/files/12235288/MoCap.log)

**Comment by mitdave95** [comment]
Would the post processing animation blueprint require additional components?

**Comment by endink** [comment]
Nope, only MediaPipeHolisticComponent is required. From your log ,the bones was not ready:
```
Bones have been mapped, 17 joints waiting to be initailize.
```

**Comment by endink** [comment]
I guess your LOD changed, you can try forcing the LOD to be 0.

**Comment by mitdave95** [comment]
Tried, no effect

**Comment by endink** [comment]
Have you changed metahuman bone names, and how do you use BonePreset or MappingAsset?

**Comment by mitdave95** [comment]
No name change of bones and I followed your tutorial on youtube (https://www.youtube.com/watch?v=XLmKnG6UMzo&ab_channel=AndersXiao) for mapping of files

**Comment by endink** [comment]
This video use BonePreset "UE5", but your skeleton looks like incorrect. See your log:

```
+-----------------+-----------------+-------------------------+
| MediaPipe Joint | Bone            | ParentBone              |
+-----------------+-----------------+-------------------------+
+-----------------+-----------------+-------------------------+
| Nose            | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| LeftEyeInner    | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| LeftEye         | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| LeftEyeOuter    | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| RightEyeInner   | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| RightEye        | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| RightEyeOuter   | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| LeftEar         | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| RightEar        | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| MouthLeft       | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| MouthRight      | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
| LeftShoulder    | [11]upperarm_l  | [10]clavicle_l          |
+-----------------+-----------------+-------------------------+
| RightShoulder   | [142]upperarm_r | [141]clavicle_r         |
+-----------------+-----------------+-------------------------+
| LeftElbow       | [12]lowerarm_l  | [11]upperarm_l          |
+-----------------+-----------------+-------------------------+
| RightElbow      | [143]lowerarm_r | [142]upperarm_r         |
+-----------------+-----------------+-------------------------+
| LeftWrist       | [13]hand_l      | [12]lowerarm_l          |
+-----------------+-----------------+-------------------------+
| RightWrist      | [144]hand_r     | [143]lowerarm_r         |
+-----------------+-----------------+-------------------------+
| LeftPinky       | [37]pinky_01_l  | [36]pinky_metacarpal_l  |
+-----------------+-----------------+-------------------------+
| RightPinky      | [168]pinky_01_r | [167]pinky_metacarpal_r |
+-----------------+-----------------+-------------------------+
| LeftIndex       | [98]index_01_l  | [97]index_metacarpal_l  |
+-----------------+-----------------+-------------------------+
| RightIndex      | [229]index_01_r | [228]index_metacarpal_r |
+-----------------+-----------------+-------------------------+
| LeftThumb       | [81]thumb_02_l  | [80]thumb_01_l          |
+-----------------+-----------------+-------------------------+
| RightThumb      | [212]thumb_02_r | [211]thumb_01_r         |
+-----------------+-----------------+-------------------------+
| LeftHip         | [276]thigh_l    | [1]pelvis               |
+-----------------+-----------------+-------------------------+
| RightHip        | [309]thigh_r    | [1]pelvis               |
+-----------------+-----------------+-------------------------+
| LeftKnee        | [277]calf_l     | [276]thigh_l            |
+-----------------+-----------------+-------------------------+
| RightKnee       | [310]calf_r     | [309]thigh_r            |
+-----------------+-----------------+-------------------------+
| LeftAnkle       | [278]foot_l     | [277]calf_l             |
+-----------------+-----------------+-------------------------+
| RightAnkle      | [311]foot_r     | [310]calf_r             |
+-----------------+-----------------+-------------------------+
| LeftHeel        | [278]foot_l     | [277]calf_l             |
+-----------------+-----------------+-------------------------+
| RightHeel       | [311]foot_r     | [310]calf_r             |
+-----------------+-----------------+-------------------------+
| LeftFootIndex   | [279]ball_l     | [278]foot_l             |
+-----------------+-----------------+-------------------------+
| RightFootIndex  | [312]ball_r     | [311]foot_r             |
+-----------------+-----------------+-------------------------+
| Hip             | [1]pelvis       | [0]root                 |
+-----------------+-----------------+-------------------------+
| Head            | [9]head         | [8]neck_02              |
+-----------------+-----------------+-------------------------+
| Neck            | [7]neck_01      | [6]spine_05             |
+-----------------+-----------------+-------------------------+
| Chest           | [6]spine_05     | [5]spine_04             |
+-----------------+-----------------+-------------------------+
| Spine           | [2]spine_01     | [1]pelvis               |
+-----------------+-----------------+-------------------------+
| Jaw             | [-1]None        |                         |
+-----------------+-----------------+-------------------------+
```

For example, thigh_l mape to pelvis is wrong, please check your BonePreset settings, and try use a mapping asset instead of built-in mapping. Refer this doc:

https://opensource-labijie-com.translate.goog/Mediapipe4u-plugin/mocap/quick_start/custom_skeleton.html?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp

**Comment by endink** [comment]
Forgive my last commit, I read wrong

**Comment by endink** [comment]
After camera started, execute command in UE Editor: "stat m4u", and upload a screenshot.

**Comment by mitdave95** [comment]
![Screenshot (3)](https://github.com/endink/Mediapipe4u-plugin/assets/8618126/761c343a-fdec-4202-b1d0-527c0aed0550)
Here it is

**Comment by endink** [comment]
OK, your Pose Solver FPS is 0, means Pose Solver animation node does not evaluate, try this step:

1. Check your animation LOD (in C++: UAnimInstance.GetLODLevel can do this, may be in debug? I dont know how to get this in Blueprint, may be google it)
2. Check mediapipe is connected to AnimationInstance (get MediapipeAnimInstance from skeleton mesh component, call IsMediaPipeConnected, you can do it in blueprint).
3. Check pose solver anim node is processed (Debug your animation blueprint, make sure the process goes through the pose solver node)

**Comment by mitdave95** [comment]
Let me try these

**Comment by endink** [comment]
BTW, image source FPS is too low, its means your image source (webcam or video file) is too slow. This will determine the mediapipe FPS cap.

**Comment by mitdave95** [comment]
Got it

**Comment by mitdave95** [comment]
1. LOD is set to 0
2. MediapipeAnimInstance is connected but not running

The issue is happening only when Metahuman is used with the environment. If I create an empty scene and use Metahuman, it works fine

**Comment by endink** [comment]
Do you have a minimum reproduction step for this issue?

**Comment by endink** [comment]
I know a lot of users who use my plugin, their scenes are also very complex, did you debug your animation blueprint, did the breakpoint hit the pose solver node?

**Comment by mitdave95** [comment]
For reproduction, you can add the Metahuman on the Demo Bazaar scene (it was free last month, it is paid now :( )
I am new to Unreal, switching from Unity. I might be missing something, I am taking a look with fresh eyes and see if I can resolve it
