### ISSUE TITLE
NDI WebCam Audio

### ISSUE THREAD

**Issue by Unknown792** [endink/Mediapipe4u-plugin#93]
### Feature Category

New Runtime Feature

### Feature Description

您好，我现在使用NDI Webcam来进行拉流动捕，在场景中回显视频，但是没有音频，我看了文档中并没有相关的设置，请问可以添加NDI Webcam回显功能的音频回显吗。

**Comment by Unknown792** [comment]
好的，我看了一下文档，其中关于MediaPlayerImageSource的使用提供的接口一个是 Open Source 另一个是 Open Url，这两个接口看上去好像不支持摄像头的接入，还是有另外的接口可以打开摄像头呢

**Comment by endink** [comment]
mediaplayer image source 你可以直接操作UE 的 MediaPlayer组件，他会自动捕获画面到 mediapipe

**Comment by endink** [comment]
关于 MediaPlayer 如何使用，你需要自己学习
