### ISSUE TITLE
Version 2023-08-07 is not being built, errors are being issued

### ISSUE THREAD

**Issue by endink** [endink/Mediapipe4u-plugin#95]
### Discussed in https://github.com/endink/Mediapipe4u-plugin/discussions/94

<div type='discussions-op-text'>

<sup>Originally posted by **caslix** August  9, 2023</sup>
Hello!
Version 2023-08-07 for UE5.1 generates the following error during assembly:

2>Building MediaPipe4U_DemoEditor...
2>Using Visual Studio 2022 14.37.32822 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
2>Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
2>  Executing up to 12 processes, one per physical core
2>Building 2 actions with 2 processes...
2>[1/2] Link UnrealEditor-MediaPipeLLMSpeech.dll
2>   Создается библиотека C:\MediaPipe4U-Demo-main_20230617\Plugins\MediaPipe4ULLMSpeech\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipeLLMSpeech\UnrealEditor-MediaPipeLLMSpeech.suppressed.lib и объект C:\MediaPipe4U-Demo-main_20230617\Plugins\MediaPipe4ULLMSpeech\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipeLLMSpeech\UnrealEditor-MediaPipeLLMSpeech.suppressed.exp
2>LLMSpeechBlueprintLibrary.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: static void __cdecl ULLMSpeechBlueprintLibrary::SetSpeechActorForLLM(class AMediaPipeSpeechActor *)" (?SetSpeechActorForLLM@ULLMSpeechBlueprintLibrary@@SAXPEAVAMediaPipeSpeechActor@@@Z) в функции "public: static void __cdecl ULLMSpeechBlueprintLibrary::execSetSpeechActorForLLM(class UObject *,struct FFrame &,void * const)" (?execSetSpeechActorForLLM@ULLMSpeechBlueprintLibrary@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
2>C:\MediaPipe4U-Demo-main_20230617\Plugins\MediaPipe4ULLMSpeech\Binaries\Win64\UnrealEditor-MediaPipeLLMSpeech.dll : fatal error LNK1120: неразрешенных внешних элементов: 1
2>[2/2] WriteMetadata MediaPipe4U_DemoEditor.target cancelled
2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: выход из команды ""C:\Program Files\Epic Games\UE_5.1\Engine\Build\BatchFiles\Build.bat" MediaPipe4U_DemoEditor Win64 Development -Project="C:\MediaPipe4U-Demo-main_20230617\MediaPipe4U-Demo.uproject" -WaitMutex -FromMsBuild" с кодом 6.
2>Сборка проекта "MediaPipe4U-Demo.vcxproj" завершена с ошибкой.
========== Сборка: успешно выполнено — 0 , со сбоем — 1, в актуальном состоянии — 0, пропущено — 1 ==========
========== Сборка запущено в 17:42, заняло 03,965 с ==========</div>

**Comment by caslix** [comment]
To clean up the project, I use clean_project.bat. Accordingly, all folders are deleted. Downloaded the new version 2023.08.09. The errors are different, but similar:
----------------------------------------------------------------

2>Creating makefile for MediaPipe4U_DemoEditor (no existing makefile)
2>Find MediaPipe File: mediapipe4u.license
2>GStreamer path:
2>C:\gstreamer\1.0\msvc_x86_64\
2>Parsing headers for MediaPipe4U_DemoEditor
2>  Running Internal UnrealHeaderTool C:\MediaPipe4U-Demo-main_2022.1.1.20230617\MediaPipe4U-Demo.uproject C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Intermediate\Build\Win64\MediaPipe4U_DemoEditor\Development\MediaPipe4U_DemoEditor.uhtmanifest -WarningsAsErrors -installed
2>Total of 6 written
2>Reflection code generated for MediaPipe4U_DemoEditor in 0.8328763 seconds
2>Building MediaPipe4U_DemoEditor...
2>Using Visual Studio 2022 14.37.32822 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
2>Determining max actions to execute in parallel (12 physical cores, 24 logical cores)
2>  Executing up to 12 processes, one per physical core
2>Building 19 actions with 12 processes...
2>[1/19] Copy mediapipe4u.license
2>[2/19] Resource Default.rc2
2>[3/19] Resource Default.rc2
2>[4/19] Compile SampleImageConsumer.cpp
2>[5/19] Compile MediaPipe4U_Demo.init.gen.cpp
2>[6/19] Compile FileHelper.gen.cpp
2>[7/19] Compile FMediaPipe4UDemoMoulder.cpp
2>[8/19] Compile FileHelper.cpp
2>[9/19] Compile MediaPipe4U_DemoGameModeBase.cpp
2>[10/19] Compile MediaPipe4U_DemoGameModeBase.gen.cpp
2>[11/19] Link UnrealEditor-MediaPipe4U_Demo.lib
2>   Создается библиотека C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipe4U_Demo\UnrealEditor-MediaPipe4U_Demo.lib и объект C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipe4U_Demo\UnrealEditor-MediaPipe4U_Demo.exp
2>[12/19] Link UnrealEditor-MediaPipe4U_Demo.dll
2>   Создается библиотека C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipe4U_Demo\UnrealEditor-MediaPipe4U_Demo.suppressed.lib и объект C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipe4U_Demo\UnrealEditor-MediaPipe4U_Demo.suppressed.exp
2>[13/19] Compile SharedPCH.Engine.ShadowErrors.cpp
2>[14/19] Compile MediaPipeLLMSpeech.init.gen.cpp
2>[15/19] Compile LLMSpeechBlueprintLibrary.gen.cpp
2>[16/19] Compile LLMSpeechChatRuntime.gen.cpp
2>[17/19] Link UnrealEditor-MediaPipeLLMSpeech.lib
2>   Создается библиотека C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Plugins\MediaPipe4ULLMSpeech\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipeLLMSpeech\UnrealEditor-MediaPipeLLMSpeech.lib и объект C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Plugins\MediaPipe4ULLMSpeech\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipeLLMSpeech\UnrealEditor-MediaPipeLLMSpeech.exp
2>[18/19] Link UnrealEditor-MediaPipeLLMSpeech.dll
2>   Создается библиотека C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Plugins\MediaPipe4ULLMSpeech\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipeLLMSpeech\UnrealEditor-MediaPipeLLMSpeech.suppressed.lib и объект C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Plugins\MediaPipe4ULLMSpeech\Intermediate\Build\Win64\UnrealEditor\Development\MediaPipeLLMSpeech\UnrealEditor-MediaPipeLLMSpeech.suppressed.exp
2>LLMSpeechBlueprintLibrary.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: static void __cdecl ULLMSpeechBlueprintLibrary::SetSpeechActorForLLM(class AMediaPipeSpeechActor *)" (?SetSpeechActorForLLM@ULLMSpeechBlueprintLibrary@@SAXPEAVAMediaPipeSpeechActor@@@Z) в функции "public: static void __cdecl ULLMSpeechBlueprintLibrary::execSetSpeechActorForLLM(class UObject *,struct FFrame &,void * const)" (?execSetSpeechActorForLLM@ULLMSpeechBlueprintLibrary@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: __cdecl ALLMSpeechChatRuntime::ALLMSpeechChatRuntime(void)" (??0ALLMSpeechChatRuntime@@QEAA@XZ) в функции "void __cdecl InternalConstructor<class ALLMSpeechChatRuntime>(class FObjectInitializer const &)" (??$InternalConstructor@VALLMSpeechChatRuntime@@@@YAXAEBVFObjectInitializer@@@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: bool __cdecl ALLMSpeechChatRuntime::IsReady(void)const " (?IsReady@ALLMSpeechChatRuntime@@QEBA_NXZ) в функции "public: static void __cdecl ALLMSpeechChatRuntime::execIsReady(class UObject *,struct FFrame &,void * const)" (?execIsReady@ALLMSpeechChatRuntime@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: bool __cdecl ALLMSpeechChatRuntime::IsRunning(void)const " (?IsRunning@ALLMSpeechChatRuntime@@QEBA_NXZ) в функции "public: bool __cdecl ALLMSpeechChatRuntime::IsAssistantRound(void)const " (?IsAssistantRound@ALLMSpeechChatRuntime@@QEBA_NXZ).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: bool __cdecl ALLMSpeechChatRuntime::Run(void)" (?Run@ALLMSpeechChatRuntime@@QEAA_NXZ) в функции "public: static void __cdecl ALLMSpeechChatRuntime::execRun(class UObject *,struct FFrame &,void * const)" (?execRun@ALLMSpeechChatRuntime@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: void __cdecl ALLMSpeechChatRuntime::Shutdown(void)" (?Shutdown@ALLMSpeechChatRuntime@@QEAAXXZ) в функции "public: static void __cdecl ALLMSpeechChatRuntime::execShutdown(class UObject *,struct FFrame &,void * const)" (?execShutdown@ALLMSpeechChatRuntime@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: enum EChatRound __cdecl ALLMSpeechChatRuntime::GetRound(void)const " (?GetRound@ALLMSpeechChatRuntime@@QEBA?AW4EChatRound@@XZ) в функции "public: bool __cdecl ALLMSpeechChatRuntime::IsAssistantRound(void)const " (?IsAssistantRound@ALLMSpeechChatRuntime@@QEBA_NXZ).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "public: void __cdecl ALLMSpeechChatRuntime::GetChatStatusText(class FText &,class FText,class FText,class FText,class FText,class FText)const " (?GetChatStatusText@ALLMSpeechChatRuntime@@QEBAXAEAVFText@@V2@1111@Z) в функции "public: static void __cdecl ALLMSpeechChatRuntime::execGetChatStatusText(class UObject *,struct FFrame &,void * const)" (?execGetChatStatusText@ALLMSpeechChatRuntime@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2001: неразрешенный внешний символ "protected: virtual void __cdecl ALLMSpeechChatRuntime::BeginPlay(void)" (?BeginPlay@ALLMSpeechChatRuntime@@MEAAXXZ).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2001: неразрешенный внешний символ "protected: virtual void __cdecl ALLMSpeechChatRuntime::EndPlay(enum EEndPlayReason::Type)" (?EndPlay@ALLMSpeechChatRuntime@@MEAAXW4Type@EEndPlayReason@@@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "protected: void __cdecl ALLMSpeechChatRuntime::OnLLMCompletionFinished(struct FLLMCompletionResult const &)" (?OnLLMCompletionFinished@ALLMSpeechChatRuntime@@IEAAXAEBUFLLMCompletionResult@@@Z) в функции "public: static void __cdecl ALLMSpeechChatRuntime::execOnLLMCompletionFinished(class UObject *,struct FFrame &,void * const)" (?execOnLLMCompletionFinished@ALLMSpeechChatRuntime@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2019: ссылка на неразрешенный внешний символ "protected: void __cdecl ALLMSpeechChatRuntime::OnTextRecognized(class FString const &,bool)" (?OnTextRecognized@ALLMSpeechChatRuntime@@IEAAXAEBVFString@@_N@Z) в функции "public: static void __cdecl ALLMSpeechChatRuntime::execOnTextRecognized(class UObject *,struct FFrame &,void * const)" (?execOnTextRecognized@ALLMSpeechChatRuntime@@SAXPEAVUObject@@AEAUFFrame@@QEAX@Z).
2>LLMSpeechChatRuntime.gen.cpp.obj : error LNK2001: неразрешенный внешний символ "public: virtual void __cdecl ALLMSpeechChatRuntime::Tick(float)" (?Tick@ALLMSpeechChatRuntime@@UEAAXM@Z).
2>C:\MediaPipe4U-Demo-main_2022.1.1.20230617\Plugins\MediaPipe4ULLMSpeech\Binaries\Win64\UnrealEditor-MediaPipeLLMSpeech.dll : fatal error LNK1120: неразрешенных внешних элементов: 13
2>[19/19] WriteMetadata MediaPipe4U_DemoEditor.target cancelled
2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: выход из команды ""C:\Program Files\Epic Games\UE_5.1\Engine\Build\BatchFiles\Build.bat" MediaPipe4U_DemoEditor Win64 Development -Project="C:\MediaPipe4U-Demo-main_2022.1.1.20230617\MediaPipe4U-Demo.uproject" -WaitMutex -FromMsBuild" с кодом 6.
2>Сборка проекта "MediaPipe4U-Demo.vcxproj" завершена с ошибкой.
========== Сборка: успешно выполнено — 0 , со сбоем — 1, в актуальном состоянии — 0, пропущено — 1 ==========
========== Сборка запущено в 11:42, заняло 45,847 с ==========

**Comment by endink** [comment]
Do you use VS or Rider's Rebuild? Please do not use the IDE's Rebuild or Clean, this will break the precompiled plugin, you should only use Build

**Comment by caslix** [comment]
I use VS 2022. I don't use Rebuild or Clean IDE. Apparently, something really needs to be updated in the demo version. I tried to clean everything again, but to no avail. The M4U_UE5_1_20230628 version compiles without problems.

**Comment by endink** [comment]
Okay, I will check this in Demo project.

**Comment by endink** [comment]
In the current situation, you can only delete Speech and LLM-related plugins for temporary use

**Comment by endink** [comment]
Its a bug, I will drop 202308xx version, and back to 20230718

**Comment by endink** [comment]
If you want to use 202308XX version, you need manually fix compilation errors:
at MediaPipeLLMSpeech.Build.cs.

Add a line after `PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;`
```
bPrecompile = true;
```

Before performing any "Build" action !

or Delete MediaPipe4ULLMSpeech plugin

**Comment by endink** [comment]
I I believe that this issue has been fixed in the 20200811.
