### ISSUE TITLE
SpeechActor导致崩溃

### ISSUE THREAD

**Issue by Uzaker** [endink/Mediapipe4u-plugin#96]
### MediaPipe4U 版本

20230718

### UnrealEngine 版本

5.2.x

### UnrealEngine 类型

Launcher

### 问题类型

运行错误

### 错误详细描述

上午还能正常运行，下午发现一点运行就崩溃，把关卡中的MediaPipeSpeechActor删掉就不崩溃了，添加回来又崩溃，更新到最新版本插件还是崩溃。
[DigiHumanAnimation.log](https://github.com/endink/Mediapipe4u-plugin/files/12311262/DigiHumanAnimation.log)

**Comment by endink** [comment]
你贴的应该不是崩溃时候的日志， 方便把崩溃时候 UE 那个窗口也截个图？

**Comment by Uzaker** [comment]
LoginId:9031fd28449986a5d92a42a7aea75de2
EpicAccountId:a2eed576f6ab4708b99dc9b267b23a81

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000018

speech_api
speech_api
speech_api
speech_api
speech_api
UnrealEditor_MediaPipeSpeech
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll
![123](https://github.com/endink/Mediapipe4u-plugin/assets/92619445/841895ce-2f6f-40d4-9577-a0a09ed2c255)
[DigiHumanAnimation.log](https://github.com/endink/Mediapipe4u-plugin/files/12318302/DigiHumanAnimation.log)
这是点click here to view directory找到的日志

**Comment by endink** [comment]
额，看起来和另外一个 BUG 很类似，我尽快复现，鉴于现在的情况，你只能删除 speech 和 LLM 相关的插件暂时用着

**Comment by endink** [comment]
我猜测是没有 Speech 模型导致的，但是这不应该崩溃，这可能是一个 BUG

**Comment by endink** [comment]
看日志发生在工具窗口，暂时不要使用 MediaPipe4U 提供的 Speech 工具，从蓝图操作 TTS

**Comment by endink** [comment]
版本 20200811 已修复窗口崩溃问题.

**Comment by endink** [comment]
最新版已经修复空文件夹问题

**Comment by endink** [comment]
你似乎没有更新到最新版，如果最新版问题依旧，请提交一个新的 issue ， 你可以在新的 issue 中贴出蓝图，日志里我没有看到错误，可能你没有贴出崩溃时候的日志
