### ISSUE TITLE
Use Nvidia's body tracking feature from AR SDK

### ISSUE THREAD

**Issue by mitdave95** [endink/Mediapipe4u-plugin#98]
### Feature Category

New Runtime Feature

### Feature Description

Ability to select between Nvidia's AR SDK and Mediapipe for body tracking

**Comment by endink** [comment]
1. The main problem is that nvidia lacks hand landmarks, which makes it possible to still need mediapipe for this solution.
    
2. Mediapipe can support mobile, but nvar cannot, although mobile support is not currently planned, but it is technically possible

**Comment by endink** [comment]
No plan for this
