### ISSUE TITLE
使用源碼版的UE5.2.0 將Plugin放入項目後 GenerateProjectFile時報錯 無法開啟項目

### ISSUE THREAD

**Issue by RAPUTADEV** [endink/Mediapipe4u-plugin#99]
### MediaPipe4U 版本

20230809

### UnrealEngine 版本

5.2.x

### UnrealEngine 类型

源码编译

### 问题类型

插件安装

### 错误详细描述

將Mediapipe放到Engine/Plugins/
在GenerateProjectFile時出現這個錯誤 (測過其他Plugin沒問題)
![image (1)](https://github.com/endink/Mediapipe4u-plugin/assets/123104166/3234e27d-02fe-4da3-8de2-682477204303)

將Mediapipe放到項目的Plugins/
選擇Generate Visual Studio project files出現類似的錯誤
![image](https://github.com/endink/Mediapipe4u-plugin/assets/123104166/7dbfd130-552b-4416-bc88-f242a28b3c0f)

從項目.sln開啟 用Visual Studio build他一樣出現此錯誤
[New Text Document.txt](https://github.com/endink/Mediapipe4u-plugin/files/12329250/New.Text.Document.txt)

C:\UE5_2\Engine\Plugins\MediaPipe4U\Source\ThirdParty\CryptoPP\CryptoPP.Build.cs(4,14): error CS0101: The namespace '<global namespace>' already contains a definition for 'CryptoPP'

C:\UE5_2\Engine\Plugins\MediaPipe4U\Source\ThirdParty\CryptoPP\CryptoPP.Build.cs(8,12): error CS0111: Type 'CryptoPP' already defines a member called 'CryptoPP' with the same parameter types

*我的環境能build成功UE5.2.1, UE5.2.0的源碼 並且能開啟具有其他支援UE5.2 plugin的項目
*不放入Mediapipe的話 項目能正常開啟

**Comment by endink** [comment]
额~~~这种问题会比较麻烦，你的项目里有其他德程序使用了  CryptoPP，而 MediaPipe4U 也使用了 CryptoPP

**Comment by endink** [comment]
你的项目里是否有另外一个 CryptoPP

**Comment by endink** [comment]
搜索 CryptoPP 看以下，可能其他插件里存在 CryptoPP

**Comment by RAPUTADEV** [comment]
有的 就在UE5.2源碼的 Engine/Source/ThirdParty/CryptoPP
我應該要刪除他 或是刪除MediaPipe4U/Source/ThirdParty/CryptoPP ?

**Comment by endink** [comment]
我建议你删除引擎里的试试

**Comment by endink** [comment]
记得备份一下

**Comment by endink** [comment]
另外，请不要使用0809版本的插件，0809有BUG

**Comment by RAPUTADEV** [comment]
將UE5.2源碼裡的CryptoPP移除後
試著將Mediapipe放入Engine/Plugins
GenerateProjectFiles過了 但一開UE5.sln就給我這個
![image](https://github.com/endink/Mediapipe4u-plugin/assets/123104166/5e324f9e-8a48-4cf8-bdaa-26366bec7808)

於是我改將Mediapipe中的CryptoPP移除
Mediapipe一樣放在Engine/Plugins 
GenerateProjectFiles之後 build UE5.sln
結果是開啟UE時在Plugin能找到MediaPipe了 但是勾選後重啟UE 又會抱怨Mediapipe版本不同需要開IDE重編

目前正在測試在Mediapipe放入Engine/Plugins後
將Plugin裡面的intermediate和binaries都刪除
重新再build一次UE5 看看這次會不會幫我compile Mediapipe plugin

**Comment by endink** [comment]
额~~~这个问题可能你这样处理不了

**Comment by endink** [comment]
我需要确认以下 CryptoPP 是否是 5.2 引擎自带的，如果是我可以移除它，使用引擎里的版本，但是这要等下一个版本

**Comment by endink** [comment]
你可以尝试这样处理，我不确定能不能兼容：

1. 移除 M4U 插件中的 CryptoCPP 
2. 修改 Build.cs, 删除 private dependencies 中的 Crypto
3. 修改 Build.cs, 添加如下内容：
```cs
        AddEngineThirdPartyPrivateStaticDependencies(Target,
                "CryptoPP"
                );
        PublicIncludePathModuleNames.Add("CryptoPP");
```

**Comment by RAPUTADEV** [comment]
我照你的方法嘗試 編譯時沒有出現錯誤 但是開啟項目時仍然會跳出一樣的訊息

**Comment by RAPUTADEV** [comment]
不過我上面是在Engine/Plugin中編譯
LinkType和copy_intermediate.bat 我不知道要放哪邊 我目前是都沒有放

**Comment by endink** [comment]
嗯？你既然编译能通过还会报错？

**Comment by RAPUTADEV** [comment]
我是編譯整個UE5 沒有錯誤訊息
打開UE5也能看到Mediapipe plugin
但是只要勾選 重啟UE5之後 就會跳這個
![image (1)](https://github.com/endink/Mediapipe4u-plugin/assets/123104166/551799d8-c03e-4c31-add2-6ff70c11b42e)

**Comment by endink** [comment]
首先，不用每次都编译整个引擎，这通常无济于事，你只需要重新编译项目（建议使用 VS 或者 Rider 编译），要记住，你不能删除插件中的任何文件夹，尤其不能删除 intermediate和binaries， 因为这是预编译插件，你没有源代码，编译好的 c++ link 文件都在这些文件夹中，你也不能在 IDE 里 clean 或者 rebuild 工程，因为这些操作会清理 intermediate， 你只需要在 IDE 里 Build 工程，你可以尝试这样清理项目：

1. 删除工程根目录下的：
    - DerivedDataCache
    - Intermediate
    - Saved 
2. 鼠标右键点击 uproject 文件，点击 generate visual studio project files
3. 打开生成的 .sln 文件（使用 VS或Rider）
4. IDE 中 build 工程，如果没有报错，此时你就可以双击 .uproject 文件用 UE Editor 打开工程了

**Comment by endink** [comment]
不建议你在 Engine/Plugins 目录中放置插件，可能你不需要执行 copy_intermediate.bat（不确定）， 这个是针对把插件放在项目里需要打包时候的操作

**Comment by endink** [comment]
BTW： 你最开始的问题问题可能就是由于插件被放到引擎目录，和引擎里的 CryptoCPP 冲突了，或许你把插件放到工程中就可以解决问题

**Comment by endink** [comment]
如果你希望把插件放到引擎，在多个项目之间共享插件，可以放到 Engine\Plugins\Marketplace

**Comment by endink** [comment]
很高兴能够帮到你，请不要使用 `20230809` 版本它会创建丢失一些字符的空文件夹，而且工具箱会造成崩溃, 请务必升级 20230811，给您添麻烦了~

**Comment by RAPUTADEV** [comment]
另外我也測試了重新下載Mediapipe plugin用你的方法操作一次
是能成功打開的
證明你是對的
CryptoPP當Mediapipe放在項目/Plugin這邊build是不會跟Engine的CryptoPP衝突的

**Comment by endink** [comment]
你如果希望放在引擎，考虑放在  Engine\Plugins\Marketplace， Engine\Plugins 是引擎自带插件， Engine\Plugins\Marketplace 代表从商店都买的插件，引擎插件可以访问一些引擎私有的东西，而外部插件不行，不建议把一个外部插件当作引擎插件对待，这会遇到很多麻烦

**Comment by RAPUTADEV** [comment]
> 很高兴能够帮到你，请不要使用 `20230809` 版本它会创建丢失一些字符的空文件夹，而且工具箱会造成崩溃, 请务必升级 20230811，给您添麻烦了~

不會 我很感激你做了這個項目
